//
//  jit.h
//
//  DANGER - This is machine generated code
//

#ifndef riscv_jit_h
#define riscv_jit_h

namespace riscv
{
	inst_t emit_lui(ireg5 rd, simm32 imm20);
	inst_t emit_auipc(ireg5 rd, offset32 oimm20);
	inst_t emit_jal(ireg5 rd, offset21 jimm20);
	inst_t emit_jalr(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_beq(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_bne(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_blt(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_bge(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_bltu(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_bgeu(ireg5 rs1, ireg5 rs2, offset13 sbimm12);
	inst_t emit_lb(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_lh(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_lw(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_lbu(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_lhu(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_sb(ireg5 rs1, ireg5 rs2, offset12 simm12);
	inst_t emit_sh(ireg5 rs1, ireg5 rs2, offset12 simm12);
	inst_t emit_sw(ireg5 rs1, ireg5 rs2, offset12 simm12);
	inst_t emit_addi(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_slti(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_sltiu(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_xori(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_ori(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_andi(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_slli_rv32i(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_srli_rv32i(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_srai_rv32i(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_add(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sub(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sll(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_slt(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sltu(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_xor(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_srl(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sra(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_or(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_and(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_fence(arg4 pred, arg4 succ);
	inst_t emit_fence_i();
	inst_t emit_lwu(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_ld(ireg5 rd, ireg5 rs1, offset12 oimm12);
	inst_t emit_sd(ireg5 rs1, ireg5 rs2, offset12 simm12);
	inst_t emit_slli_rv64i(ireg5 rd, ireg5 rs1, uimm6 shamt6);
	inst_t emit_srli_rv64i(ireg5 rd, ireg5 rs1, uimm6 shamt6);
	inst_t emit_srai_rv64i(ireg5 rd, ireg5 rs1, uimm6 shamt6);
	inst_t emit_addiw(ireg5 rd, ireg5 rs1, simm12 imm12);
	inst_t emit_slliw(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_srliw(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_sraiw(ireg5 rd, ireg5 rs1, uimm5 shamt5);
	inst_t emit_addw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_subw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sllw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_srlw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_sraw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_mul(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_mulh(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_mulhsu(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_mulhu(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_div(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_divu(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_rem(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_remu(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_mulw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_divw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_divuw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_remw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_remuw(ireg5 rd, ireg5 rs1, ireg5 rs2);
	inst_t emit_lr_w(ireg5 rd, ireg5 rs1, arg1 aq, arg1 rl);
	inst_t emit_sc_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoswap_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoadd_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoxor_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoor_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoand_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomin_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomax_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amominu_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomaxu_w(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_lr_d(ireg5 rd, ireg5 rs1, arg1 aq, arg1 rl);
	inst_t emit_sc_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoswap_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoadd_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoxor_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoor_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amoand_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomin_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomax_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amominu_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_amomaxu_d(ireg5 rd, ireg5 rs1, ireg5 rs2, arg1 aq, arg1 rl);
	inst_t emit_ecall();
	inst_t emit_ebreak();
	inst_t emit_uret();
	inst_t emit_sret();
	inst_t emit_hret();
	inst_t emit_mret();
	inst_t emit_dret();
	inst_t emit_sfence_vm(ireg5 rs1);
	inst_t emit_wfi();
	inst_t emit_csrrw(ireg5 rd, ireg5 rs1, uimm12 csr12);
	inst_t emit_csrrs(ireg5 rd, ireg5 rs1, uimm12 csr12);
	inst_t emit_csrrc(ireg5 rd, ireg5 rs1, uimm12 csr12);
	inst_t emit_csrrwi(ireg5 rd, uimm5 zimm, uimm12 csr12);
	inst_t emit_csrrsi(ireg5 rd, uimm5 zimm, uimm12 csr12);
	inst_t emit_csrrci(ireg5 rd, uimm5 zimm, uimm12 csr12);
	inst_t emit_flw(freg5 frd, ireg5 rs1, offset12 oimm12);
	inst_t emit_fsw(ireg5 rs1, freg5 frs2, offset12 simm12);
	inst_t emit_fmadd_s(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fmsub_s(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fnmsub_s(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fnmadd_s(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fadd_s(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fsub_s(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fmul_s(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fdiv_s(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fsgnj_s(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fsgnjn_s(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fsgnjx_s(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fmin_s(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fmax_s(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fsqrt_s(freg5 frd, freg5 frs1, arg3 rm);
	inst_t emit_fle_s(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_flt_s(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_feq_s(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_fcvt_w_s(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_wu_s(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_s_w(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fcvt_s_wu(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fmv_x_s(ireg5 rd, freg5 frs1);
	inst_t emit_fclass_s(ireg5 rd, freg5 frs1);
	inst_t emit_fmv_s_x(freg5 frd, ireg5 rs1);
	inst_t emit_fcvt_l_s(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_lu_s(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_s_l(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fcvt_s_lu(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fld(freg5 frd, ireg5 rs1, offset12 oimm12);
	inst_t emit_fsd(ireg5 rs1, freg5 frs2, offset12 simm12);
	inst_t emit_fmadd_d(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fmsub_d(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fnmsub_d(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fnmadd_d(freg5 frd, freg5 frs1, freg5 frs2, freg5 frs3, arg3 rm);
	inst_t emit_fadd_d(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fsub_d(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fmul_d(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fdiv_d(freg5 frd, freg5 frs1, freg5 frs2, arg3 rm);
	inst_t emit_fsgnj_d(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fsgnjn_d(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fsgnjx_d(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fmin_d(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fmax_d(freg5 frd, freg5 frs1, freg5 frs2);
	inst_t emit_fcvt_s_d(freg5 frd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_d_s(freg5 frd, freg5 frs1, arg3 rm);
	inst_t emit_fsqrt_d(freg5 frd, freg5 frs1, arg3 rm);
	inst_t emit_fle_d(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_flt_d(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_feq_d(ireg5 rd, freg5 frs1, freg5 frs2);
	inst_t emit_fcvt_w_d(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_wu_d(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_d_w(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fcvt_d_wu(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fclass_d(ireg5 rd, freg5 frs1);
	inst_t emit_fcvt_l_d(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fcvt_lu_d(ireg5 rd, freg5 frs1, arg3 rm);
	inst_t emit_fmv_x_d(ireg5 rd, freg5 frs1);
	inst_t emit_fcvt_d_l(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fcvt_d_lu(freg5 frd, ireg5 rs1, arg3 rm);
	inst_t emit_fmv_d_x(freg5 frd, ireg5 rs1);
}

#endif
