//
//  riscv-opcodes.cc
//
//  DANGER - This is machine generated code
//

#include "riscv-types.h"
#include "riscv-format.h"
#include "riscv-opcodes.h"

const char* riscv_instruction_name[] = {
	/*              unknown */ "unknown",
	/*                  lui */ "lui",
	/*                auipc */ "auipc",
	/*                  jal */ "jal",
	/*                 jalr */ "jalr",
	/*                  beq */ "beq",
	/*                  bne */ "bne",
	/*                  blt */ "blt",
	/*                  bge */ "bge",
	/*                 bltu */ "bltu",
	/*                 bgeu */ "bgeu",
	/*                   lb */ "lb",
	/*                   lh */ "lh",
	/*                   lw */ "lw",
	/*                  lbu */ "lbu",
	/*                  lhu */ "lhu",
	/*                   sb */ "sb",
	/*                   sh */ "sh",
	/*                   sw */ "sw",
	/*                 addi */ "addi",
	/*                 slti */ "slti",
	/*                sltiu */ "sltiu",
	/*                 xori */ "xori",
	/*                  ori */ "ori",
	/*                 andi */ "andi",
	/*           slli.rv32i */ "slli",
	/*           srli.rv32i */ "srli",
	/*           srai.rv32i */ "srai",
	/*                  add */ "add",
	/*                  sub */ "sub",
	/*                  sll */ "sll",
	/*                  slt */ "slt",
	/*                 sltu */ "sltu",
	/*                  xor */ "xor",
	/*                  srl */ "srl",
	/*                  sra */ "sra",
	/*                   or */ "or",
	/*                  and */ "and",
	/*                fence */ "fence",
	/*              fence.i */ "fence.i",
	/*                  lwu */ "lwu",
	/*                   ld */ "ld",
	/*                   sd */ "sd",
	/*           slli.rv64i */ "slli",
	/*           srli.rv64i */ "srli",
	/*           srai.rv64i */ "srai",
	/*                addiw */ "addiw",
	/*                slliw */ "slliw",
	/*                srliw */ "srliw",
	/*                sraiw */ "sraiw",
	/*                 addw */ "addw",
	/*                 subw */ "subw",
	/*                 sllw */ "sllw",
	/*                 srlw */ "srlw",
	/*                 sraw */ "sraw",
	/*                  mul */ "mul",
	/*                 mulh */ "mulh",
	/*               mulhsu */ "mulhsu",
	/*                mulhu */ "mulhu",
	/*                  div */ "div",
	/*                 divu */ "divu",
	/*                  rem */ "rem",
	/*                 remu */ "remu",
	/*                 mulw */ "mulw",
	/*                 divw */ "divw",
	/*                divuw */ "divuw",
	/*                 remw */ "remw",
	/*                remuw */ "remuw",
	/*                 lr.w */ "lr.w",
	/*                 sc.w */ "sc.w",
	/*            amoswap.w */ "amoswap.w",
	/*             amoadd.w */ "amoadd.w",
	/*             amoxor.w */ "amoxor.w",
	/*              amoor.w */ "amoor.w",
	/*             amoand.w */ "amoand.w",
	/*             amomin.w */ "amomin.w",
	/*             amomax.w */ "amomax.w",
	/*            amominu.w */ "amominu.w",
	/*            amomaxu.w */ "amomaxu.w",
	/*                 lr.d */ "lr.d",
	/*                 sc.d */ "sc.d",
	/*            amoswap.d */ "amoswap.d",
	/*             amoadd.d */ "amoadd.d",
	/*             amoxor.d */ "amoxor.d",
	/*              amoor.d */ "amoor.d",
	/*             amoand.d */ "amoand.d",
	/*             amomin.d */ "amomin.d",
	/*             amomax.d */ "amomax.d",
	/*            amominu.d */ "amominu.d",
	/*            amomaxu.d */ "amomaxu.d",
	/*                scall */ "scall",
	/*               sbreak */ "sbreak",
	/*                 sret */ "sret",
	/*            sfence.vm */ "sfence.vm",
	/*                  wfi */ "wfi",
	/*                 mrth */ "mrth",
	/*                 mrts */ "mrts",
	/*                 hrts */ "hrts",
	/*              rdcycle */ "rdcycle",
	/*               rdtime */ "rdtime",
	/*            rdinstret */ "rdinstret",
	/*             rdcycleh */ "rdcycleh",
	/*              rdtimeh */ "rdtimeh",
	/*           rdinstreth */ "rdinstreth",
	/*                csrrw */ "csrrw",
	/*                csrrs */ "csrrs",
	/*                csrrc */ "csrrc",
	/*               csrrwi */ "csrrwi",
	/*               csrrsi */ "csrrsi",
	/*               csrrci */ "csrrci",
	/*                  flw */ "flw",
	/*                  fsw */ "fsw",
	/*              fmadd.s */ "fmadd.s",
	/*              fmsub.s */ "fmsub.s",
	/*             fnmsub.s */ "fnmsub.s",
	/*             fnmadd.s */ "fnmadd.s",
	/*               fadd.s */ "fadd.s",
	/*               fsub.s */ "fsub.s",
	/*               fmul.s */ "fmul.s",
	/*               fdiv.s */ "fdiv.s",
	/*              fsgnj.s */ "fsgnj.s",
	/*             fsgnjn.s */ "fsgnjn.s",
	/*             fsgnjx.s */ "fsgnjx.s",
	/*               fmin.s */ "fmin.s",
	/*               fmax.s */ "fmax.s",
	/*              fsqrt.s */ "fsqrt.s",
	/*                fle.s */ "fle.s",
	/*                flt.s */ "flt.s",
	/*                feq.s */ "feq.s",
	/*             fcvt.w.s */ "fcvt.w.s",
	/*            fcvt.wu.s */ "fcvt.wu.s",
	/*             fcvt.s.w */ "fcvt.s.w",
	/*            fcvt.s.wu */ "fcvt.s.wu",
	/*              fmv.x.s */ "fmv.x.s",
	/*             fclass.s */ "fclass.s",
	/*              fmv.s.x */ "fmv.s.x",
	/*             fcvt.l.s */ "fcvt.l.s",
	/*            fcvt.lu.s */ "fcvt.lu.s",
	/*             fcvt.s.l */ "fcvt.s.l",
	/*            fcvt.s.lu */ "fcvt.s.lu",
	/*                  fld */ "fld",
	/*                  fsd */ "fsd",
	/*              fmadd.d */ "fmadd.d",
	/*              fmsub.d */ "fmsub.d",
	/*             fnmsub.d */ "fnmsub.d",
	/*             fnmadd.d */ "fnmadd.d",
	/*               fadd.d */ "fadd.d",
	/*               fsub.d */ "fsub.d",
	/*               fmul.d */ "fmul.d",
	/*               fdiv.d */ "fdiv.d",
	/*              fsgnj.d */ "fsgnj.d",
	/*             fsgnjn.d */ "fsgnjn.d",
	/*             fsgnjx.d */ "fsgnjx.d",
	/*               fmin.d */ "fmin.d",
	/*               fmax.d */ "fmax.d",
	/*             fcvt.s.d */ "fcvt.s.d",
	/*             fcvt.d.s */ "fcvt.d.s",
	/*              fsqrt.d */ "fsqrt.d",
	/*                fle.d */ "fle.d",
	/*                flt.d */ "flt.d",
	/*                feq.d */ "feq.d",
	/*             fcvt.w.d */ "fcvt.w.d",
	/*            fcvt.wu.d */ "fcvt.wu.d",
	/*             fcvt.d.w */ "fcvt.d.w",
	/*            fcvt.d.wu */ "fcvt.d.wu",
	/*              fmv.x.d */ "fmv.x.d",
	/*             fclass.d */ "fclass.d",
	/*              fmv.d.x */ "fmv.d.x",
	/*             fcvt.l.d */ "fcvt.l.d",
	/*            fcvt.lu.d */ "fcvt.lu.d",
	/*             fcvt.d.l */ "fcvt.d.l",
	/*            fcvt.d.lu */ "fcvt.d.lu",
	/*                frcsr */ "frcsr",
	/*                 frrm */ "frrm",
	/*              frflags */ "frflags",
	/*                fscsr */ "fscsr",
	/*                 fsrm */ "fsrm",
	/*              fsflags */ "fsflags",
	/*                fsrmi */ "fsrmi",
	/*             fsflagsi */ "fsflagsi",
	/*           c.addi4spn */ "c.addi4spn",
	/*                c.fld */ "c.fld",
	/*                 c.lw */ "c.lw",
	/*                c.flw */ "c.flw",
	/*                c.fsd */ "c.fsd",
	/*                 c.sw */ "c.sw",
	/*                c.fsw */ "c.fsw",
	/*                c.nop */ "c.nop",
	/*               c.addi */ "c.addi",
	/*                c.jal */ "c.jal",
	/*                 c.li */ "c.li",
	/*                c.lui */ "c.lui",
	/*           c.addi16sp */ "c.addi16sp",
	/*               c.srli */ "c.srli",
	/*               c.srai */ "c.srai",
	/*               c.andi */ "c.andi",
	/*                c.sub */ "c.sub",
	/*                c.xor */ "c.xor",
	/*                 c.or */ "c.or",
	/*                c.and */ "c.and",
	/*               c.subw */ "c.subw",
	/*               c.addw */ "c.addw",
	/*                  c.j */ "c.j",
	/*               c.beqz */ "c.beqz",
	/*               c.bnez */ "c.bnez",
	/*               c.slli */ "c.slli",
	/*              c.fldsp */ "c.fldsp",
	/*               c.lwsp */ "c.lwsp",
	/*              c.flwsp */ "c.flwsp",
	/*                 c.jr */ "c.jr",
	/*                 c.mv */ "c.mv",
	/*             c.ebreak */ "c.ebreak",
	/*               c.jalr */ "c.jalr",
	/*                c.add */ "c.add",
	/*              c.fsdsp */ "c.fsdsp",
	/*               c.swsp */ "c.swsp",
	/*              c.fswsp */ "c.fswsp",
	/*                 c.ld */ "c.ld",
	/*                 c.sd */ "c.sd",
	/*              c.addiw */ "c.addiw",
	/*               c.ldsp */ "c.ldsp",
	/*               c.sdsp */ "c.sdsp",
};

const riscv_inst_type riscv_instruction_type[] = {
	/*              unknown */ riscv_inst_type_unknown,
	/*                  lui */ riscv_inst_type_u,
	/*                auipc */ riscv_inst_type_u,
	/*                  jal */ riscv_inst_type_uj,
	/*                 jalr */ riscv_inst_type_i,
	/*                  beq */ riscv_inst_type_sb,
	/*                  bne */ riscv_inst_type_sb,
	/*                  blt */ riscv_inst_type_sb,
	/*                  bge */ riscv_inst_type_sb,
	/*                 bltu */ riscv_inst_type_sb,
	/*                 bgeu */ riscv_inst_type_sb,
	/*                   lb */ riscv_inst_type_i,
	/*                   lh */ riscv_inst_type_i,
	/*                   lw */ riscv_inst_type_i,
	/*                  lbu */ riscv_inst_type_i,
	/*                  lhu */ riscv_inst_type_i,
	/*                   sb */ riscv_inst_type_s,
	/*                   sh */ riscv_inst_type_s,
	/*                   sw */ riscv_inst_type_s,
	/*                 addi */ riscv_inst_type_i,
	/*                 slti */ riscv_inst_type_i,
	/*                sltiu */ riscv_inst_type_i,
	/*                 xori */ riscv_inst_type_i,
	/*                  ori */ riscv_inst_type_i,
	/*                 andi */ riscv_inst_type_i,
	/*           slli.rv32i */ riscv_inst_type_i_sh5,
	/*           srli.rv32i */ riscv_inst_type_i_sh5,
	/*           srai.rv32i */ riscv_inst_type_i_sh5,
	/*                  add */ riscv_inst_type_r,
	/*                  sub */ riscv_inst_type_r,
	/*                  sll */ riscv_inst_type_r,
	/*                  slt */ riscv_inst_type_r,
	/*                 sltu */ riscv_inst_type_r,
	/*                  xor */ riscv_inst_type_r,
	/*                  srl */ riscv_inst_type_r,
	/*                  sra */ riscv_inst_type_r,
	/*                   or */ riscv_inst_type_r,
	/*                  and */ riscv_inst_type_r,
	/*                fence */ riscv_inst_type_none,
	/*              fence.i */ riscv_inst_type_none,
	/*                  lwu */ riscv_inst_type_i,
	/*                   ld */ riscv_inst_type_i,
	/*                   sd */ riscv_inst_type_s,
	/*           slli.rv64i */ riscv_inst_type_i_sh6,
	/*           srli.rv64i */ riscv_inst_type_i_sh6,
	/*           srai.rv64i */ riscv_inst_type_i_sh6,
	/*                addiw */ riscv_inst_type_i,
	/*                slliw */ riscv_inst_type_i_sh5,
	/*                srliw */ riscv_inst_type_i_sh5,
	/*                sraiw */ riscv_inst_type_i_sh5,
	/*                 addw */ riscv_inst_type_r,
	/*                 subw */ riscv_inst_type_r,
	/*                 sllw */ riscv_inst_type_r,
	/*                 srlw */ riscv_inst_type_r,
	/*                 sraw */ riscv_inst_type_r,
	/*                  mul */ riscv_inst_type_r,
	/*                 mulh */ riscv_inst_type_r,
	/*               mulhsu */ riscv_inst_type_r,
	/*                mulhu */ riscv_inst_type_r,
	/*                  div */ riscv_inst_type_r,
	/*                 divu */ riscv_inst_type_r,
	/*                  rem */ riscv_inst_type_r,
	/*                 remu */ riscv_inst_type_r,
	/*                 mulw */ riscv_inst_type_r,
	/*                 divw */ riscv_inst_type_r,
	/*                divuw */ riscv_inst_type_r,
	/*                 remw */ riscv_inst_type_r,
	/*                remuw */ riscv_inst_type_r,
	/*                 lr.w */ riscv_inst_type_r,
	/*                 sc.w */ riscv_inst_type_r,
	/*            amoswap.w */ riscv_inst_type_r,
	/*             amoadd.w */ riscv_inst_type_r,
	/*             amoxor.w */ riscv_inst_type_r,
	/*              amoor.w */ riscv_inst_type_r,
	/*             amoand.w */ riscv_inst_type_r,
	/*             amomin.w */ riscv_inst_type_r,
	/*             amomax.w */ riscv_inst_type_r,
	/*            amominu.w */ riscv_inst_type_r,
	/*            amomaxu.w */ riscv_inst_type_r,
	/*                 lr.d */ riscv_inst_type_r,
	/*                 sc.d */ riscv_inst_type_r,
	/*            amoswap.d */ riscv_inst_type_r,
	/*             amoadd.d */ riscv_inst_type_r,
	/*             amoxor.d */ riscv_inst_type_r,
	/*              amoor.d */ riscv_inst_type_r,
	/*             amoand.d */ riscv_inst_type_r,
	/*             amomin.d */ riscv_inst_type_r,
	/*             amomax.d */ riscv_inst_type_r,
	/*            amominu.d */ riscv_inst_type_r,
	/*            amomaxu.d */ riscv_inst_type_r,
	/*                scall */ riscv_inst_type_none,
	/*               sbreak */ riscv_inst_type_none,
	/*                 sret */ riscv_inst_type_none,
	/*            sfence.vm */ riscv_inst_type_none,
	/*                  wfi */ riscv_inst_type_none,
	/*                 mrth */ riscv_inst_type_none,
	/*                 mrts */ riscv_inst_type_none,
	/*                 hrts */ riscv_inst_type_none,
	/*              rdcycle */ riscv_inst_type_i,
	/*               rdtime */ riscv_inst_type_i,
	/*            rdinstret */ riscv_inst_type_i,
	/*             rdcycleh */ riscv_inst_type_i,
	/*              rdtimeh */ riscv_inst_type_i,
	/*           rdinstreth */ riscv_inst_type_i,
	/*                csrrw */ riscv_inst_type_i,
	/*                csrrs */ riscv_inst_type_i,
	/*                csrrc */ riscv_inst_type_i,
	/*               csrrwi */ riscv_inst_type_i,
	/*               csrrsi */ riscv_inst_type_i,
	/*               csrrci */ riscv_inst_type_i,
	/*                  flw */ riscv_inst_type_i,
	/*                  fsw */ riscv_inst_type_s,
	/*              fmadd.s */ riscv_inst_type_r_4f,
	/*              fmsub.s */ riscv_inst_type_r_4f,
	/*             fnmsub.s */ riscv_inst_type_r_4f,
	/*             fnmadd.s */ riscv_inst_type_r_4f,
	/*               fadd.s */ riscv_inst_type_r,
	/*               fsub.s */ riscv_inst_type_r,
	/*               fmul.s */ riscv_inst_type_r,
	/*               fdiv.s */ riscv_inst_type_r,
	/*              fsgnj.s */ riscv_inst_type_r,
	/*             fsgnjn.s */ riscv_inst_type_r,
	/*             fsgnjx.s */ riscv_inst_type_r,
	/*               fmin.s */ riscv_inst_type_r,
	/*               fmax.s */ riscv_inst_type_r,
	/*              fsqrt.s */ riscv_inst_type_r,
	/*                fle.s */ riscv_inst_type_r,
	/*                flt.s */ riscv_inst_type_r,
	/*                feq.s */ riscv_inst_type_r,
	/*             fcvt.w.s */ riscv_inst_type_r,
	/*            fcvt.wu.s */ riscv_inst_type_r,
	/*             fcvt.s.w */ riscv_inst_type_r,
	/*            fcvt.s.wu */ riscv_inst_type_r,
	/*              fmv.x.s */ riscv_inst_type_r,
	/*             fclass.s */ riscv_inst_type_r,
	/*              fmv.s.x */ riscv_inst_type_r,
	/*             fcvt.l.s */ riscv_inst_type_r,
	/*            fcvt.lu.s */ riscv_inst_type_r,
	/*             fcvt.s.l */ riscv_inst_type_r,
	/*            fcvt.s.lu */ riscv_inst_type_r,
	/*                  fld */ riscv_inst_type_i,
	/*                  fsd */ riscv_inst_type_s,
	/*              fmadd.d */ riscv_inst_type_r_4f,
	/*              fmsub.d */ riscv_inst_type_r_4f,
	/*             fnmsub.d */ riscv_inst_type_r_4f,
	/*             fnmadd.d */ riscv_inst_type_r_4f,
	/*               fadd.d */ riscv_inst_type_r,
	/*               fsub.d */ riscv_inst_type_r,
	/*               fmul.d */ riscv_inst_type_r,
	/*               fdiv.d */ riscv_inst_type_r,
	/*              fsgnj.d */ riscv_inst_type_r,
	/*             fsgnjn.d */ riscv_inst_type_r,
	/*             fsgnjx.d */ riscv_inst_type_r,
	/*               fmin.d */ riscv_inst_type_r,
	/*               fmax.d */ riscv_inst_type_r,
	/*             fcvt.s.d */ riscv_inst_type_r,
	/*             fcvt.d.s */ riscv_inst_type_r,
	/*              fsqrt.d */ riscv_inst_type_r,
	/*                fle.d */ riscv_inst_type_r,
	/*                flt.d */ riscv_inst_type_r,
	/*                feq.d */ riscv_inst_type_r,
	/*             fcvt.w.d */ riscv_inst_type_r,
	/*            fcvt.wu.d */ riscv_inst_type_r,
	/*             fcvt.d.w */ riscv_inst_type_r,
	/*            fcvt.d.wu */ riscv_inst_type_r,
	/*              fmv.x.d */ riscv_inst_type_r,
	/*             fclass.d */ riscv_inst_type_r,
	/*              fmv.d.x */ riscv_inst_type_r,
	/*             fcvt.l.d */ riscv_inst_type_r,
	/*            fcvt.lu.d */ riscv_inst_type_r,
	/*             fcvt.d.l */ riscv_inst_type_r,
	/*            fcvt.d.lu */ riscv_inst_type_r,
	/*                frcsr */ riscv_inst_type_i,
	/*                 frrm */ riscv_inst_type_i,
	/*              frflags */ riscv_inst_type_i,
	/*                fscsr */ riscv_inst_type_i,
	/*                 fsrm */ riscv_inst_type_i,
	/*              fsflags */ riscv_inst_type_i,
	/*                fsrmi */ riscv_inst_type_i,
	/*             fsflagsi */ riscv_inst_type_i,
	/*           c.addi4spn */ riscv_inst_type_ciw_4spn,
	/*                c.fld */ riscv_inst_type_cl_ld,
	/*                 c.lw */ riscv_inst_type_cl_lw,
	/*                c.flw */ riscv_inst_type_cl_lw,
	/*                c.fsd */ riscv_inst_type_cs_sd,
	/*                 c.sw */ riscv_inst_type_cs_sw,
	/*                c.fsw */ riscv_inst_type_cs_sw,
	/*                c.nop */ riscv_inst_type_c_nop,
	/*               c.addi */ riscv_inst_type_ci,
	/*                c.jal */ riscv_inst_type_cj,
	/*                 c.li */ riscv_inst_type_ci_li,
	/*                c.lui */ riscv_inst_type_ci_lui,
	/*           c.addi16sp */ riscv_inst_type_ci_16sp,
	/*               c.srli */ riscv_inst_type_cb_sh5,
	/*               c.srai */ riscv_inst_type_cb_sh5,
	/*               c.andi */ riscv_inst_type_cb,
	/*                c.sub */ riscv_inst_type_cs,
	/*                c.xor */ riscv_inst_type_cs,
	/*                 c.or */ riscv_inst_type_cs,
	/*                c.and */ riscv_inst_type_cs,
	/*               c.subw */ riscv_inst_type_cs,
	/*               c.addw */ riscv_inst_type_cs,
	/*                  c.j */ riscv_inst_type_cj,
	/*               c.beqz */ riscv_inst_type_cb,
	/*               c.bnez */ riscv_inst_type_cb,
	/*               c.slli */ riscv_inst_type_ci_sh5,
	/*              c.fldsp */ riscv_inst_type_ci_ldsp,
	/*               c.lwsp */ riscv_inst_type_ci_lwsp,
	/*              c.flwsp */ riscv_inst_type_ci_lwsp,
	/*                 c.jr */ riscv_inst_type_cr_jr,
	/*                 c.mv */ riscv_inst_type_cr_mv,
	/*             c.ebreak */ riscv_inst_type_none,
	/*               c.jalr */ riscv_inst_type_cr_jalr,
	/*                c.add */ riscv_inst_type_cr,
	/*              c.fsdsp */ riscv_inst_type_css_sdsp,
	/*               c.swsp */ riscv_inst_type_css_swsp,
	/*              c.fswsp */ riscv_inst_type_css_swsp,
	/*                 c.ld */ riscv_inst_type_cl_ld,
	/*                 c.sd */ riscv_inst_type_cs_sd,
	/*              c.addiw */ riscv_inst_type_ci,
	/*               c.ldsp */ riscv_inst_type_ci_ldsp,
	/*               c.sdsp */ riscv_inst_type_css_sdsp,
};

const riscv_wu riscv_instruction_match[] = {
	/*              unknown */ 0x00000000,
	/*                  lui */ 0x00000037,
	/*                auipc */ 0x00000017,
	/*                  jal */ 0x0000006f,
	/*                 jalr */ 0x00000067,
	/*                  beq */ 0x00000063,
	/*                  bne */ 0x00001063,
	/*                  blt */ 0x00004063,
	/*                  bge */ 0x00005063,
	/*                 bltu */ 0x00006063,
	/*                 bgeu */ 0x00007063,
	/*                   lb */ 0x00000003,
	/*                   lh */ 0x00001003,
	/*                   lw */ 0x00002003,
	/*                  lbu */ 0x00004003,
	/*                  lhu */ 0x00005003,
	/*                   sb */ 0x00000023,
	/*                   sh */ 0x00001023,
	/*                   sw */ 0x00002023,
	/*                 addi */ 0x00000013,
	/*                 slti */ 0x00002013,
	/*                sltiu */ 0x00003013,
	/*                 xori */ 0x00004013,
	/*                  ori */ 0x00006013,
	/*                 andi */ 0x00007013,
	/*           slli.rv32i */ 0x00001013,
	/*           srli.rv32i */ 0x00005013,
	/*           srai.rv32i */ 0x40005013,
	/*                  add */ 0x00000033,
	/*                  sub */ 0x40000033,
	/*                  sll */ 0x00001033,
	/*                  slt */ 0x00002033,
	/*                 sltu */ 0x00003033,
	/*                  xor */ 0x00004033,
	/*                  srl */ 0x00005033,
	/*                  sra */ 0x40005033,
	/*                   or */ 0x00006033,
	/*                  and */ 0x00007033,
	/*                fence */ 0x0000000f,
	/*              fence.i */ 0x0000100f,
	/*                  lwu */ 0x00006003,
	/*                   ld */ 0x00003003,
	/*                   sd */ 0x00003023,
	/*           slli.rv64i */ 0x00001013,
	/*           srli.rv64i */ 0x00005013,
	/*           srai.rv64i */ 0x40005013,
	/*                addiw */ 0x0000001b,
	/*                slliw */ 0x0000101b,
	/*                srliw */ 0x0000501b,
	/*                sraiw */ 0x4000501b,
	/*                 addw */ 0x0000003b,
	/*                 subw */ 0x4000003b,
	/*                 sllw */ 0x0000103b,
	/*                 srlw */ 0x0000503b,
	/*                 sraw */ 0x4000503b,
	/*                  mul */ 0x02000033,
	/*                 mulh */ 0x02001033,
	/*               mulhsu */ 0x02002033,
	/*                mulhu */ 0x02003033,
	/*                  div */ 0x02004033,
	/*                 divu */ 0x02005033,
	/*                  rem */ 0x02006033,
	/*                 remu */ 0x02007033,
	/*                 mulw */ 0x0200003b,
	/*                 divw */ 0x0200403b,
	/*                divuw */ 0x0200503b,
	/*                 remw */ 0x0200603b,
	/*                remuw */ 0x0200703b,
	/*                 lr.w */ 0x1000202f,
	/*                 sc.w */ 0x1800202f,
	/*            amoswap.w */ 0x0800202f,
	/*             amoadd.w */ 0x0000202f,
	/*             amoxor.w */ 0x2000202f,
	/*              amoor.w */ 0x4000202f,
	/*             amoand.w */ 0x6000202f,
	/*             amomin.w */ 0x8000202f,
	/*             amomax.w */ 0xa000202f,
	/*            amominu.w */ 0xc000202f,
	/*            amomaxu.w */ 0xe000202f,
	/*                 lr.d */ 0x1000302f,
	/*                 sc.d */ 0x1800302f,
	/*            amoswap.d */ 0x0800302f,
	/*             amoadd.d */ 0x0000302f,
	/*             amoxor.d */ 0x2000302f,
	/*              amoor.d */ 0x4000302f,
	/*             amoand.d */ 0x6000302f,
	/*             amomin.d */ 0x8000302f,
	/*             amomax.d */ 0xa000302f,
	/*            amominu.d */ 0xc000302f,
	/*            amomaxu.d */ 0xe000302f,
	/*                scall */ 0x00000073,
	/*               sbreak */ 0x00100073,
	/*                 sret */ 0x10000073,
	/*            sfence.vm */ 0x10100073,
	/*                  wfi */ 0x10200073,
	/*                 mrth */ 0x30600073,
	/*                 mrts */ 0x30500073,
	/*                 hrts */ 0x20500073,
	/*              rdcycle */ 0xc0002073,
	/*               rdtime */ 0xc0102073,
	/*            rdinstret */ 0xc0202073,
	/*             rdcycleh */ 0xc8002073,
	/*              rdtimeh */ 0xc8102073,
	/*           rdinstreth */ 0xc8202073,
	/*                csrrw */ 0x00001073,
	/*                csrrs */ 0x00002073,
	/*                csrrc */ 0x00003073,
	/*               csrrwi */ 0x00005073,
	/*               csrrsi */ 0x00006073,
	/*               csrrci */ 0x00007073,
	/*                  flw */ 0x00002007,
	/*                  fsw */ 0x00002027,
	/*              fmadd.s */ 0x00000043,
	/*              fmsub.s */ 0x00000047,
	/*             fnmsub.s */ 0x0000004b,
	/*             fnmadd.s */ 0x0000004f,
	/*               fadd.s */ 0x00000053,
	/*               fsub.s */ 0x08000053,
	/*               fmul.s */ 0x10000053,
	/*               fdiv.s */ 0x18000053,
	/*              fsgnj.s */ 0x20000053,
	/*             fsgnjn.s */ 0x20001053,
	/*             fsgnjx.s */ 0x20002053,
	/*               fmin.s */ 0x28000053,
	/*               fmax.s */ 0x28001053,
	/*              fsqrt.s */ 0x58000053,
	/*                fle.s */ 0xa0000053,
	/*                flt.s */ 0xa0001053,
	/*                feq.s */ 0xa0002053,
	/*             fcvt.w.s */ 0xc0000053,
	/*            fcvt.wu.s */ 0xc0100053,
	/*             fcvt.s.w */ 0xd0000053,
	/*            fcvt.s.wu */ 0xd0100053,
	/*              fmv.x.s */ 0xe0000053,
	/*             fclass.s */ 0xe0001053,
	/*              fmv.s.x */ 0xf0000053,
	/*             fcvt.l.s */ 0xc0200053,
	/*            fcvt.lu.s */ 0xc0300053,
	/*             fcvt.s.l */ 0xd0200053,
	/*            fcvt.s.lu */ 0xd0300053,
	/*                  fld */ 0x00003007,
	/*                  fsd */ 0x00003027,
	/*              fmadd.d */ 0x02000043,
	/*              fmsub.d */ 0x02000047,
	/*             fnmsub.d */ 0x0200004b,
	/*             fnmadd.d */ 0x0200004f,
	/*               fadd.d */ 0x02000053,
	/*               fsub.d */ 0x0a000053,
	/*               fmul.d */ 0x12000053,
	/*               fdiv.d */ 0x1a000053,
	/*              fsgnj.d */ 0x22000053,
	/*             fsgnjn.d */ 0x22001053,
	/*             fsgnjx.d */ 0x22002053,
	/*               fmin.d */ 0x2a000053,
	/*               fmax.d */ 0x2a001053,
	/*             fcvt.s.d */ 0x40100053,
	/*             fcvt.d.s */ 0x42000053,
	/*              fsqrt.d */ 0x5a000053,
	/*                fle.d */ 0xa2000053,
	/*                flt.d */ 0xa2001053,
	/*                feq.d */ 0xa2002053,
	/*             fcvt.w.d */ 0xc2000053,
	/*            fcvt.wu.d */ 0xc2100053,
	/*             fcvt.d.w */ 0xd2000053,
	/*            fcvt.d.wu */ 0xd2100053,
	/*              fmv.x.d */ 0xe2000053,
	/*             fclass.d */ 0xe2001053,
	/*              fmv.d.x */ 0xf2000053,
	/*             fcvt.l.d */ 0xc2200053,
	/*            fcvt.lu.d */ 0xc2300053,
	/*             fcvt.d.l */ 0xd2200053,
	/*            fcvt.d.lu */ 0xd2300053,
	/*                frcsr */ 0x00302073,
	/*                 frrm */ 0x00202073,
	/*              frflags */ 0x00102073,
	/*                fscsr */ 0x00301073,
	/*                 fsrm */ 0x00201073,
	/*              fsflags */ 0x00101073,
	/*                fsrmi */ 0x00205073,
	/*             fsflagsi */ 0x00105073,
	/*           c.addi4spn */ 0x00000000,
	/*                c.fld */ 0x00002000,
	/*                 c.lw */ 0x00004000,
	/*                c.flw */ 0x00006000,
	/*                c.fsd */ 0x0000a000,
	/*                 c.sw */ 0x0000c000,
	/*                c.fsw */ 0x0000e000,
	/*                c.nop */ 0x00000001,
	/*               c.addi */ 0x00000001,
	/*                c.jal */ 0x00002001,
	/*                 c.li */ 0x00004001,
	/*                c.lui */ 0x00006001,
	/*           c.addi16sp */ 0x00006101,
	/*               c.srli */ 0x00008001,
	/*               c.srai */ 0x00008401,
	/*               c.andi */ 0x00008801,
	/*                c.sub */ 0x00008c01,
	/*                c.xor */ 0x00008c21,
	/*                 c.or */ 0x00008c41,
	/*                c.and */ 0x00008c61,
	/*               c.subw */ 0x00009c01,
	/*               c.addw */ 0x00009c21,
	/*                  c.j */ 0x0000a001,
	/*               c.beqz */ 0x0000c001,
	/*               c.bnez */ 0x0000e001,
	/*               c.slli */ 0x00000002,
	/*              c.fldsp */ 0x00002002,
	/*               c.lwsp */ 0x00004002,
	/*              c.flwsp */ 0x00006002,
	/*                 c.jr */ 0x00008002,
	/*                 c.mv */ 0x00008002,
	/*             c.ebreak */ 0x00009002,
	/*               c.jalr */ 0x00009002,
	/*                c.add */ 0x00009002,
	/*              c.fsdsp */ 0x0000a002,
	/*               c.swsp */ 0x0000c002,
	/*              c.fswsp */ 0x0000e002,
	/*                 c.ld */ 0x00006000,
	/*                 c.sd */ 0x0000e000,
	/*              c.addiw */ 0x00002001,
	/*               c.ldsp */ 0x00006002,
	/*               c.sdsp */ 0x0000e002,
};

const riscv_wu riscv_instruction_mask[] = {
	/*              unknown */ 0x00000000,
	/*                  lui */ 0x0000007f,
	/*                auipc */ 0x0000007f,
	/*                  jal */ 0x0000007f,
	/*                 jalr */ 0x0000707f,
	/*                  beq */ 0x0000707f,
	/*                  bne */ 0x0000707f,
	/*                  blt */ 0x0000707f,
	/*                  bge */ 0x0000707f,
	/*                 bltu */ 0x0000707f,
	/*                 bgeu */ 0x0000707f,
	/*                   lb */ 0x0000707f,
	/*                   lh */ 0x0000707f,
	/*                   lw */ 0x0000707f,
	/*                  lbu */ 0x0000707f,
	/*                  lhu */ 0x0000707f,
	/*                   sb */ 0x0000707f,
	/*                   sh */ 0x0000707f,
	/*                   sw */ 0x0000707f,
	/*                 addi */ 0x0000707f,
	/*                 slti */ 0x0000707f,
	/*                sltiu */ 0x0000707f,
	/*                 xori */ 0x0000707f,
	/*                  ori */ 0x0000707f,
	/*                 andi */ 0x0000707f,
	/*           slli.rv32i */ 0xfc00707f,
	/*           srli.rv32i */ 0xfc00707f,
	/*           srai.rv32i */ 0xfc00707f,
	/*                  add */ 0xfe00707f,
	/*                  sub */ 0xfe00707f,
	/*                  sll */ 0xfe00707f,
	/*                  slt */ 0xfe00707f,
	/*                 sltu */ 0xfe00707f,
	/*                  xor */ 0xfe00707f,
	/*                  srl */ 0xfe00707f,
	/*                  sra */ 0xfe00707f,
	/*                   or */ 0xfe00707f,
	/*                  and */ 0xfe00707f,
	/*                fence */ 0x0000707f,
	/*              fence.i */ 0x0000707f,
	/*                  lwu */ 0x0000707f,
	/*                   ld */ 0x0000707f,
	/*                   sd */ 0x0000707f,
	/*           slli.rv64i */ 0xfc00707f,
	/*           srli.rv64i */ 0xfc00707f,
	/*           srai.rv64i */ 0xfc00707f,
	/*                addiw */ 0x0000707f,
	/*                slliw */ 0xfe00707f,
	/*                srliw */ 0xfe00707f,
	/*                sraiw */ 0xfe00707f,
	/*                 addw */ 0xfe00707f,
	/*                 subw */ 0xfe00707f,
	/*                 sllw */ 0xfe00707f,
	/*                 srlw */ 0xfe00707f,
	/*                 sraw */ 0xfe00707f,
	/*                  mul */ 0xfe00707f,
	/*                 mulh */ 0xfe00707f,
	/*               mulhsu */ 0xfe00707f,
	/*                mulhu */ 0xfe00707f,
	/*                  div */ 0xfe00707f,
	/*                 divu */ 0xfe00707f,
	/*                  rem */ 0xfe00707f,
	/*                 remu */ 0xfe00707f,
	/*                 mulw */ 0xfe00707f,
	/*                 divw */ 0xfe00707f,
	/*                divuw */ 0xfe00707f,
	/*                 remw */ 0xfe00707f,
	/*                remuw */ 0xfe00707f,
	/*                 lr.w */ 0xf9f0707f,
	/*                 sc.w */ 0xf800707f,
	/*            amoswap.w */ 0xf800707f,
	/*             amoadd.w */ 0xf800707f,
	/*             amoxor.w */ 0xf800707f,
	/*              amoor.w */ 0xf800707f,
	/*             amoand.w */ 0xf800707f,
	/*             amomin.w */ 0xf800707f,
	/*             amomax.w */ 0xf800707f,
	/*            amominu.w */ 0xf800707f,
	/*            amomaxu.w */ 0xf800707f,
	/*                 lr.d */ 0xf9f0707f,
	/*                 sc.d */ 0xf800707f,
	/*            amoswap.d */ 0xf800707f,
	/*             amoadd.d */ 0xf800707f,
	/*             amoxor.d */ 0xf800707f,
	/*              amoor.d */ 0xf800707f,
	/*             amoand.d */ 0xf800707f,
	/*             amomin.d */ 0xf800707f,
	/*             amomax.d */ 0xf800707f,
	/*            amominu.d */ 0xf800707f,
	/*            amomaxu.d */ 0xf800707f,
	/*                scall */ 0xffffffff,
	/*               sbreak */ 0xffffffff,
	/*                 sret */ 0xffffffff,
	/*            sfence.vm */ 0xfff07fff,
	/*                  wfi */ 0xffffffff,
	/*                 mrth */ 0xffffffff,
	/*                 mrts */ 0xffffffff,
	/*                 hrts */ 0xffffffff,
	/*              rdcycle */ 0xfffff07f,
	/*               rdtime */ 0xfffff07f,
	/*            rdinstret */ 0xfffff07f,
	/*             rdcycleh */ 0xfffff07f,
	/*              rdtimeh */ 0xfffff07f,
	/*           rdinstreth */ 0xfffff07f,
	/*                csrrw */ 0x0000707f,
	/*                csrrs */ 0x0000707f,
	/*                csrrc */ 0x0000707f,
	/*               csrrwi */ 0x0000707f,
	/*               csrrsi */ 0x0000707f,
	/*               csrrci */ 0x0000707f,
	/*                  flw */ 0x0000707f,
	/*                  fsw */ 0x0000707f,
	/*              fmadd.s */ 0x0600007f,
	/*              fmsub.s */ 0x0600007f,
	/*             fnmsub.s */ 0x0600007f,
	/*             fnmadd.s */ 0x0600007f,
	/*               fadd.s */ 0xfe00007f,
	/*               fsub.s */ 0xfe00007f,
	/*               fmul.s */ 0xfe00007f,
	/*               fdiv.s */ 0xfe00007f,
	/*              fsgnj.s */ 0xfe00707f,
	/*             fsgnjn.s */ 0xfe00707f,
	/*             fsgnjx.s */ 0xfe00707f,
	/*               fmin.s */ 0xfe00707f,
	/*               fmax.s */ 0xfe00707f,
	/*              fsqrt.s */ 0xfff0007f,
	/*                fle.s */ 0xfe00707f,
	/*                flt.s */ 0xfe00707f,
	/*                feq.s */ 0xfe00707f,
	/*             fcvt.w.s */ 0xfff0007f,
	/*            fcvt.wu.s */ 0xfff0007f,
	/*             fcvt.s.w */ 0xfff0007f,
	/*            fcvt.s.wu */ 0xfff0007f,
	/*              fmv.x.s */ 0xfff0707f,
	/*             fclass.s */ 0xfff0707f,
	/*              fmv.s.x */ 0xfff0707f,
	/*             fcvt.l.s */ 0xfff0007f,
	/*            fcvt.lu.s */ 0xfff0007f,
	/*             fcvt.s.l */ 0xfff0007f,
	/*            fcvt.s.lu */ 0xfff0007f,
	/*                  fld */ 0x0000707f,
	/*                  fsd */ 0x0000707f,
	/*              fmadd.d */ 0x0600007f,
	/*              fmsub.d */ 0x0600007f,
	/*             fnmsub.d */ 0x0600007f,
	/*             fnmadd.d */ 0x0600007f,
	/*               fadd.d */ 0xfe00007f,
	/*               fsub.d */ 0xfe00007f,
	/*               fmul.d */ 0xfe00007f,
	/*               fdiv.d */ 0xfe00007f,
	/*              fsgnj.d */ 0xfe00707f,
	/*             fsgnjn.d */ 0xfe00707f,
	/*             fsgnjx.d */ 0xfe00707f,
	/*               fmin.d */ 0xfe00707f,
	/*               fmax.d */ 0xfe00707f,
	/*             fcvt.s.d */ 0xfff0007f,
	/*             fcvt.d.s */ 0xfff0007f,
	/*              fsqrt.d */ 0xfff0007f,
	/*                fle.d */ 0xfe00707f,
	/*                flt.d */ 0xfe00707f,
	/*                feq.d */ 0xfe00707f,
	/*             fcvt.w.d */ 0xfff0007f,
	/*            fcvt.wu.d */ 0xfff0007f,
	/*             fcvt.d.w */ 0xfff0007f,
	/*            fcvt.d.wu */ 0xfff0007f,
	/*              fmv.x.d */ 0xfff0707f,
	/*             fclass.d */ 0xfff0707f,
	/*              fmv.d.x */ 0xfff0707f,
	/*             fcvt.l.d */ 0xfff0007f,
	/*            fcvt.lu.d */ 0xfff0007f,
	/*             fcvt.d.l */ 0xfff0007f,
	/*            fcvt.d.lu */ 0xfff0007f,
	/*                frcsr */ 0xfffff07f,
	/*                 frrm */ 0xfffff07f,
	/*              frflags */ 0xfffff07f,
	/*                fscsr */ 0xfff0707f,
	/*                 fsrm */ 0xfff0707f,
	/*              fsflags */ 0xfff0707f,
	/*                fsrmi */ 0xfff0707f,
	/*             fsflagsi */ 0xfff0707f,
	/*           c.addi4spn */ 0x0000e003,
	/*                c.fld */ 0x0000e003,
	/*                 c.lw */ 0x0000e003,
	/*                c.flw */ 0x0000e003,
	/*                c.fsd */ 0x0000e003,
	/*                 c.sw */ 0x0000e003,
	/*                c.fsw */ 0x0000e003,
	/*                c.nop */ 0x0000ffff,
	/*               c.addi */ 0x0000e003,
	/*                c.jal */ 0x0000e003,
	/*                 c.li */ 0x0000e003,
	/*                c.lui */ 0x0000e003,
	/*           c.addi16sp */ 0x0000ef83,
	/*               c.srli */ 0x0000ec03,
	/*               c.srai */ 0x0000ec03,
	/*               c.andi */ 0x0000ec03,
	/*                c.sub */ 0x0000fc63,
	/*                c.xor */ 0x0000fc63,
	/*                 c.or */ 0x0000fc63,
	/*                c.and */ 0x0000fc63,
	/*               c.subw */ 0x0000fc63,
	/*               c.addw */ 0x0000fc63,
	/*                  c.j */ 0x0000e003,
	/*               c.beqz */ 0x0000e003,
	/*               c.bnez */ 0x0000e003,
	/*               c.slli */ 0x0000e003,
	/*              c.fldsp */ 0x0000e003,
	/*               c.lwsp */ 0x0000e003,
	/*              c.flwsp */ 0x0000e003,
	/*                 c.jr */ 0x0000f07f,
	/*                 c.mv */ 0x0000f003,
	/*             c.ebreak */ 0x0000ffff,
	/*               c.jalr */ 0x0000f07f,
	/*                c.add */ 0x0000f003,
	/*              c.fsdsp */ 0x0000e003,
	/*               c.swsp */ 0x0000e003,
	/*              c.fswsp */ 0x0000e003,
	/*                 c.ld */ 0x0000e003,
	/*                 c.sd */ 0x0000e003,
	/*              c.addiw */ 0x0000e003,
	/*               c.ldsp */ 0x0000e003,
	/*               c.sdsp */ 0x0000e003,
};

const rvf* riscv_instruction_format[] = {
	/*              unknown */ riscv_fmt_none,
	/*                  lui */ riscv_fmt_rd_imm,
	/*                auipc */ riscv_fmt_rd_imm,
	/*                  jal */ riscv_fmt_rd_ipc,
	/*                 jalr */ riscv_fmt_rd_rs1_imm,
	/*                  beq */ riscv_fmt_rs1_rs2_ipc,
	/*                  bne */ riscv_fmt_rs1_rs2_ipc,
	/*                  blt */ riscv_fmt_rs1_rs2_ipc,
	/*                  bge */ riscv_fmt_rs1_rs2_ipc,
	/*                 bltu */ riscv_fmt_rs1_rs2_ipc,
	/*                 bgeu */ riscv_fmt_rs1_rs2_ipc,
	/*                   lb */ riscv_fmt_rd_bimm_rs1,
	/*                   lh */ riscv_fmt_rd_bimm_rs1,
	/*                   lw */ riscv_fmt_rd_bimm_rs1,
	/*                  lbu */ riscv_fmt_rd_bimm_rs1,
	/*                  lhu */ riscv_fmt_rd_bimm_rs1,
	/*                   sb */ riscv_fmt_rs2_bimm_rs1,
	/*                   sh */ riscv_fmt_rs2_bimm_rs1,
	/*                   sw */ riscv_fmt_rs2_bimm_rs1,
	/*                 addi */ riscv_fmt_rd_rs1_imm,
	/*                 slti */ riscv_fmt_rd_rs1_imm,
	/*                sltiu */ riscv_fmt_rd_rs1_imm,
	/*                 xori */ riscv_fmt_rd_rs1_imm,
	/*                  ori */ riscv_fmt_rd_rs1_imm,
	/*                 andi */ riscv_fmt_rd_rs1_imm,
	/*           slli.rv32i */ riscv_fmt_rd_rs1_imm,
	/*           srli.rv32i */ riscv_fmt_rd_rs1_imm,
	/*           srai.rv32i */ riscv_fmt_rd_rs1_imm,
	/*                  add */ riscv_fmt_rd_rs1_rs2,
	/*                  sub */ riscv_fmt_rd_rs1_rs2,
	/*                  sll */ riscv_fmt_rd_rs1_rs2,
	/*                  slt */ riscv_fmt_rd_rs1_rs2,
	/*                 sltu */ riscv_fmt_rd_rs1_rs2,
	/*                  xor */ riscv_fmt_rd_rs1_rs2,
	/*                  srl */ riscv_fmt_rd_rs1_rs2,
	/*                  sra */ riscv_fmt_rd_rs1_rs2,
	/*                   or */ riscv_fmt_rd_rs1_rs2,
	/*                  and */ riscv_fmt_rd_rs1_rs2,
	/*                fence */ riscv_fmt_none,
	/*              fence.i */ riscv_fmt_none,
	/*                  lwu */ riscv_fmt_rd_bimm_rs1,
	/*                   ld */ riscv_fmt_rd_bimm_rs1,
	/*                   sd */ riscv_fmt_rs2_bimm_rs1,
	/*           slli.rv64i */ riscv_fmt_rd_rs1_imm,
	/*           srli.rv64i */ riscv_fmt_rd_rs1_imm,
	/*           srai.rv64i */ riscv_fmt_rd_rs1_imm,
	/*                addiw */ riscv_fmt_rd_rs1_imm,
	/*                slliw */ riscv_fmt_rd_rs1_imm,
	/*                srliw */ riscv_fmt_rd_rs1_imm,
	/*                sraiw */ riscv_fmt_rd_rs1_imm,
	/*                 addw */ riscv_fmt_rd_rs1_rs2,
	/*                 subw */ riscv_fmt_rd_rs1_rs2,
	/*                 sllw */ riscv_fmt_rd_rs1_rs2,
	/*                 srlw */ riscv_fmt_rd_rs1_rs2,
	/*                 sraw */ riscv_fmt_rd_rs1_rs2,
	/*                  mul */ riscv_fmt_rd_rs1_rs2,
	/*                 mulh */ riscv_fmt_rd_rs1_rs2,
	/*               mulhsu */ riscv_fmt_rd_rs1_rs2,
	/*                mulhu */ riscv_fmt_rd_rs1_rs2,
	/*                  div */ riscv_fmt_rd_rs1_rs2,
	/*                 divu */ riscv_fmt_rd_rs1_rs2,
	/*                  rem */ riscv_fmt_rd_rs1_rs2,
	/*                 remu */ riscv_fmt_rd_rs1_rs2,
	/*                 mulw */ riscv_fmt_rd_rs1_rs2,
	/*                 divw */ riscv_fmt_rd_rs1_rs2,
	/*                divuw */ riscv_fmt_rd_rs1_rs2,
	/*                 remw */ riscv_fmt_rd_rs1_rs2,
	/*                remuw */ riscv_fmt_rd_rs1_rs2,
	/*                 lr.w */ riscv_fmt_rd_b_rs1,
	/*                 sc.w */ riscv_fmt_rd_rs2_b_rs1,
	/*            amoswap.w */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoadd.w */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoxor.w */ riscv_fmt_rd_rs2_b_rs1,
	/*              amoor.w */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoand.w */ riscv_fmt_rd_rs2_b_rs1,
	/*             amomin.w */ riscv_fmt_rd_rs2_b_rs1,
	/*             amomax.w */ riscv_fmt_rd_rs2_b_rs1,
	/*            amominu.w */ riscv_fmt_rd_rs2_b_rs1,
	/*            amomaxu.w */ riscv_fmt_rd_rs2_b_rs1,
	/*                 lr.d */ riscv_fmt_rd_b_rs1,
	/*                 sc.d */ riscv_fmt_rd_rs2_b_rs1,
	/*            amoswap.d */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoadd.d */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoxor.d */ riscv_fmt_rd_rs2_b_rs1,
	/*              amoor.d */ riscv_fmt_rd_rs2_b_rs1,
	/*             amoand.d */ riscv_fmt_rd_rs2_b_rs1,
	/*             amomin.d */ riscv_fmt_rd_rs2_b_rs1,
	/*             amomax.d */ riscv_fmt_rd_rs2_b_rs1,
	/*            amominu.d */ riscv_fmt_rd_rs2_b_rs1,
	/*            amomaxu.d */ riscv_fmt_rd_rs2_b_rs1,
	/*                scall */ riscv_fmt_none,
	/*               sbreak */ riscv_fmt_none,
	/*                 sret */ riscv_fmt_none,
	/*            sfence.vm */ riscv_fmt_none,
	/*                  wfi */ riscv_fmt_none,
	/*                 mrth */ riscv_fmt_none,
	/*                 mrts */ riscv_fmt_none,
	/*                 hrts */ riscv_fmt_none,
	/*              rdcycle */ riscv_fmt_rd_csr_rs1,
	/*               rdtime */ riscv_fmt_rd_csr_rs1,
	/*            rdinstret */ riscv_fmt_rd_csr_rs1,
	/*             rdcycleh */ riscv_fmt_rd_csr_rs1,
	/*              rdtimeh */ riscv_fmt_rd_csr_rs1,
	/*           rdinstreth */ riscv_fmt_rd_csr_rs1,
	/*                csrrw */ riscv_fmt_rd_csr_rs1,
	/*                csrrs */ riscv_fmt_rd_csr_rs1,
	/*                csrrc */ riscv_fmt_rd_csr_rs1,
	/*               csrrwi */ riscv_fmt_rd_csr_irs1,
	/*               csrrsi */ riscv_fmt_rd_csr_irs1,
	/*               csrrci */ riscv_fmt_rd_csr_irs1,
	/*                  flw */ riscv_fmt_frd_bimm_rs1,
	/*                  fsw */ riscv_fmt_frs2_bimm_rs1,
	/*              fmadd.s */ riscv_fmt_frd_frs1_frs2_frs3,
	/*              fmsub.s */ riscv_fmt_frd_frs1_frs2_frs3,
	/*             fnmsub.s */ riscv_fmt_frd_frs1_frs2_frs3,
	/*             fnmadd.s */ riscv_fmt_frd_frs1_frs2_frs3,
	/*               fadd.s */ riscv_fmt_frd_frs1_frs2,
	/*               fsub.s */ riscv_fmt_frd_frs1_frs2,
	/*               fmul.s */ riscv_fmt_frd_frs1_frs2,
	/*               fdiv.s */ riscv_fmt_frd_frs1_frs2,
	/*              fsgnj.s */ riscv_fmt_frd_frs1_frs2,
	/*             fsgnjn.s */ riscv_fmt_frd_frs1_frs2,
	/*             fsgnjx.s */ riscv_fmt_frd_frs1_frs2,
	/*               fmin.s */ riscv_fmt_frd_frs1_frs2,
	/*               fmax.s */ riscv_fmt_frd_frs1_frs2,
	/*              fsqrt.s */ riscv_fmt_frd_frs1_frs2,
	/*                fle.s */ riscv_fmt_rd_frs1_frs2,
	/*                flt.s */ riscv_fmt_rd_frs1_frs2,
	/*                feq.s */ riscv_fmt_rd_frs1_frs2,
	/*             fcvt.w.s */ riscv_fmt_rd_frs1,
	/*            fcvt.wu.s */ riscv_fmt_rd_frs1,
	/*             fcvt.s.w */ riscv_fmt_frd_rs1,
	/*            fcvt.s.wu */ riscv_fmt_frd_rs1,
	/*              fmv.x.s */ riscv_fmt_rd_frs1,
	/*             fclass.s */ riscv_fmt_rd_frs1,
	/*              fmv.s.x */ riscv_fmt_frd_rs1,
	/*             fcvt.l.s */ riscv_fmt_rd_frs1,
	/*            fcvt.lu.s */ riscv_fmt_rd_frs1,
	/*             fcvt.s.l */ riscv_fmt_frd_rs1,
	/*            fcvt.s.lu */ riscv_fmt_frd_rs1,
	/*                  fld */ riscv_fmt_frd_bimm_rs1,
	/*                  fsd */ riscv_fmt_frs2_bimm_rs1,
	/*              fmadd.d */ riscv_fmt_frd_frs1_frs2_frs3,
	/*              fmsub.d */ riscv_fmt_frd_frs1_frs2_frs3,
	/*             fnmsub.d */ riscv_fmt_frd_frs1_frs2_frs3,
	/*             fnmadd.d */ riscv_fmt_frd_frs1_frs2_frs3,
	/*               fadd.d */ riscv_fmt_frd_frs1_frs2,
	/*               fsub.d */ riscv_fmt_frd_frs1_frs2,
	/*               fmul.d */ riscv_fmt_frd_frs1_frs2,
	/*               fdiv.d */ riscv_fmt_frd_frs1_frs2,
	/*              fsgnj.d */ riscv_fmt_frd_frs1_frs2,
	/*             fsgnjn.d */ riscv_fmt_frd_frs1_frs2,
	/*             fsgnjx.d */ riscv_fmt_frd_frs1_frs2,
	/*               fmin.d */ riscv_fmt_frd_frs1_frs2,
	/*               fmax.d */ riscv_fmt_frd_frs1_frs2,
	/*             fcvt.s.d */ riscv_fmt_frd_frs1,
	/*             fcvt.d.s */ riscv_fmt_frd_frs1,
	/*              fsqrt.d */ riscv_fmt_frd_frs1,
	/*                fle.d */ riscv_fmt_rd_frs1_frs2,
	/*                flt.d */ riscv_fmt_rd_frs1_frs2,
	/*                feq.d */ riscv_fmt_rd_frs1_frs2,
	/*             fcvt.w.d */ riscv_fmt_rd_frs1,
	/*            fcvt.wu.d */ riscv_fmt_rd_frs1,
	/*             fcvt.d.w */ riscv_fmt_frd_rs1,
	/*            fcvt.d.wu */ riscv_fmt_frd_rs1,
	/*              fmv.x.d */ riscv_fmt_rd_frs1,
	/*             fclass.d */ riscv_fmt_rd_frs1,
	/*              fmv.d.x */ riscv_fmt_frd_rs1,
	/*             fcvt.l.d */ riscv_fmt_rd_frs1,
	/*            fcvt.lu.d */ riscv_fmt_rd_frs1,
	/*             fcvt.d.l */ riscv_fmt_frd_rs1,
	/*            fcvt.d.lu */ riscv_fmt_frd_rs1,
	/*                frcsr */ riscv_fmt_rd_csr_rs1,
	/*                 frrm */ riscv_fmt_rd_csr_rs1,
	/*              frflags */ riscv_fmt_rd_csr_rs1,
	/*                fscsr */ riscv_fmt_rd_csr_rs1,
	/*                 fsrm */ riscv_fmt_rd_csr_rs1,
	/*              fsflags */ riscv_fmt_rd_csr_rs1,
	/*                fsrmi */ riscv_fmt_rd_csr_irs1,
	/*             fsflagsi */ riscv_fmt_rd_csr_irs1,
	/*           c.addi4spn */ riscv_fmt_rd_rs1_imm,
	/*                c.fld */ riscv_fmt_frd_bimm_rs1,
	/*                 c.lw */ riscv_fmt_rd_bimm_rs1,
	/*                c.flw */ riscv_fmt_frd_bimm_rs1,
	/*                c.fsd */ riscv_fmt_frs2_bimm_rs1,
	/*                 c.sw */ riscv_fmt_rs2_bimm_rs1,
	/*                c.fsw */ riscv_fmt_frs2_bimm_rs1,
	/*                c.nop */ riscv_fmt_none,
	/*               c.addi */ riscv_fmt_rd_rs1_imm,
	/*                c.jal */ riscv_fmt_rd_ipc,
	/*                 c.li */ riscv_fmt_rd_rs1_imm,
	/*                c.lui */ riscv_fmt_rd_imm,
	/*           c.addi16sp */ riscv_fmt_rd_rs1_imm,
	/*               c.srli */ riscv_fmt_rd_rs1_imm,
	/*               c.srai */ riscv_fmt_rd_rs1_imm,
	/*               c.andi */ riscv_fmt_rs1_rs2_ipc,
	/*                c.sub */ riscv_fmt_rd_rs1_rs2,
	/*                c.xor */ riscv_fmt_rd_rs1_rs2,
	/*                 c.or */ riscv_fmt_rd_rs1_rs2,
	/*                c.and */ riscv_fmt_rd_rs1_rs2,
	/*               c.subw */ riscv_fmt_rd_rs1_rs2,
	/*               c.addw */ riscv_fmt_rd_rs1_rs2,
	/*                  c.j */ riscv_fmt_rd_ipc,
	/*               c.beqz */ riscv_fmt_rs1_rs2_ipc,
	/*               c.bnez */ riscv_fmt_rs1_rs2_ipc,
	/*               c.slli */ riscv_fmt_rd_rs1_imm,
	/*              c.fldsp */ riscv_fmt_frd_bimm_rs1,
	/*               c.lwsp */ riscv_fmt_rd_bimm_rs1,
	/*              c.flwsp */ riscv_fmt_frd_bimm_rs1,
	/*                 c.jr */ riscv_fmt_rd_rs1_imm,
	/*                 c.mv */ riscv_fmt_rd_rs1_rs2,
	/*             c.ebreak */ riscv_fmt_none,
	/*               c.jalr */ riscv_fmt_rd_rs1_imm,
	/*                c.add */ riscv_fmt_rd_rs1_rs2,
	/*              c.fsdsp */ riscv_fmt_frs2_bimm_rs1,
	/*               c.swsp */ riscv_fmt_rs2_bimm_rs1,
	/*              c.fswsp */ riscv_fmt_frs2_bimm_rs1,
	/*                 c.ld */ riscv_fmt_rd_bimm_rs1,
	/*                 c.sd */ riscv_fmt_rs2_bimm_rs1,
	/*              c.addiw */ riscv_fmt_rd_rs1_imm,
	/*               c.ldsp */ riscv_fmt_rd_bimm_rs1,
	/*               c.sdsp */ riscv_fmt_rs2_bimm_rs1,
};

const char* riscv_i_registers[] = {
	"zero",
	"ra",
	"sp",
	"gp",
	"tp",
	"t0",
	"t1",
	"t2",
	"s0",
	"s1",
	"a0",
	"a1",
	"a2",
	"a3",
	"a4",
	"a5",
	"a6",
	"a7",
	"s2",
	"s3",
	"s4",
	"s5",
	"s6",
	"s7",
	"s8",
	"s9",
	"s10",
	"s11",
	"t3",
	"t4",
	"t5",
	"t6",
};

const char* riscv_f_registers[] = {
	"ft0",
	"ft1",
	"ft2",
	"ft3",
	"ft4",
	"ft5",
	"ft6",
	"ft7",
	"fs0",
	"fs1",
	"fa0",
	"fa1",
	"fa2",
	"fa3",
	"fa4",
	"fa5",
	"fa6",
	"fa7",
	"fs2",
	"fs3",
	"fs4",
	"fs5",
	"fs6",
	"fs7",
	"fs8",
	"fs9",
	"fs10",
	"fs11",
	"ft8",
	"ft9",
	"ft10",
	"ft11",
};

const rvc_constraint rvcc_c_addi4spn[] =            { rvc_imm_10, rvc_imm_scale_4, rvc_rd_comp, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_fld[] =                 { rvc_imm_8, rvc_imm_scale_8, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_lw[] =                  { rvc_imm_7, rvc_imm_scale_4, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_flw[] =                 { rvc_imm_7, rvc_imm_scale_4, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_fsd[] =                 { rvc_imm_8, rvc_imm_scale_8, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_sw[] =                  { rvc_imm_7, rvc_imm_scale_4, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_fsw[] =                 { rvc_imm_7, rvc_imm_scale_4, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_nop[] =                 { rvc_rd_eq_zero, rvc_rs1_eq_zero, rvc_rs2_eq_zero, rvc_end };
const rvc_constraint rvcc_c_addi[] =                { rvc_imm_6, rvc_rd_not_zero, rvc_rd_eq_rs1, rvc_end };
const rvc_constraint rvcc_c_jal[] =                 { rvc_imm_12, rvc_imm_scale_2, rvc_rd_eq_ra, rvc_end };
const rvc_constraint rvcc_c_li[] =                  { rvc_imm_6, rvc_rd_not_zero, rvc_rd_eq_rs1, rvc_end };
const rvc_constraint rvcc_c_lui[] =                 { rvc_imm_18, rvc_imm_not_zero, rvc_rd_not_zero, rvc_rd_not_sp, rvc_end };
const rvc_constraint rvcc_c_addi16sp[] =            { rvc_imm_10, rvc_imm_scale_4, rvc_rd_eq_sp, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_srli[] =                { rvc_imm_not_zero, rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_srai[] =                { rvc_imm_not_zero, rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_andi[] =                { rvc_imm_not_zero, rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_sub[] =                 { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_xor[] =                 { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_or[] =                  { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_and[] =                 { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_subw[] =                { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_addw[] =                { rvc_rd_eq_rs1, rvc_rd_comp, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_j[] =                   { rvc_imm_12, rvc_imm_scale_2, rvc_rd_eq_zero, rvc_end };
const rvc_constraint rvcc_c_beqz[] =                { rvc_imm_9, rvc_imm_scale_2, rvc_rs1_comp, rvc_rs2_eq_zero, rvc_end };
const rvc_constraint rvcc_c_bnez[] =                { rvc_imm_9, rvc_imm_scale_2, rvc_rs1_comp, rvc_rs2_eq_zero, rvc_end };
const rvc_constraint rvcc_c_slli[] =                { rvc_imm_not_zero, rvc_rd_not_zero, rvc_rd_eq_rs1, rvc_end };
const rvc_constraint rvcc_c_fldsp[] =               { rvc_imm_9, rvc_imm_scale_8, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_lwsp[] =                { rvc_imm_8, rvc_imm_scale_4, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_flwsp[] =               { rvc_imm_8, rvc_imm_scale_4, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_jr[] =                  { rvc_rd_eq_zero, rvc_rs2_eq_zero, rvc_end };
const rvc_constraint rvcc_c_mv[] =                  { rvc_rs1_eq_zero, rvc_rd_not_zero, rvc_rs2_not_zero, rvc_end };
const rvc_constraint rvcc_c_ebreak[] =              { rvc_end };
const rvc_constraint rvcc_c_jalr[] =                { rvc_rd_eq_ra, rvc_rs2_eq_zero, rvc_end };
const rvc_constraint rvcc_c_add[] =                 { rvc_rd_eq_rs1, rvc_rd_not_zero, rvc_rs2_not_zero, rvc_end };
const rvc_constraint rvcc_c_fsdsp[] =               { rvc_imm_9, rvc_imm_scale_8, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_swsp[] =                { rvc_imm_8, rvc_imm_scale_4, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_fswsp[] =               { rvc_imm_8, rvc_imm_scale_4, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_ld[] =                  { rvc_imm_8, rvc_imm_scale_8, rvc_rd_comp, rvc_rs1_comp, rvc_end };
const rvc_constraint rvcc_c_sd[] =                  { rvc_imm_8, rvc_imm_scale_8, rvc_rs1_comp, rvc_rs2_comp, rvc_end };
const rvc_constraint rvcc_c_addiw[] =               { rvc_imm_6, rvc_rd_not_zero, rvc_rd_eq_rs1, rvc_end };
const rvc_constraint rvcc_c_ldsp[] =                { rvc_imm_9, rvc_imm_scale_8, rvc_rs1_eq_sp, rvc_end };
const rvc_constraint rvcc_c_sdsp[] =                { rvc_imm_9, rvc_imm_scale_8, rvc_rs1_eq_sp, rvc_end };

const riscv_comp_data rvcd_lui[] =                   { { riscv_op_c_lui, rvcc_c_lui }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_jal[] =                   { { riscv_op_c_jal, rvcc_c_jal }, { riscv_op_c_j, rvcc_c_j }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_jalr[] =                  { { riscv_op_c_jr, rvcc_c_jr }, { riscv_op_c_jalr, rvcc_c_jalr }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_beq[] =                   { { riscv_op_c_beqz, rvcc_c_beqz }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_bne[] =                   { { riscv_op_c_bnez, rvcc_c_bnez }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_lw[] =                    { { riscv_op_c_lw, rvcc_c_lw }, { riscv_op_c_lwsp, rvcc_c_lwsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_sw[] =                    { { riscv_op_c_sw, rvcc_c_sw }, { riscv_op_c_swsp, rvcc_c_swsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_addi[] =                  { { riscv_op_c_addi4spn, rvcc_c_addi4spn }, { riscv_op_c_nop, rvcc_c_nop }, { riscv_op_c_addi, rvcc_c_addi }, { riscv_op_c_li, rvcc_c_li }, { riscv_op_c_addi16sp, rvcc_c_addi16sp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_andi[] =                  { { riscv_op_c_andi, rvcc_c_andi }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_slli_rv32i[] =            { { riscv_op_c_slli, rvcc_c_slli }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_srli_rv32i[] =            { { riscv_op_c_srli, rvcc_c_srli }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_srai_rv32i[] =            { { riscv_op_c_srai, rvcc_c_srai }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_add[] =                   { { riscv_op_c_mv, rvcc_c_mv }, { riscv_op_c_add, rvcc_c_add }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_sub[] =                   { { riscv_op_c_sub, rvcc_c_sub }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_xor[] =                   { { riscv_op_c_xor, rvcc_c_xor }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_or[] =                    { { riscv_op_c_or, rvcc_c_or }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_and[] =                   { { riscv_op_c_and, rvcc_c_and }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_ld[] =                    { { riscv_op_c_ld, rvcc_c_ld }, { riscv_op_c_ldsp, rvcc_c_ldsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_sd[] =                    { { riscv_op_c_sd, rvcc_c_sd }, { riscv_op_c_sdsp, rvcc_c_sdsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_slli_rv64i[] =            { { riscv_op_c_slli, rvcc_c_slli }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_srli_rv64i[] =            { { riscv_op_c_srli, rvcc_c_srli }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_srai_rv64i[] =            { { riscv_op_c_srai, rvcc_c_srai }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_addiw[] =                 { { riscv_op_c_addiw, rvcc_c_addiw }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_addw[] =                  { { riscv_op_c_addw, rvcc_c_addw }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_subw[] =                  { { riscv_op_c_subw, rvcc_c_subw }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_sbreak[] =                { { riscv_op_c_ebreak, rvcc_c_ebreak }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_flw[] =                   { { riscv_op_c_flw, rvcc_c_flw }, { riscv_op_c_flwsp, rvcc_c_flwsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_fsw[] =                   { { riscv_op_c_fsw, rvcc_c_fsw }, { riscv_op_c_fswsp, rvcc_c_fswsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_fld[] =                   { { riscv_op_c_fld, rvcc_c_fld }, { riscv_op_c_fldsp, rvcc_c_fldsp }, { riscv_op_unknown, nullptr } };
const riscv_comp_data rvcd_fsd[] =                   { { riscv_op_c_fsd, rvcc_c_fsd }, { riscv_op_c_fsdsp, rvcc_c_fsdsp }, { riscv_op_unknown, nullptr } };

const riscv_comp_data* riscv_instruction_comp[] = {
	/*              unknown */ nullptr,
	/*                  lui */ rvcd_lui,
	/*                auipc */ nullptr,
	/*                  jal */ rvcd_jal,
	/*                 jalr */ rvcd_jalr,
	/*                  beq */ rvcd_beq,
	/*                  bne */ rvcd_bne,
	/*                  blt */ nullptr,
	/*                  bge */ nullptr,
	/*                 bltu */ nullptr,
	/*                 bgeu */ nullptr,
	/*                   lb */ nullptr,
	/*                   lh */ nullptr,
	/*                   lw */ rvcd_lw,
	/*                  lbu */ nullptr,
	/*                  lhu */ nullptr,
	/*                   sb */ nullptr,
	/*                   sh */ nullptr,
	/*                   sw */ rvcd_sw,
	/*                 addi */ rvcd_addi,
	/*                 slti */ nullptr,
	/*                sltiu */ nullptr,
	/*                 xori */ nullptr,
	/*                  ori */ nullptr,
	/*                 andi */ rvcd_andi,
	/*           slli.rv32i */ rvcd_slli_rv32i,
	/*           srli.rv32i */ rvcd_srli_rv32i,
	/*           srai.rv32i */ rvcd_srai_rv32i,
	/*                  add */ rvcd_add,
	/*                  sub */ rvcd_sub,
	/*                  sll */ nullptr,
	/*                  slt */ nullptr,
	/*                 sltu */ nullptr,
	/*                  xor */ rvcd_xor,
	/*                  srl */ nullptr,
	/*                  sra */ nullptr,
	/*                   or */ rvcd_or,
	/*                  and */ rvcd_and,
	/*                fence */ nullptr,
	/*              fence.i */ nullptr,
	/*                  lwu */ nullptr,
	/*                   ld */ rvcd_ld,
	/*                   sd */ rvcd_sd,
	/*           slli.rv64i */ rvcd_slli_rv64i,
	/*           srli.rv64i */ rvcd_srli_rv64i,
	/*           srai.rv64i */ rvcd_srai_rv64i,
	/*                addiw */ rvcd_addiw,
	/*                slliw */ nullptr,
	/*                srliw */ nullptr,
	/*                sraiw */ nullptr,
	/*                 addw */ rvcd_addw,
	/*                 subw */ rvcd_subw,
	/*                 sllw */ nullptr,
	/*                 srlw */ nullptr,
	/*                 sraw */ nullptr,
	/*                  mul */ nullptr,
	/*                 mulh */ nullptr,
	/*               mulhsu */ nullptr,
	/*                mulhu */ nullptr,
	/*                  div */ nullptr,
	/*                 divu */ nullptr,
	/*                  rem */ nullptr,
	/*                 remu */ nullptr,
	/*                 mulw */ nullptr,
	/*                 divw */ nullptr,
	/*                divuw */ nullptr,
	/*                 remw */ nullptr,
	/*                remuw */ nullptr,
	/*                 lr.w */ nullptr,
	/*                 sc.w */ nullptr,
	/*            amoswap.w */ nullptr,
	/*             amoadd.w */ nullptr,
	/*             amoxor.w */ nullptr,
	/*              amoor.w */ nullptr,
	/*             amoand.w */ nullptr,
	/*             amomin.w */ nullptr,
	/*             amomax.w */ nullptr,
	/*            amominu.w */ nullptr,
	/*            amomaxu.w */ nullptr,
	/*                 lr.d */ nullptr,
	/*                 sc.d */ nullptr,
	/*            amoswap.d */ nullptr,
	/*             amoadd.d */ nullptr,
	/*             amoxor.d */ nullptr,
	/*              amoor.d */ nullptr,
	/*             amoand.d */ nullptr,
	/*             amomin.d */ nullptr,
	/*             amomax.d */ nullptr,
	/*            amominu.d */ nullptr,
	/*            amomaxu.d */ nullptr,
	/*                scall */ nullptr,
	/*               sbreak */ rvcd_sbreak,
	/*                 sret */ nullptr,
	/*            sfence.vm */ nullptr,
	/*                  wfi */ nullptr,
	/*                 mrth */ nullptr,
	/*                 mrts */ nullptr,
	/*                 hrts */ nullptr,
	/*              rdcycle */ nullptr,
	/*               rdtime */ nullptr,
	/*            rdinstret */ nullptr,
	/*             rdcycleh */ nullptr,
	/*              rdtimeh */ nullptr,
	/*           rdinstreth */ nullptr,
	/*                csrrw */ nullptr,
	/*                csrrs */ nullptr,
	/*                csrrc */ nullptr,
	/*               csrrwi */ nullptr,
	/*               csrrsi */ nullptr,
	/*               csrrci */ nullptr,
	/*                  flw */ rvcd_flw,
	/*                  fsw */ rvcd_fsw,
	/*              fmadd.s */ nullptr,
	/*              fmsub.s */ nullptr,
	/*             fnmsub.s */ nullptr,
	/*             fnmadd.s */ nullptr,
	/*               fadd.s */ nullptr,
	/*               fsub.s */ nullptr,
	/*               fmul.s */ nullptr,
	/*               fdiv.s */ nullptr,
	/*              fsgnj.s */ nullptr,
	/*             fsgnjn.s */ nullptr,
	/*             fsgnjx.s */ nullptr,
	/*               fmin.s */ nullptr,
	/*               fmax.s */ nullptr,
	/*              fsqrt.s */ nullptr,
	/*                fle.s */ nullptr,
	/*                flt.s */ nullptr,
	/*                feq.s */ nullptr,
	/*             fcvt.w.s */ nullptr,
	/*            fcvt.wu.s */ nullptr,
	/*             fcvt.s.w */ nullptr,
	/*            fcvt.s.wu */ nullptr,
	/*              fmv.x.s */ nullptr,
	/*             fclass.s */ nullptr,
	/*              fmv.s.x */ nullptr,
	/*             fcvt.l.s */ nullptr,
	/*            fcvt.lu.s */ nullptr,
	/*             fcvt.s.l */ nullptr,
	/*            fcvt.s.lu */ nullptr,
	/*                  fld */ rvcd_fld,
	/*                  fsd */ rvcd_fsd,
	/*              fmadd.d */ nullptr,
	/*              fmsub.d */ nullptr,
	/*             fnmsub.d */ nullptr,
	/*             fnmadd.d */ nullptr,
	/*               fadd.d */ nullptr,
	/*               fsub.d */ nullptr,
	/*               fmul.d */ nullptr,
	/*               fdiv.d */ nullptr,
	/*              fsgnj.d */ nullptr,
	/*             fsgnjn.d */ nullptr,
	/*             fsgnjx.d */ nullptr,
	/*               fmin.d */ nullptr,
	/*               fmax.d */ nullptr,
	/*             fcvt.s.d */ nullptr,
	/*             fcvt.d.s */ nullptr,
	/*              fsqrt.d */ nullptr,
	/*                fle.d */ nullptr,
	/*                flt.d */ nullptr,
	/*                feq.d */ nullptr,
	/*             fcvt.w.d */ nullptr,
	/*            fcvt.wu.d */ nullptr,
	/*             fcvt.d.w */ nullptr,
	/*            fcvt.d.wu */ nullptr,
	/*              fmv.x.d */ nullptr,
	/*             fclass.d */ nullptr,
	/*              fmv.d.x */ nullptr,
	/*             fcvt.l.d */ nullptr,
	/*            fcvt.lu.d */ nullptr,
	/*             fcvt.d.l */ nullptr,
	/*            fcvt.d.lu */ nullptr,
	/*                frcsr */ nullptr,
	/*                 frrm */ nullptr,
	/*              frflags */ nullptr,
	/*                fscsr */ nullptr,
	/*                 fsrm */ nullptr,
	/*              fsflags */ nullptr,
	/*                fsrmi */ nullptr,
	/*             fsflagsi */ nullptr,
	/*           c.addi4spn */ nullptr,
	/*                c.fld */ nullptr,
	/*                 c.lw */ nullptr,
	/*                c.flw */ nullptr,
	/*                c.fsd */ nullptr,
	/*                 c.sw */ nullptr,
	/*                c.fsw */ nullptr,
	/*                c.nop */ nullptr,
	/*               c.addi */ nullptr,
	/*                c.jal */ nullptr,
	/*                 c.li */ nullptr,
	/*                c.lui */ nullptr,
	/*           c.addi16sp */ nullptr,
	/*               c.srli */ nullptr,
	/*               c.srai */ nullptr,
	/*               c.andi */ nullptr,
	/*                c.sub */ nullptr,
	/*                c.xor */ nullptr,
	/*                 c.or */ nullptr,
	/*                c.and */ nullptr,
	/*               c.subw */ nullptr,
	/*               c.addw */ nullptr,
	/*                  c.j */ nullptr,
	/*               c.beqz */ nullptr,
	/*               c.bnez */ nullptr,
	/*               c.slli */ nullptr,
	/*              c.fldsp */ nullptr,
	/*               c.lwsp */ nullptr,
	/*              c.flwsp */ nullptr,
	/*                 c.jr */ nullptr,
	/*                 c.mv */ nullptr,
	/*             c.ebreak */ nullptr,
	/*               c.jalr */ nullptr,
	/*                c.add */ nullptr,
	/*              c.fsdsp */ nullptr,
	/*               c.swsp */ nullptr,
	/*              c.fswsp */ nullptr,
	/*                 c.ld */ nullptr,
	/*                 c.sd */ nullptr,
	/*              c.addiw */ nullptr,
	/*               c.ldsp */ nullptr,
	/*               c.sdsp */ nullptr,
};

const riscv_op riscv_instruction_decomp[] = {
	/*              unknown */ riscv_op_unknown,
	/*                  lui */ riscv_op_unknown,
	/*                auipc */ riscv_op_unknown,
	/*                  jal */ riscv_op_unknown,
	/*                 jalr */ riscv_op_unknown,
	/*                  beq */ riscv_op_unknown,
	/*                  bne */ riscv_op_unknown,
	/*                  blt */ riscv_op_unknown,
	/*                  bge */ riscv_op_unknown,
	/*                 bltu */ riscv_op_unknown,
	/*                 bgeu */ riscv_op_unknown,
	/*                   lb */ riscv_op_unknown,
	/*                   lh */ riscv_op_unknown,
	/*                   lw */ riscv_op_unknown,
	/*                  lbu */ riscv_op_unknown,
	/*                  lhu */ riscv_op_unknown,
	/*                   sb */ riscv_op_unknown,
	/*                   sh */ riscv_op_unknown,
	/*                   sw */ riscv_op_unknown,
	/*                 addi */ riscv_op_unknown,
	/*                 slti */ riscv_op_unknown,
	/*                sltiu */ riscv_op_unknown,
	/*                 xori */ riscv_op_unknown,
	/*                  ori */ riscv_op_unknown,
	/*                 andi */ riscv_op_unknown,
	/*           slli.rv32i */ riscv_op_unknown,
	/*           srli.rv32i */ riscv_op_unknown,
	/*           srai.rv32i */ riscv_op_unknown,
	/*                  add */ riscv_op_unknown,
	/*                  sub */ riscv_op_unknown,
	/*                  sll */ riscv_op_unknown,
	/*                  slt */ riscv_op_unknown,
	/*                 sltu */ riscv_op_unknown,
	/*                  xor */ riscv_op_unknown,
	/*                  srl */ riscv_op_unknown,
	/*                  sra */ riscv_op_unknown,
	/*                   or */ riscv_op_unknown,
	/*                  and */ riscv_op_unknown,
	/*                fence */ riscv_op_unknown,
	/*              fence.i */ riscv_op_unknown,
	/*                  lwu */ riscv_op_unknown,
	/*                   ld */ riscv_op_unknown,
	/*                   sd */ riscv_op_unknown,
	/*           slli.rv64i */ riscv_op_unknown,
	/*           srli.rv64i */ riscv_op_unknown,
	/*           srai.rv64i */ riscv_op_unknown,
	/*                addiw */ riscv_op_unknown,
	/*                slliw */ riscv_op_unknown,
	/*                srliw */ riscv_op_unknown,
	/*                sraiw */ riscv_op_unknown,
	/*                 addw */ riscv_op_unknown,
	/*                 subw */ riscv_op_unknown,
	/*                 sllw */ riscv_op_unknown,
	/*                 srlw */ riscv_op_unknown,
	/*                 sraw */ riscv_op_unknown,
	/*                  mul */ riscv_op_unknown,
	/*                 mulh */ riscv_op_unknown,
	/*               mulhsu */ riscv_op_unknown,
	/*                mulhu */ riscv_op_unknown,
	/*                  div */ riscv_op_unknown,
	/*                 divu */ riscv_op_unknown,
	/*                  rem */ riscv_op_unknown,
	/*                 remu */ riscv_op_unknown,
	/*                 mulw */ riscv_op_unknown,
	/*                 divw */ riscv_op_unknown,
	/*                divuw */ riscv_op_unknown,
	/*                 remw */ riscv_op_unknown,
	/*                remuw */ riscv_op_unknown,
	/*                 lr.w */ riscv_op_unknown,
	/*                 sc.w */ riscv_op_unknown,
	/*            amoswap.w */ riscv_op_unknown,
	/*             amoadd.w */ riscv_op_unknown,
	/*             amoxor.w */ riscv_op_unknown,
	/*              amoor.w */ riscv_op_unknown,
	/*             amoand.w */ riscv_op_unknown,
	/*             amomin.w */ riscv_op_unknown,
	/*             amomax.w */ riscv_op_unknown,
	/*            amominu.w */ riscv_op_unknown,
	/*            amomaxu.w */ riscv_op_unknown,
	/*                 lr.d */ riscv_op_unknown,
	/*                 sc.d */ riscv_op_unknown,
	/*            amoswap.d */ riscv_op_unknown,
	/*             amoadd.d */ riscv_op_unknown,
	/*             amoxor.d */ riscv_op_unknown,
	/*              amoor.d */ riscv_op_unknown,
	/*             amoand.d */ riscv_op_unknown,
	/*             amomin.d */ riscv_op_unknown,
	/*             amomax.d */ riscv_op_unknown,
	/*            amominu.d */ riscv_op_unknown,
	/*            amomaxu.d */ riscv_op_unknown,
	/*                scall */ riscv_op_unknown,
	/*               sbreak */ riscv_op_unknown,
	/*                 sret */ riscv_op_unknown,
	/*            sfence.vm */ riscv_op_unknown,
	/*                  wfi */ riscv_op_unknown,
	/*                 mrth */ riscv_op_unknown,
	/*                 mrts */ riscv_op_unknown,
	/*                 hrts */ riscv_op_unknown,
	/*              rdcycle */ riscv_op_unknown,
	/*               rdtime */ riscv_op_unknown,
	/*            rdinstret */ riscv_op_unknown,
	/*             rdcycleh */ riscv_op_unknown,
	/*              rdtimeh */ riscv_op_unknown,
	/*           rdinstreth */ riscv_op_unknown,
	/*                csrrw */ riscv_op_unknown,
	/*                csrrs */ riscv_op_unknown,
	/*                csrrc */ riscv_op_unknown,
	/*               csrrwi */ riscv_op_unknown,
	/*               csrrsi */ riscv_op_unknown,
	/*               csrrci */ riscv_op_unknown,
	/*                  flw */ riscv_op_unknown,
	/*                  fsw */ riscv_op_unknown,
	/*              fmadd.s */ riscv_op_unknown,
	/*              fmsub.s */ riscv_op_unknown,
	/*             fnmsub.s */ riscv_op_unknown,
	/*             fnmadd.s */ riscv_op_unknown,
	/*               fadd.s */ riscv_op_unknown,
	/*               fsub.s */ riscv_op_unknown,
	/*               fmul.s */ riscv_op_unknown,
	/*               fdiv.s */ riscv_op_unknown,
	/*              fsgnj.s */ riscv_op_unknown,
	/*             fsgnjn.s */ riscv_op_unknown,
	/*             fsgnjx.s */ riscv_op_unknown,
	/*               fmin.s */ riscv_op_unknown,
	/*               fmax.s */ riscv_op_unknown,
	/*              fsqrt.s */ riscv_op_unknown,
	/*                fle.s */ riscv_op_unknown,
	/*                flt.s */ riscv_op_unknown,
	/*                feq.s */ riscv_op_unknown,
	/*             fcvt.w.s */ riscv_op_unknown,
	/*            fcvt.wu.s */ riscv_op_unknown,
	/*             fcvt.s.w */ riscv_op_unknown,
	/*            fcvt.s.wu */ riscv_op_unknown,
	/*              fmv.x.s */ riscv_op_unknown,
	/*             fclass.s */ riscv_op_unknown,
	/*              fmv.s.x */ riscv_op_unknown,
	/*             fcvt.l.s */ riscv_op_unknown,
	/*            fcvt.lu.s */ riscv_op_unknown,
	/*             fcvt.s.l */ riscv_op_unknown,
	/*            fcvt.s.lu */ riscv_op_unknown,
	/*                  fld */ riscv_op_unknown,
	/*                  fsd */ riscv_op_unknown,
	/*              fmadd.d */ riscv_op_unknown,
	/*              fmsub.d */ riscv_op_unknown,
	/*             fnmsub.d */ riscv_op_unknown,
	/*             fnmadd.d */ riscv_op_unknown,
	/*               fadd.d */ riscv_op_unknown,
	/*               fsub.d */ riscv_op_unknown,
	/*               fmul.d */ riscv_op_unknown,
	/*               fdiv.d */ riscv_op_unknown,
	/*              fsgnj.d */ riscv_op_unknown,
	/*             fsgnjn.d */ riscv_op_unknown,
	/*             fsgnjx.d */ riscv_op_unknown,
	/*               fmin.d */ riscv_op_unknown,
	/*               fmax.d */ riscv_op_unknown,
	/*             fcvt.s.d */ riscv_op_unknown,
	/*             fcvt.d.s */ riscv_op_unknown,
	/*              fsqrt.d */ riscv_op_unknown,
	/*                fle.d */ riscv_op_unknown,
	/*                flt.d */ riscv_op_unknown,
	/*                feq.d */ riscv_op_unknown,
	/*             fcvt.w.d */ riscv_op_unknown,
	/*            fcvt.wu.d */ riscv_op_unknown,
	/*             fcvt.d.w */ riscv_op_unknown,
	/*            fcvt.d.wu */ riscv_op_unknown,
	/*              fmv.x.d */ riscv_op_unknown,
	/*             fclass.d */ riscv_op_unknown,
	/*              fmv.d.x */ riscv_op_unknown,
	/*             fcvt.l.d */ riscv_op_unknown,
	/*            fcvt.lu.d */ riscv_op_unknown,
	/*             fcvt.d.l */ riscv_op_unknown,
	/*            fcvt.d.lu */ riscv_op_unknown,
	/*                frcsr */ riscv_op_unknown,
	/*                 frrm */ riscv_op_unknown,
	/*              frflags */ riscv_op_unknown,
	/*                fscsr */ riscv_op_unknown,
	/*                 fsrm */ riscv_op_unknown,
	/*              fsflags */ riscv_op_unknown,
	/*                fsrmi */ riscv_op_unknown,
	/*             fsflagsi */ riscv_op_unknown,
	/*           c.addi4spn */ riscv_op_addi,
	/*                c.fld */ riscv_op_fld,
	/*                 c.lw */ riscv_op_lw,
	/*                c.flw */ riscv_op_flw,
	/*                c.fsd */ riscv_op_fsd,
	/*                 c.sw */ riscv_op_sw,
	/*                c.fsw */ riscv_op_fsw,
	/*                c.nop */ riscv_op_addi,
	/*               c.addi */ riscv_op_addi,
	/*                c.jal */ riscv_op_jal,
	/*                 c.li */ riscv_op_addi,
	/*                c.lui */ riscv_op_lui,
	/*           c.addi16sp */ riscv_op_addi,
	/*               c.srli */ riscv_op_srli_rv64i,
	/*               c.srai */ riscv_op_srai_rv64i,
	/*               c.andi */ riscv_op_andi,
	/*                c.sub */ riscv_op_sub,
	/*                c.xor */ riscv_op_xor,
	/*                 c.or */ riscv_op_or,
	/*                c.and */ riscv_op_and,
	/*               c.subw */ riscv_op_subw,
	/*               c.addw */ riscv_op_addw,
	/*                  c.j */ riscv_op_jal,
	/*               c.beqz */ riscv_op_beq,
	/*               c.bnez */ riscv_op_bne,
	/*               c.slli */ riscv_op_slli_rv64i,
	/*              c.fldsp */ riscv_op_fld,
	/*               c.lwsp */ riscv_op_lw,
	/*              c.flwsp */ riscv_op_flw,
	/*                 c.jr */ riscv_op_jalr,
	/*                 c.mv */ riscv_op_add,
	/*             c.ebreak */ riscv_op_sbreak,
	/*               c.jalr */ riscv_op_jalr,
	/*                c.add */ riscv_op_add,
	/*              c.fsdsp */ riscv_op_fsd,
	/*               c.swsp */ riscv_op_sw,
	/*              c.fswsp */ riscv_op_fsw,
	/*                 c.ld */ riscv_op_ld,
	/*                 c.sd */ riscv_op_sd,
	/*              c.addiw */ riscv_op_addiw,
	/*               c.ldsp */ riscv_op_ld,
	/*               c.sdsp */ riscv_op_sd,
};

