//
//  riscv-meta.h
//
//  DANGER - This is machine generated code
//

#ifndef riscv_opcodes_h
#define riscv_opcodes_h

enum rvc_constraint
{
	rvc_end,
	rvc_imm_10,
	rvc_imm_12,
	rvc_imm_18,
	rvc_imm_6,
	rvc_imm_7,
	rvc_imm_8,
	rvc_imm_9,
	rvc_imm_not_zero,
	rvc_imm_scale_2,
	rvc_imm_scale_4,
	rvc_imm_scale_8,
	rvc_rd_comp,
	rvc_rd_eq_ra,
	rvc_rd_eq_rs1,
	rvc_rd_eq_sp,
	rvc_rd_eq_zero,
	rvc_rd_not_sp,
	rvc_rd_not_zero,
	rvc_rs1_comp,
	rvc_rs1_eq_sp,
	rvc_rs1_eq_zero,
	rvc_rs2_comp,
	rvc_rs2_eq_zero,
	rvc_rs2_not_zero,
};

enum riscv_csr
{
	riscv_csr_fflags = 0x001,
	riscv_csr_frm = 0x002,
	riscv_csr_fcsr = 0x003,
	riscv_csr_cycle = 0xC00,
	riscv_csr_time = 0xC01,
	riscv_csr_instret = 0xC02,
	riscv_csr_cycleh = 0xC80,
	riscv_csr_timeh = 0xC81,
	riscv_csr_instreth = 0xC82,
	riscv_csr_sstatus = 0x100,
	riscv_csr_stvec = 0x101,
	riscv_csr_sie = 0x104,
	riscv_csr_stimecmp = 0x121,
	riscv_csr_stime = 0xD01,
	riscv_csr_stimeh = 0xD81,
	riscv_csr_sscratch = 0x140,
	riscv_csr_sepc = 0x141,
	riscv_csr_scause = 0xD42,
	riscv_csr_sbadaddr = 0xD43,
	riscv_csr_sip = 0x144,
	riscv_csr_sptbr = 0x180,
	riscv_csr_sasid = 0x181,
	riscv_csr_cyclew = 0x900,
	riscv_csr_timew = 0x901,
	riscv_csr_instretw = 0x902,
	riscv_csr_cyclehw = 0x980,
	riscv_csr_timehw = 0x981,
	riscv_csr_instrethw = 0x982,
	riscv_csr_hstatus = 0x200,
	riscv_csr_htvec = 0x201,
	riscv_csr_htdeleg = 0x202,
	riscv_csr_htimecmp = 0x221,
	riscv_csr_htime = 0xE01,
	riscv_csr_htimeh = 0xE81,
	riscv_csr_hscratch = 0x240,
	riscv_csr_hepc = 0x241,
	riscv_csr_hcause = 0x242,
	riscv_csr_hbadaddr = 0x243,
	riscv_csr_stimew = 0xA01,
	riscv_csr_stimehw = 0xA81,
	riscv_csr_mcpuid = 0xF00,
	riscv_csr_mimpid = 0xF01,
	riscv_csr_mhartid = 0xF10,
	riscv_csr_mstatus = 0x300,
	riscv_csr_mtvec = 0x301,
	riscv_csr_mtdeleg = 0x302,
	riscv_csr_mie = 0x304,
	riscv_csr_mtimecmp = 0x321,
	riscv_csr_mscratch = 0x340,
	riscv_csr_mepc = 0x341,
	riscv_csr_mcause = 0x342,
	riscv_csr_mbadaddr = 0x343,
	riscv_csr_mip = 0x344,
	riscv_csr_mbase = 0x380,
	riscv_csr_mbound = 0x381,
	riscv_csr_mibase = 0x382,
	riscv_csr_mibound = 0x383,
	riscv_csr_mdbase = 0x384,
	riscv_csr_mdbound = 0x385,
	riscv_csr_htimew = 0xB01,
	riscv_csr_htimehw = 0xB81,
	riscv_csr_mtohost = 0x780,
	riscv_csr_mfromhost = 0x781,
};

enum riscv_ireg_name
{
	riscv_ireg_x0,
	riscv_ireg_x1,
	riscv_ireg_x2,
	riscv_ireg_x3,
	riscv_ireg_x4,
	riscv_ireg_x5,
	riscv_ireg_x6,
	riscv_ireg_x7,
	riscv_ireg_x8,
	riscv_ireg_x9,
	riscv_ireg_x10,
	riscv_ireg_x11,
	riscv_ireg_x12,
	riscv_ireg_x13,
	riscv_ireg_x14,
	riscv_ireg_x15,
	riscv_ireg_x16,
	riscv_ireg_x17,
	riscv_ireg_x18,
	riscv_ireg_x19,
	riscv_ireg_x20,
	riscv_ireg_x21,
	riscv_ireg_x22,
	riscv_ireg_x23,
	riscv_ireg_x24,
	riscv_ireg_x25,
	riscv_ireg_x26,
	riscv_ireg_x27,
	riscv_ireg_x28,
	riscv_ireg_x29,
	riscv_ireg_x30,
	riscv_ireg_x31,
};

enum riscv_ireg_alias
{
	riscv_ireg_zero,
	riscv_ireg_ra,
	riscv_ireg_sp,
	riscv_ireg_gp,
	riscv_ireg_tp,
	riscv_ireg_t0,
	riscv_ireg_t1,
	riscv_ireg_t2,
	riscv_ireg_s0,
	riscv_ireg_s1,
	riscv_ireg_a0,
	riscv_ireg_a1,
	riscv_ireg_a2,
	riscv_ireg_a3,
	riscv_ireg_a4,
	riscv_ireg_a5,
	riscv_ireg_a6,
	riscv_ireg_a7,
	riscv_ireg_s2,
	riscv_ireg_s3,
	riscv_ireg_s4,
	riscv_ireg_s5,
	riscv_ireg_s6,
	riscv_ireg_s7,
	riscv_ireg_s8,
	riscv_ireg_s9,
	riscv_ireg_s10,
	riscv_ireg_s11,
	riscv_ireg_t3,
	riscv_ireg_t4,
	riscv_ireg_t5,
	riscv_ireg_t6,
};

enum riscv_freg_name
{
	riscv_freg_f0,
	riscv_freg_f1,
	riscv_freg_f2,
	riscv_freg_f3,
	riscv_freg_f4,
	riscv_freg_f5,
	riscv_freg_f6,
	riscv_freg_f7,
	riscv_freg_f8,
	riscv_freg_f9,
	riscv_freg_f10,
	riscv_freg_f11,
	riscv_freg_f12,
	riscv_freg_f13,
	riscv_freg_f14,
	riscv_freg_f15,
	riscv_freg_f16,
	riscv_freg_f17,
	riscv_freg_f18,
	riscv_freg_f19,
	riscv_freg_f20,
	riscv_freg_f21,
	riscv_freg_f22,
	riscv_freg_f23,
	riscv_freg_f24,
	riscv_freg_f25,
	riscv_freg_f26,
	riscv_freg_f27,
	riscv_freg_f28,
	riscv_freg_f29,
	riscv_freg_f30,
	riscv_freg_f31,
};

enum riscv_freg_alias
{
	riscv_freg_ft0,
	riscv_freg_ft1,
	riscv_freg_ft2,
	riscv_freg_ft3,
	riscv_freg_ft4,
	riscv_freg_ft5,
	riscv_freg_ft6,
	riscv_freg_ft7,
	riscv_freg_fs0,
	riscv_freg_fs1,
	riscv_freg_fa0,
	riscv_freg_fa1,
	riscv_freg_fa2,
	riscv_freg_fa3,
	riscv_freg_fa4,
	riscv_freg_fa5,
	riscv_freg_fa6,
	riscv_freg_fa7,
	riscv_freg_fs2,
	riscv_freg_fs3,
	riscv_freg_fs4,
	riscv_freg_fs5,
	riscv_freg_fs6,
	riscv_freg_fs7,
	riscv_freg_fs8,
	riscv_freg_fs9,
	riscv_freg_fs10,
	riscv_freg_fs11,
	riscv_freg_ft8,
	riscv_freg_ft9,
	riscv_freg_ft10,
	riscv_freg_ft11,
};

enum riscv_inst_type
{
	riscv_inst_type_unknown,
	riscv_inst_type_none,
	riscv_inst_type_c_nop,
	riscv_inst_type_cb,
	riscv_inst_type_cb_sh5,
	riscv_inst_type_ci,
	riscv_inst_type_ci_sh5,
	riscv_inst_type_ci_16sp,
	riscv_inst_type_ci_lwsp,
	riscv_inst_type_ci_ldsp,
	riscv_inst_type_ci_li,
	riscv_inst_type_ci_lui,
	riscv_inst_type_ciw_4spn,
	riscv_inst_type_cj,
	riscv_inst_type_cl_lw,
	riscv_inst_type_cl_ld,
	riscv_inst_type_cr,
	riscv_inst_type_cr_mv,
	riscv_inst_type_cr_jalr,
	riscv_inst_type_cr_jr,
	riscv_inst_type_cs,
	riscv_inst_type_cs_sw,
	riscv_inst_type_cs_sd,
	riscv_inst_type_css_swsp,
	riscv_inst_type_css_sdsp,
	riscv_inst_type_i,
	riscv_inst_type_i_sh5,
	riscv_inst_type_i_sh6,
	riscv_inst_type_r,
	riscv_inst_type_r_4f,
	riscv_inst_type_s,
	riscv_inst_type_sb,
	riscv_inst_type_u,
	riscv_inst_type_uj,
};

enum riscv_op
{
	riscv_op_unknown,
	riscv_op_lui,
	riscv_op_auipc,
	riscv_op_jal,
	riscv_op_jalr,
	riscv_op_beq,
	riscv_op_bne,
	riscv_op_blt,
	riscv_op_bge,
	riscv_op_bltu,
	riscv_op_bgeu,
	riscv_op_lb,
	riscv_op_lh,
	riscv_op_lw,
	riscv_op_lbu,
	riscv_op_lhu,
	riscv_op_sb,
	riscv_op_sh,
	riscv_op_sw,
	riscv_op_addi,
	riscv_op_slti,
	riscv_op_sltiu,
	riscv_op_xori,
	riscv_op_ori,
	riscv_op_andi,
	riscv_op_slli_rv32i,
	riscv_op_srli_rv32i,
	riscv_op_srai_rv32i,
	riscv_op_add,
	riscv_op_sub,
	riscv_op_sll,
	riscv_op_slt,
	riscv_op_sltu,
	riscv_op_xor,
	riscv_op_srl,
	riscv_op_sra,
	riscv_op_or,
	riscv_op_and,
	riscv_op_fence,
	riscv_op_fence_i,
	riscv_op_lwu,
	riscv_op_ld,
	riscv_op_sd,
	riscv_op_slli_rv64i,
	riscv_op_srli_rv64i,
	riscv_op_srai_rv64i,
	riscv_op_addiw,
	riscv_op_slliw,
	riscv_op_srliw,
	riscv_op_sraiw,
	riscv_op_addw,
	riscv_op_subw,
	riscv_op_sllw,
	riscv_op_srlw,
	riscv_op_sraw,
	riscv_op_mul,
	riscv_op_mulh,
	riscv_op_mulhsu,
	riscv_op_mulhu,
	riscv_op_div,
	riscv_op_divu,
	riscv_op_rem,
	riscv_op_remu,
	riscv_op_mulw,
	riscv_op_divw,
	riscv_op_divuw,
	riscv_op_remw,
	riscv_op_remuw,
	riscv_op_lr_w,
	riscv_op_sc_w,
	riscv_op_amoswap_w,
	riscv_op_amoadd_w,
	riscv_op_amoxor_w,
	riscv_op_amoor_w,
	riscv_op_amoand_w,
	riscv_op_amomin_w,
	riscv_op_amomax_w,
	riscv_op_amominu_w,
	riscv_op_amomaxu_w,
	riscv_op_lr_d,
	riscv_op_sc_d,
	riscv_op_amoswap_d,
	riscv_op_amoadd_d,
	riscv_op_amoxor_d,
	riscv_op_amoor_d,
	riscv_op_amoand_d,
	riscv_op_amomin_d,
	riscv_op_amomax_d,
	riscv_op_amominu_d,
	riscv_op_amomaxu_d,
	riscv_op_scall,
	riscv_op_sbreak,
	riscv_op_sret,
	riscv_op_sfence_vm,
	riscv_op_wfi,
	riscv_op_mrth,
	riscv_op_mrts,
	riscv_op_hrts,
	riscv_op_rdcycle,
	riscv_op_rdtime,
	riscv_op_rdinstret,
	riscv_op_rdcycleh,
	riscv_op_rdtimeh,
	riscv_op_rdinstreth,
	riscv_op_csrrw,
	riscv_op_csrrs,
	riscv_op_csrrc,
	riscv_op_csrrwi,
	riscv_op_csrrsi,
	riscv_op_csrrci,
	riscv_op_flw,
	riscv_op_fsw,
	riscv_op_fmadd_s,
	riscv_op_fmsub_s,
	riscv_op_fnmsub_s,
	riscv_op_fnmadd_s,
	riscv_op_fadd_s,
	riscv_op_fsub_s,
	riscv_op_fmul_s,
	riscv_op_fdiv_s,
	riscv_op_fsgnj_s,
	riscv_op_fsgnjn_s,
	riscv_op_fsgnjx_s,
	riscv_op_fmin_s,
	riscv_op_fmax_s,
	riscv_op_fsqrt_s,
	riscv_op_fle_s,
	riscv_op_flt_s,
	riscv_op_feq_s,
	riscv_op_fcvt_w_s,
	riscv_op_fcvt_wu_s,
	riscv_op_fcvt_s_w,
	riscv_op_fcvt_s_wu,
	riscv_op_fmv_x_s,
	riscv_op_fclass_s,
	riscv_op_fmv_s_x,
	riscv_op_fcvt_l_s,
	riscv_op_fcvt_lu_s,
	riscv_op_fcvt_s_l,
	riscv_op_fcvt_s_lu,
	riscv_op_fld,
	riscv_op_fsd,
	riscv_op_fmadd_d,
	riscv_op_fmsub_d,
	riscv_op_fnmsub_d,
	riscv_op_fnmadd_d,
	riscv_op_fadd_d,
	riscv_op_fsub_d,
	riscv_op_fmul_d,
	riscv_op_fdiv_d,
	riscv_op_fsgnj_d,
	riscv_op_fsgnjn_d,
	riscv_op_fsgnjx_d,
	riscv_op_fmin_d,
	riscv_op_fmax_d,
	riscv_op_fcvt_s_d,
	riscv_op_fcvt_d_s,
	riscv_op_fsqrt_d,
	riscv_op_fle_d,
	riscv_op_flt_d,
	riscv_op_feq_d,
	riscv_op_fcvt_w_d,
	riscv_op_fcvt_wu_d,
	riscv_op_fcvt_d_w,
	riscv_op_fcvt_d_wu,
	riscv_op_fclass_d,
	riscv_op_fcvt_l_d,
	riscv_op_fcvt_lu_d,
	riscv_op_fmv_x_d,
	riscv_op_fcvt_d_l,
	riscv_op_fcvt_d_lu,
	riscv_op_fmv_d_x,
	riscv_op_frcsr,
	riscv_op_frrm,
	riscv_op_frflags,
	riscv_op_fscsr,
	riscv_op_fsrm,
	riscv_op_fsflags,
	riscv_op_fsrmi,
	riscv_op_fsflagsi,
	riscv_op_c_addi4spn,
	riscv_op_c_fld,
	riscv_op_c_lw,
	riscv_op_c_flw,
	riscv_op_c_fsd,
	riscv_op_c_sw,
	riscv_op_c_fsw,
	riscv_op_c_nop,
	riscv_op_c_addi,
	riscv_op_c_jal,
	riscv_op_c_li,
	riscv_op_c_lui,
	riscv_op_c_addi16sp,
	riscv_op_c_srli,
	riscv_op_c_srai,
	riscv_op_c_andi,
	riscv_op_c_sub,
	riscv_op_c_xor,
	riscv_op_c_or,
	riscv_op_c_and,
	riscv_op_c_subw,
	riscv_op_c_addw,
	riscv_op_c_j,
	riscv_op_c_beqz,
	riscv_op_c_bnez,
	riscv_op_c_slli,
	riscv_op_c_fldsp,
	riscv_op_c_lwsp,
	riscv_op_c_flwsp,
	riscv_op_c_jr,
	riscv_op_c_mv,
	riscv_op_c_ebreak,
	riscv_op_c_jalr,
	riscv_op_c_add,
	riscv_op_c_fsdsp,
	riscv_op_c_swsp,
	riscv_op_c_fswsp,
	riscv_op_c_ld,
	riscv_op_c_sd,
	riscv_op_c_addiw,
	riscv_op_c_ldsp,
	riscv_op_c_sdsp,
};

struct riscv_comp_data
{
	const riscv_op op;
	const rvc_constraint* constraints;
};

extern const char* riscv_i_registers[];
extern const char* riscv_f_registers[];
extern const char* riscv_instruction_name[];
extern const riscv_inst_type riscv_instruction_type[];
extern const riscv_wu riscv_instruction_match[];
extern const riscv_wu riscv_instruction_mask[];
extern const rvf* riscv_instruction_format[];
extern const riscv_comp_data* riscv_instruction_comp[];
extern const riscv_op riscv_instruction_decomp[];

#endif
