#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cstdarg>
#include <cerrno>
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <iostream>
#include <iomanip>

#include <sys/stat.h>

#include "endian.h"
#include "riscv-mc.h"

const char* riscv_instructions[] = {
	"unknown",
	"nop",
	"beq",
	"bne",
	"blt",
	"bge",
	"bltu",
	"bgeu",
	"jalr",
	"jal",
	"lui",
	"auipc",
	"addi",
	"slli",
	"slti",
	"sltiu",
	"xori",
	"srli",
	"srai",
	"ori",
	"andi",
	"add",
	"sub",
	"sll",
	"slt",
	"sltu",
	"xor",
	"srl",
	"sra",
	"or",
	"and",
	"addiw",
	"slliw",
	"srliw",
	"sraiw",
	"addw",
	"subw",
	"sllw",
	"srlw",
	"sraw",
	"lb",
	"lh",
	"lw",
	"ld",
	"lbu",
	"lhu",
	"lwu",
	"sb",
	"sh",
	"sw",
	"sd",
	"fence",
	"fence.i",
	"mul",
	"mulh",
	"mulhsu",
	"mulhu",
	"div",
	"divu",
	"rem",
	"remu",
	"mulw",
	"divw",
	"divuw",
	"remw",
	"remuw",
	"amoadd.w",
	"amoxor.w",
	"amoor.w",
	"amoand.w",
	"amomin.w",
	"amomax.w",
	"amominu.w",
	"amomaxu.w",
	"amoswap.w",
	"lr.w",
	"sc.w",
	"amoadd.d",
	"amoxor.d",
	"amoor.d",
	"amoand.d",
	"amomin.d",
	"amomax.d",
	"amominu.d",
	"amomaxu.d",
	"amoswap.d",
	"lr.d",
	"sc.d",
	"scall",
	"sbreak",
	"sret",
	"sfence.vm",
	"wfi",
	"mrth",
	"mrts",
	"hrts",
	"csrrw",
	"csrrs",
	"csrrc",
	"csrrwi",
	"csrrsi",
	"csrrci",
	"fadd.s",
	"fsub.s",
	"fmul.s",
	"fdiv.s",
	"fsgnj.s",
	"fsgnjn.s",
	"fsgnjx.s",
	"fmin.s",
	"fmax.s",
	"fsqrt.s",
	"fadd.d",
	"fsub.d",
	"fmul.d",
	"fdiv.d",
	"fsgnj.d",
	"fsgnjn.d",
	"fsgnjx.d",
	"fmin.d",
	"fmax.d",
	"fcvt.s.d",
	"fcvt.d.s",
	"fsqrt.d",
	"fle.s",
	"flt.s",
	"feq.s",
	"fle.d",
	"flt.d",
	"feq.d",
	"fcvt.w.s",
	"fcvt.wu.s",
	"fcvt.l.s",
	"fcvt.lu.s",
	"fmv.x.s",
	"fclass.s",
	"fcvt.w.d",
	"fcvt.wu.d",
	"fcvt.l.d",
	"fcvt.lu.d",
	"fmv.x.d",
	"fclass.d",
	"fcvt.s.w",
	"fcvt.s.wu",
	"fcvt.s.l",
	"fcvt.s.lu",
	"fmv.s.x",
	"fcvt.d.w",
	"fcvt.d.wu",
	"fcvt.d.l",
	"fcvt.d.lu",
	"fmv.d.x",
	"flw",
	"fld",
	"fsw",
	"fsd",
	"fmadd.s",
	"fmsub.s",
	"fnmsub.s",
	"fnmadd.s",
	"fmadd.d",
	"fmsub.d",
	"fnmsub.d",
	"fnmadd.d",
	"c.nop",
	"c.addi",
	"c.lw",
	"c.mv",
	"c.bnez",
	"c.sw",
	"c.ld",
	"c.swsp",
	"c.lwsp",
	"c.li",
	"c.add",
	"c.srli",
	"c.jr",
	"c.fld",
	"c.sdsp",
	"c.j",
	"c.ldsp",
	"c.andi",
	"c.addiw",
	"c.slli",
	"c.sd",
	"c.beqz",
	"c.and",
	"c.srai",
	"c.jal",
	"c.addi4spn",
	"c.fldsp",
	"c.addi16sp",
	"c.fsd",
	"c.fsdsp",
	"c.addw",
	"c.xor",
	"c.or",
	"c.sub",
	"c.lui",
	"c.jalr",
	"c.subw",
	"c.ebreak",
	"c.flw",
	"c.flwsp",
	"c.fsw",
	"c.fswsp"
};

const char* riscv_i_registers[] = {
	"zero",
	"ra",
	"sp",
	"gp",
	"tp",
	"t0",
	"t1",
	"t2",
	"s0",
	"s1",
	"a0",
	"a1",
	"a2",
	"a3",
	"a4",
	"a5",
	"a6", 
	"a7",
	"s2",
	"s3",
	"s4",
	"s5",
	"s6",
	"s7",
	"s8",
	"s9",
	"s10",
	"s11",
	"t3",
	"t4",
	"t5",
	"t6"
};

const char* riscv_f_registers[] = {
	"ft0",
	"ft1",
	"ft2",
	"ft3",
	"ft4",
	"ft5",
	"ft6",
	"ft7",
	"fs0",
	"fs1",
	"fa0",
	"fa1",
	"fa2",
	"fa3",
	"fa4",
	"fa5",
	"fa6",
	"fa7",
	"fs2",
	"fs3",
	"fs4",
	"fs5",
	"fs6",
	"fs7",
	"fs8",
	"fs9",
	"fs10",
	"fs11",
	"ft8",
	"ft9",
	"ft10",
	"ft11"
};

const riscv_inst_comp_metadata riscv_comp_table[] = {
    { riscv_op_c_addi,     riscv_inst_type_ci,            riscv_op_addi,       riscv_inst_type_i },
    { riscv_op_c_lw,       riscv_inst_type_cl_lw,         riscv_op_lw,         riscv_inst_type_i },
    { riscv_op_c_mv,       riscv_inst_type_cr,            riscv_op_addi,       riscv_inst_type_i },
    { riscv_op_c_bnez,     riscv_inst_type_cb,            riscv_op_bne,        riscv_inst_type_sb },
    { riscv_op_c_sw,       riscv_inst_type_cs_sw,         riscv_op_sw,         riscv_inst_type_s },
    { riscv_op_c_ld,       riscv_inst_type_cl_ld,         riscv_op_ld,         riscv_inst_type_i },
    { riscv_op_c_swsp,     riscv_inst_type_css_swsp,      riscv_op_sw,         riscv_inst_type_s },
    { riscv_op_c_lwsp,     riscv_inst_type_ci_lwsp,       riscv_op_lw,         riscv_inst_type_i },
    { riscv_op_c_li,       riscv_inst_type_ci,            riscv_op_addi,       riscv_inst_type_i },
    { riscv_op_c_add,      riscv_inst_type_cr,            riscv_op_add,        riscv_inst_type_r },
    { riscv_op_c_srli,     riscv_inst_type_cb,            riscv_op_srli,       riscv_inst_type_i },
    { riscv_op_c_jr,       riscv_inst_type_cr,            riscv_op_jalr,       riscv_inst_type_i },
    { riscv_op_c_fld,      riscv_inst_type_cl_ld,         riscv_op_fld,        riscv_inst_type_unknown },
    { riscv_op_c_sdsp,     riscv_inst_type_css_sdsp,      riscv_op_sd,         riscv_inst_type_s },
    { riscv_op_c_j,        riscv_inst_type_cj,            riscv_op_jal,        riscv_inst_type_uj },
    { riscv_op_c_ldsp,     riscv_inst_type_ci_ldsp,       riscv_op_ld,         riscv_inst_type_i },
    { riscv_op_c_andi,     riscv_inst_type_cb,            riscv_op_andi,       riscv_inst_type_i },
    { riscv_op_c_addiw,    riscv_inst_type_ci,            riscv_op_addiw,      riscv_inst_type_i },
    { riscv_op_c_slli,     riscv_inst_type_ci,            riscv_op_slli,       riscv_inst_type_i },
    { riscv_op_c_sd,       riscv_inst_type_cs_sd,         riscv_op_sd,         riscv_inst_type_s },
    { riscv_op_c_beqz,     riscv_inst_type_cb,            riscv_op_beq,        riscv_inst_type_sb },
    { riscv_op_c_and,      riscv_inst_type_cs_x,          riscv_op_and,        riscv_inst_type_r },
    { riscv_op_c_srai,     riscv_inst_type_cb,            riscv_op_srai,       riscv_inst_type_i },
    { riscv_op_c_jal,      riscv_inst_type_cj,            riscv_op_jal,        riscv_inst_type_uj },
    { riscv_op_c_addi4spn, riscv_inst_type_ciw_addi4spn,  riscv_op_addi,       riscv_inst_type_i },
    { riscv_op_c_fldsp,    riscv_inst_type_ci_lwsp,       riscv_op_fld,        riscv_inst_type_unknown },
    { riscv_op_c_addi16sp, riscv_inst_type_ci_addi16sp,   riscv_op_addi,       riscv_inst_type_i },
    { riscv_op_c_fsd,      riscv_inst_type_cs_sd,         riscv_op_fsd,        riscv_inst_type_unknown },
    { riscv_op_c_fsdsp,    riscv_inst_type_css_sdsp,      riscv_op_fsd,        riscv_inst_type_unknown },
    { riscv_op_c_addw,     riscv_inst_type_cs_x,          riscv_op_addw,       riscv_inst_type_r },
    { riscv_op_c_xor,      riscv_inst_type_cs_x,          riscv_op_xor,        riscv_inst_type_r },
    { riscv_op_c_or,       riscv_inst_type_cs_x,          riscv_op_or,         riscv_inst_type_r },
    { riscv_op_c_sub,      riscv_inst_type_cs_x,          riscv_op_sub,        riscv_inst_type_r },
    { riscv_op_c_lui,      riscv_inst_type_ci_lui,        riscv_op_lui,        riscv_inst_type_u },
    { riscv_op_c_jalr,     riscv_inst_type_cr,            riscv_op_jalr,       riscv_inst_type_i },
    { riscv_op_c_subw,     riscv_inst_type_cs_x,          riscv_op_subw,       riscv_inst_type_r },
    { riscv_op_c_ebreak,   riscv_inst_type_cr,            riscv_op_unknown,    riscv_inst_type_unknown },
    { riscv_op_c_flw,      riscv_inst_type_cl_lw,         riscv_op_flw,        riscv_inst_type_unknown },
    { riscv_op_c_flwsp,    riscv_inst_type_ci_lwsp,       riscv_op_unknown,    riscv_inst_type_unknown },
    { riscv_op_c_fsw,      riscv_inst_type_cs_sw,         riscv_op_fsw,        riscv_inst_type_unknown },
    { riscv_op_c_fswsp,    riscv_inst_type_css_swsp,      riscv_op_unknown,    riscv_inst_type_unknown },
    { riscv_op_unknown,    riscv_inst_type_unknown,       riscv_op_unknown,    riscv_inst_type_unknown }
};

const riscv_dsm_entry riscv_dsm_table[] = {
/* 0    */{ riscv_dsm_mask_srl0, 3 },
/* 1    */{ riscv_dsm_table_brk, 4 },
/* 2    */{ riscv_dsm_jump, 4 },
/* 3    */{ riscv_dsm_jump, 13 },
/* 4    */{ riscv_dsm_jump, 37 },
/* 5    */{ riscv_dsm_jump, 50 },
/* 6    */{ riscv_dsm_mask_srl13, 7 },
/* 7    */{ riscv_dsm_table_brk, 8 },
/* 8    */{ riscv_dsm_select, riscv_op_c_addi4spn },
/* 9    */{ riscv_dsm_select, riscv_op_c_fld },
/* 10   */{ riscv_dsm_select, riscv_op_c_lw },
/* 11   */{ riscv_dsm_select, riscv_op_c_flw },
/* 12   */{ riscv_dsm_break, 0 },
/* 13   */{ riscv_dsm_select, riscv_op_c_fsd },
/* 14   */{ riscv_dsm_select, riscv_op_c_sw },
/* 15   */{ riscv_dsm_select, riscv_op_c_fsw },
/* 16   */{ riscv_dsm_mask_srl13, 7 },
/* 17   */{ riscv_dsm_table_brk, 8 },
/* 18   */{ riscv_dsm_select, riscv_op_c_addi },
/* 19   */{ riscv_dsm_select, riscv_op_c_jal },
/* 20   */{ riscv_dsm_select, riscv_op_c_li },
/* 21   */{ riscv_dsm_select, riscv_op_c_lui },
/* 22   */{ riscv_dsm_jump, 4 },
/* 23   */{ riscv_dsm_select, riscv_op_c_j },
/* 24   */{ riscv_dsm_select, riscv_op_c_beqz },
/* 25   */{ riscv_dsm_select, riscv_op_c_bnez },
/* 26   */{ riscv_dsm_mask_srl10, 3 },
/* 27   */{ riscv_dsm_table_brk, 4 },
/* 28   */{ riscv_dsm_select, riscv_op_c_srli },
/* 29   */{ riscv_dsm_select, riscv_op_c_srai },
/* 30   */{ riscv_dsm_select, riscv_op_c_andi },
/* 31   */{ riscv_dsm_jump, 1 },
/* 32   */{ riscv_dsm_mask_srl10, 4 },
/* 33   */{ riscv_dsm_mask_srl5, 3 },
/* 34   */{ riscv_dsm_table_brk, 6 },
/* 35   */{ riscv_dsm_select, riscv_op_c_sub },
/* 36   */{ riscv_dsm_select, riscv_op_c_xor },
/* 37   */{ riscv_dsm_select, riscv_op_c_or },
/* 38   */{ riscv_dsm_select, riscv_op_c_and },
/* 39   */{ riscv_dsm_select, riscv_op_c_subw },
/* 40   */{ riscv_dsm_select, riscv_op_c_addw },
/* 41   */{ riscv_dsm_mask_srl13, 7 },
/* 42   */{ riscv_dsm_table_brk, 8 },
/* 43   */{ riscv_dsm_select, riscv_op_c_slli },
/* 44   */{ riscv_dsm_select, riscv_op_c_fldsp },
/* 45   */{ riscv_dsm_select, riscv_op_c_lwsp },
/* 46   */{ riscv_dsm_select, riscv_op_c_flwsp },
/* 47   */{ riscv_dsm_jump, 4 },
/* 48   */{ riscv_dsm_select, riscv_op_c_fsdsp },
/* 49   */{ riscv_dsm_select, riscv_op_c_swsp },
/* 50   */{ riscv_dsm_select, riscv_op_c_fswsp },
/* 51   */{ riscv_dsm_mask_srl12, 1 },
/* 52   */{ riscv_dsm_table_brk, 2 },
/* 53   */{ riscv_dsm_select, riscv_op_c_mv },
/* 54   */{ riscv_dsm_select, riscv_op_c_add },
/* 55   */{ riscv_dsm_mask_srl2, 31 },
/* 56   */{ riscv_dsm_table_brk, 29 },
/* 57   */{ riscv_dsm_jump, 29 },
/* 58   */{ riscv_dsm_jump, 37 },
/* 59   */{ riscv_dsm_break, 0 },
/* 60   */{ riscv_dsm_jump, 41 },
/* 61   */{ riscv_dsm_jump, 44 },
/* 62   */{ riscv_dsm_select, riscv_op_auipc },
/* 63   */{ riscv_dsm_jump, 74 },
/* 64   */{ riscv_dsm_break, 0 },
/* 65   */{ riscv_dsm_jump, 118 },
/* 66   */{ riscv_dsm_jump, 123 },
/* 67   */{ riscv_dsm_break, 0 },
/* 68   */{ riscv_dsm_jump, 127 },
/* 69   */{ riscv_dsm_jump, 363 },
/* 70   */{ riscv_dsm_select, riscv_op_lui },
/* 71   */{ riscv_dsm_jump, 626 },
/* 72   */{ riscv_dsm_break, 0 },
/* 73   */{ riscv_dsm_jump, 889 },
/* 74   */{ riscv_dsm_jump, 892 },
/* 75   */{ riscv_dsm_jump, 895 },
/* 76   */{ riscv_dsm_jump, 898 },
/* 77   */{ riscv_dsm_jump, 901 },
/* 78   */{ riscv_dsm_break, 0 },
/* 79   */{ riscv_dsm_break, 0 },
/* 80   */{ riscv_dsm_break, 0 },
/* 81   */{ riscv_dsm_jump, 1104 },
/* 82   */{ riscv_dsm_jump, 1113 },
/* 83   */{ riscv_dsm_break, 0 },
/* 84   */{ riscv_dsm_select, riscv_op_jal },
/* 85   */{ riscv_dsm_jump, 1113 },
/* 86   */{ riscv_dsm_mask_srl12, 7 },
/* 87   */{ riscv_dsm_table_brk, 7 },
/* 88   */{ riscv_dsm_select, riscv_op_lb },
/* 89   */{ riscv_dsm_select, riscv_op_lh },
/* 90   */{ riscv_dsm_select, riscv_op_lw },
/* 91   */{ riscv_dsm_select, riscv_op_ld },
/* 92   */{ riscv_dsm_select, riscv_op_lbu },
/* 93   */{ riscv_dsm_select, riscv_op_lhu },
/* 94   */{ riscv_dsm_select, riscv_op_lwu },
/* 95   */{ riscv_dsm_mask_srl12, 7 },
/* 96   */{ riscv_dsm_table_brk, 4 },
/* 97   */{ riscv_dsm_break, 0 },
/* 98   */{ riscv_dsm_break, 0 },
/* 99   */{ riscv_dsm_select, riscv_op_flw },
/* 100  */{ riscv_dsm_select, riscv_op_fld },
/* 101  */{ riscv_dsm_mask_srl12, 7 },
/* 102  */{ riscv_dsm_table_brk, 2 },
/* 103  */{ riscv_dsm_select, riscv_op_fence },
/* 104  */{ riscv_dsm_select, riscv_op_fence_i },
/* 105  */{ riscv_dsm_mask_srl12, 7 },
/* 106  */{ riscv_dsm_table_brk, 8 },
/* 107  */{ riscv_dsm_select, riscv_op_addi },
/* 108  */{ riscv_dsm_jump, 7 },
/* 109  */{ riscv_dsm_select, riscv_op_slti },
/* 110  */{ riscv_dsm_select, riscv_op_sltiu },
/* 111  */{ riscv_dsm_select, riscv_op_xori },
/* 112  */{ riscv_dsm_jump, 6 },
/* 113  */{ riscv_dsm_select, riscv_op_ori },
/* 114  */{ riscv_dsm_select, riscv_op_andi },
/* 115  */{ riscv_dsm_mask_srl26, 63 },
/* 116  */{ riscv_dsm_table_brk, 1 },
/* 117  */{ riscv_dsm_select, riscv_op_slli },
/* 118  */{ riscv_dsm_mask_srl26, 63 },
/* 119  */{ riscv_dsm_table_brk, 17 },
/* 120  */{ riscv_dsm_select, riscv_op_srli },
/* 121  */{ riscv_dsm_break, 0 },
/* 122  */{ riscv_dsm_break, 0 },
/* 123  */{ riscv_dsm_break, 0 },
/* 124  */{ riscv_dsm_break, 0 },
/* 125  */{ riscv_dsm_break, 0 },
/* 126  */{ riscv_dsm_break, 0 },
/* 127  */{ riscv_dsm_break, 0 },
/* 128  */{ riscv_dsm_break, 0 },
/* 129  */{ riscv_dsm_break, 0 },
/* 130  */{ riscv_dsm_break, 0 },
/* 131  */{ riscv_dsm_break, 0 },
/* 132  */{ riscv_dsm_break, 0 },
/* 133  */{ riscv_dsm_break, 0 },
/* 134  */{ riscv_dsm_break, 0 },
/* 135  */{ riscv_dsm_break, 0 },
/* 136  */{ riscv_dsm_select, riscv_op_srai },
/* 137  */{ riscv_dsm_mask_srl12, 7 },
/* 138  */{ riscv_dsm_table_brk, 6 },
/* 139  */{ riscv_dsm_select, riscv_op_addiw },
/* 140  */{ riscv_dsm_jump, 5 },
/* 141  */{ riscv_dsm_break, 0 },
/* 142  */{ riscv_dsm_break, 0 },
/* 143  */{ riscv_dsm_break, 0 },
/* 144  */{ riscv_dsm_jump, 4 },
/* 145  */{ riscv_dsm_mask_srl25, 127 },
/* 146  */{ riscv_dsm_table_brk, 1 },
/* 147  */{ riscv_dsm_select, riscv_op_slliw },
/* 148  */{ riscv_dsm_mask_srl25, 127 },
/* 149  */{ riscv_dsm_table_brk, 33 },
/* 150  */{ riscv_dsm_select, riscv_op_srliw },
/* 151  */{ riscv_dsm_break, 0 },
/* 152  */{ riscv_dsm_break, 0 },
/* 153  */{ riscv_dsm_break, 0 },
/* 154  */{ riscv_dsm_break, 0 },
/* 155  */{ riscv_dsm_break, 0 },
/* 156  */{ riscv_dsm_break, 0 },
/* 157  */{ riscv_dsm_break, 0 },
/* 158  */{ riscv_dsm_break, 0 },
/* 159  */{ riscv_dsm_break, 0 },
/* 160  */{ riscv_dsm_break, 0 },
/* 161  */{ riscv_dsm_break, 0 },
/* 162  */{ riscv_dsm_break, 0 },
/* 163  */{ riscv_dsm_break, 0 },
/* 164  */{ riscv_dsm_break, 0 },
/* 165  */{ riscv_dsm_break, 0 },
/* 166  */{ riscv_dsm_break, 0 },
/* 167  */{ riscv_dsm_break, 0 },
/* 168  */{ riscv_dsm_break, 0 },
/* 169  */{ riscv_dsm_break, 0 },
/* 170  */{ riscv_dsm_break, 0 },
/* 171  */{ riscv_dsm_break, 0 },
/* 172  */{ riscv_dsm_break, 0 },
/* 173  */{ riscv_dsm_break, 0 },
/* 174  */{ riscv_dsm_break, 0 },
/* 175  */{ riscv_dsm_break, 0 },
/* 176  */{ riscv_dsm_break, 0 },
/* 177  */{ riscv_dsm_break, 0 },
/* 178  */{ riscv_dsm_break, 0 },
/* 179  */{ riscv_dsm_break, 0 },
/* 180  */{ riscv_dsm_break, 0 },
/* 181  */{ riscv_dsm_break, 0 },
/* 182  */{ riscv_dsm_select, riscv_op_sraiw },
/* 183  */{ riscv_dsm_mask_srl12, 7 },
/* 184  */{ riscv_dsm_table_brk, 4 },
/* 185  */{ riscv_dsm_select, riscv_op_sb },
/* 186  */{ riscv_dsm_select, riscv_op_sh },
/* 187  */{ riscv_dsm_select, riscv_op_sw },
/* 188  */{ riscv_dsm_select, riscv_op_sd },
/* 189  */{ riscv_dsm_mask_srl12, 7 },
/* 190  */{ riscv_dsm_table_brk, 4 },
/* 191  */{ riscv_dsm_break, 0 },
/* 192  */{ riscv_dsm_break, 0 },
/* 193  */{ riscv_dsm_select, riscv_op_fsw },
/* 194  */{ riscv_dsm_select, riscv_op_fsd },
/* 195  */{ riscv_dsm_mask_srl24, 248 },
/* 196  */{ riscv_dsm_mask_srl12, 7 },
/* 197  */{ riscv_dsm_table_brk, 228 },
/* 198  */{ riscv_dsm_break, 0 },
/* 199  */{ riscv_dsm_break, 0 },
/* 200  */{ riscv_dsm_select, riscv_op_amoadd_w },
/* 201  */{ riscv_dsm_select, riscv_op_amoadd_d },
/* 202  */{ riscv_dsm_break, 0 },
/* 203  */{ riscv_dsm_break, 0 },
/* 204  */{ riscv_dsm_break, 0 },
/* 205  */{ riscv_dsm_break, 0 },
/* 206  */{ riscv_dsm_break, 0 },
/* 207  */{ riscv_dsm_break, 0 },
/* 208  */{ riscv_dsm_select, riscv_op_amoswap_w },
/* 209  */{ riscv_dsm_select, riscv_op_amoswap_d },
/* 210  */{ riscv_dsm_break, 0 },
/* 211  */{ riscv_dsm_break, 0 },
/* 212  */{ riscv_dsm_break, 0 },
/* 213  */{ riscv_dsm_break, 0 },
/* 214  */{ riscv_dsm_break, 0 },
/* 215  */{ riscv_dsm_break, 0 },
/* 216  */{ riscv_dsm_jump, 210 },
/* 217  */{ riscv_dsm_jump, 212 },
/* 218  */{ riscv_dsm_break, 0 },
/* 219  */{ riscv_dsm_break, 0 },
/* 220  */{ riscv_dsm_break, 0 },
/* 221  */{ riscv_dsm_break, 0 },
/* 222  */{ riscv_dsm_break, 0 },
/* 223  */{ riscv_dsm_break, 0 },
/* 224  */{ riscv_dsm_select, riscv_op_sc_w },
/* 225  */{ riscv_dsm_select, riscv_op_sc_d },
/* 226  */{ riscv_dsm_break, 0 },
/* 227  */{ riscv_dsm_break, 0 },
/* 228  */{ riscv_dsm_break, 0 },
/* 229  */{ riscv_dsm_break, 0 },
/* 230  */{ riscv_dsm_break, 0 },
/* 231  */{ riscv_dsm_break, 0 },
/* 232  */{ riscv_dsm_select, riscv_op_amoxor_w },
/* 233  */{ riscv_dsm_select, riscv_op_amoxor_d },
/* 234  */{ riscv_dsm_break, 0 },
/* 235  */{ riscv_dsm_break, 0 },
/* 236  */{ riscv_dsm_break, 0 },
/* 237  */{ riscv_dsm_break, 0 },
/* 238  */{ riscv_dsm_break, 0 },
/* 239  */{ riscv_dsm_break, 0 },
/* 240  */{ riscv_dsm_break, 0 },
/* 241  */{ riscv_dsm_break, 0 },
/* 242  */{ riscv_dsm_break, 0 },
/* 243  */{ riscv_dsm_break, 0 },
/* 244  */{ riscv_dsm_break, 0 },
/* 245  */{ riscv_dsm_break, 0 },
/* 246  */{ riscv_dsm_break, 0 },
/* 247  */{ riscv_dsm_break, 0 },
/* 248  */{ riscv_dsm_break, 0 },
/* 249  */{ riscv_dsm_break, 0 },
/* 250  */{ riscv_dsm_break, 0 },
/* 251  */{ riscv_dsm_break, 0 },
/* 252  */{ riscv_dsm_break, 0 },
/* 253  */{ riscv_dsm_break, 0 },
/* 254  */{ riscv_dsm_break, 0 },
/* 255  */{ riscv_dsm_break, 0 },
/* 256  */{ riscv_dsm_break, 0 },
/* 257  */{ riscv_dsm_break, 0 },
/* 258  */{ riscv_dsm_break, 0 },
/* 259  */{ riscv_dsm_break, 0 },
/* 260  */{ riscv_dsm_break, 0 },
/* 261  */{ riscv_dsm_break, 0 },
/* 262  */{ riscv_dsm_break, 0 },
/* 263  */{ riscv_dsm_break, 0 },
/* 264  */{ riscv_dsm_select, riscv_op_amoor_w },
/* 265  */{ riscv_dsm_select, riscv_op_amoor_d },
/* 266  */{ riscv_dsm_break, 0 },
/* 267  */{ riscv_dsm_break, 0 },
/* 268  */{ riscv_dsm_break, 0 },
/* 269  */{ riscv_dsm_break, 0 },
/* 270  */{ riscv_dsm_break, 0 },
/* 271  */{ riscv_dsm_break, 0 },
/* 272  */{ riscv_dsm_break, 0 },
/* 273  */{ riscv_dsm_break, 0 },
/* 274  */{ riscv_dsm_break, 0 },
/* 275  */{ riscv_dsm_break, 0 },
/* 276  */{ riscv_dsm_break, 0 },
/* 277  */{ riscv_dsm_break, 0 },
/* 278  */{ riscv_dsm_break, 0 },
/* 279  */{ riscv_dsm_break, 0 },
/* 280  */{ riscv_dsm_break, 0 },
/* 281  */{ riscv_dsm_break, 0 },
/* 282  */{ riscv_dsm_break, 0 },
/* 283  */{ riscv_dsm_break, 0 },
/* 284  */{ riscv_dsm_break, 0 },
/* 285  */{ riscv_dsm_break, 0 },
/* 286  */{ riscv_dsm_break, 0 },
/* 287  */{ riscv_dsm_break, 0 },
/* 288  */{ riscv_dsm_break, 0 },
/* 289  */{ riscv_dsm_break, 0 },
/* 290  */{ riscv_dsm_break, 0 },
/* 291  */{ riscv_dsm_break, 0 },
/* 292  */{ riscv_dsm_break, 0 },
/* 293  */{ riscv_dsm_break, 0 },
/* 294  */{ riscv_dsm_break, 0 },
/* 295  */{ riscv_dsm_break, 0 },
/* 296  */{ riscv_dsm_select, riscv_op_amoand_w },
/* 297  */{ riscv_dsm_select, riscv_op_amoand_d },
/* 298  */{ riscv_dsm_break, 0 },
/* 299  */{ riscv_dsm_break, 0 },
/* 300  */{ riscv_dsm_break, 0 },
/* 301  */{ riscv_dsm_break, 0 },
/* 302  */{ riscv_dsm_break, 0 },
/* 303  */{ riscv_dsm_break, 0 },
/* 304  */{ riscv_dsm_break, 0 },
/* 305  */{ riscv_dsm_break, 0 },
/* 306  */{ riscv_dsm_break, 0 },
/* 307  */{ riscv_dsm_break, 0 },
/* 308  */{ riscv_dsm_break, 0 },
/* 309  */{ riscv_dsm_break, 0 },
/* 310  */{ riscv_dsm_break, 0 },
/* 311  */{ riscv_dsm_break, 0 },
/* 312  */{ riscv_dsm_break, 0 },
/* 313  */{ riscv_dsm_break, 0 },
/* 314  */{ riscv_dsm_break, 0 },
/* 315  */{ riscv_dsm_break, 0 },
/* 316  */{ riscv_dsm_break, 0 },
/* 317  */{ riscv_dsm_break, 0 },
/* 318  */{ riscv_dsm_break, 0 },
/* 319  */{ riscv_dsm_break, 0 },
/* 320  */{ riscv_dsm_break, 0 },
/* 321  */{ riscv_dsm_break, 0 },
/* 322  */{ riscv_dsm_break, 0 },
/* 323  */{ riscv_dsm_break, 0 },
/* 324  */{ riscv_dsm_break, 0 },
/* 325  */{ riscv_dsm_break, 0 },
/* 326  */{ riscv_dsm_break, 0 },
/* 327  */{ riscv_dsm_break, 0 },
/* 328  */{ riscv_dsm_select, riscv_op_amomin_w },
/* 329  */{ riscv_dsm_select, riscv_op_amomin_d },
/* 330  */{ riscv_dsm_break, 0 },
/* 331  */{ riscv_dsm_break, 0 },
/* 332  */{ riscv_dsm_break, 0 },
/* 333  */{ riscv_dsm_break, 0 },
/* 334  */{ riscv_dsm_break, 0 },
/* 335  */{ riscv_dsm_break, 0 },
/* 336  */{ riscv_dsm_break, 0 },
/* 337  */{ riscv_dsm_break, 0 },
/* 338  */{ riscv_dsm_break, 0 },
/* 339  */{ riscv_dsm_break, 0 },
/* 340  */{ riscv_dsm_break, 0 },
/* 341  */{ riscv_dsm_break, 0 },
/* 342  */{ riscv_dsm_break, 0 },
/* 343  */{ riscv_dsm_break, 0 },
/* 344  */{ riscv_dsm_break, 0 },
/* 345  */{ riscv_dsm_break, 0 },
/* 346  */{ riscv_dsm_break, 0 },
/* 347  */{ riscv_dsm_break, 0 },
/* 348  */{ riscv_dsm_break, 0 },
/* 349  */{ riscv_dsm_break, 0 },
/* 350  */{ riscv_dsm_break, 0 },
/* 351  */{ riscv_dsm_break, 0 },
/* 352  */{ riscv_dsm_break, 0 },
/* 353  */{ riscv_dsm_break, 0 },
/* 354  */{ riscv_dsm_break, 0 },
/* 355  */{ riscv_dsm_break, 0 },
/* 356  */{ riscv_dsm_break, 0 },
/* 357  */{ riscv_dsm_break, 0 },
/* 358  */{ riscv_dsm_break, 0 },
/* 359  */{ riscv_dsm_break, 0 },
/* 360  */{ riscv_dsm_select, riscv_op_amomax_w },
/* 361  */{ riscv_dsm_select, riscv_op_amomax_d },
/* 362  */{ riscv_dsm_break, 0 },
/* 363  */{ riscv_dsm_break, 0 },
/* 364  */{ riscv_dsm_break, 0 },
/* 365  */{ riscv_dsm_break, 0 },
/* 366  */{ riscv_dsm_break, 0 },
/* 367  */{ riscv_dsm_break, 0 },
/* 368  */{ riscv_dsm_break, 0 },
/* 369  */{ riscv_dsm_break, 0 },
/* 370  */{ riscv_dsm_break, 0 },
/* 371  */{ riscv_dsm_break, 0 },
/* 372  */{ riscv_dsm_break, 0 },
/* 373  */{ riscv_dsm_break, 0 },
/* 374  */{ riscv_dsm_break, 0 },
/* 375  */{ riscv_dsm_break, 0 },
/* 376  */{ riscv_dsm_break, 0 },
/* 377  */{ riscv_dsm_break, 0 },
/* 378  */{ riscv_dsm_break, 0 },
/* 379  */{ riscv_dsm_break, 0 },
/* 380  */{ riscv_dsm_break, 0 },
/* 381  */{ riscv_dsm_break, 0 },
/* 382  */{ riscv_dsm_break, 0 },
/* 383  */{ riscv_dsm_break, 0 },
/* 384  */{ riscv_dsm_break, 0 },
/* 385  */{ riscv_dsm_break, 0 },
/* 386  */{ riscv_dsm_break, 0 },
/* 387  */{ riscv_dsm_break, 0 },
/* 388  */{ riscv_dsm_break, 0 },
/* 389  */{ riscv_dsm_break, 0 },
/* 390  */{ riscv_dsm_break, 0 },
/* 391  */{ riscv_dsm_break, 0 },
/* 392  */{ riscv_dsm_select, riscv_op_amominu_w },
/* 393  */{ riscv_dsm_select, riscv_op_amominu_d },
/* 394  */{ riscv_dsm_break, 0 },
/* 395  */{ riscv_dsm_break, 0 },
/* 396  */{ riscv_dsm_break, 0 },
/* 397  */{ riscv_dsm_break, 0 },
/* 398  */{ riscv_dsm_break, 0 },
/* 399  */{ riscv_dsm_break, 0 },
/* 400  */{ riscv_dsm_break, 0 },
/* 401  */{ riscv_dsm_break, 0 },
/* 402  */{ riscv_dsm_break, 0 },
/* 403  */{ riscv_dsm_break, 0 },
/* 404  */{ riscv_dsm_break, 0 },
/* 405  */{ riscv_dsm_break, 0 },
/* 406  */{ riscv_dsm_break, 0 },
/* 407  */{ riscv_dsm_break, 0 },
/* 408  */{ riscv_dsm_break, 0 },
/* 409  */{ riscv_dsm_break, 0 },
/* 410  */{ riscv_dsm_break, 0 },
/* 411  */{ riscv_dsm_break, 0 },
/* 412  */{ riscv_dsm_break, 0 },
/* 413  */{ riscv_dsm_break, 0 },
/* 414  */{ riscv_dsm_break, 0 },
/* 415  */{ riscv_dsm_break, 0 },
/* 416  */{ riscv_dsm_break, 0 },
/* 417  */{ riscv_dsm_break, 0 },
/* 418  */{ riscv_dsm_break, 0 },
/* 419  */{ riscv_dsm_break, 0 },
/* 420  */{ riscv_dsm_break, 0 },
/* 421  */{ riscv_dsm_break, 0 },
/* 422  */{ riscv_dsm_break, 0 },
/* 423  */{ riscv_dsm_break, 0 },
/* 424  */{ riscv_dsm_select, riscv_op_amomaxu_w },
/* 425  */{ riscv_dsm_select, riscv_op_amomaxu_d },
/* 426  */{ riscv_dsm_mask_srl20, 31 },
/* 427  */{ riscv_dsm_table_brk, 1 },
/* 428  */{ riscv_dsm_select, riscv_op_lr_w },
/* 429  */{ riscv_dsm_mask_srl20, 31 },
/* 430  */{ riscv_dsm_table_brk, 1 },
/* 431  */{ riscv_dsm_select, riscv_op_lr_d },
/* 432  */{ riscv_dsm_mask_srl22, 1016 },
/* 433  */{ riscv_dsm_mask_srl12, 7 },
/* 434  */{ riscv_dsm_table_brk, 262 },
/* 435  */{ riscv_dsm_select, riscv_op_add },
/* 436  */{ riscv_dsm_select, riscv_op_sll },
/* 437  */{ riscv_dsm_select, riscv_op_slt },
/* 438  */{ riscv_dsm_select, riscv_op_sltu },
/* 439  */{ riscv_dsm_select, riscv_op_xor },
/* 440  */{ riscv_dsm_select, riscv_op_srl },
/* 441  */{ riscv_dsm_select, riscv_op_or },
/* 442  */{ riscv_dsm_select, riscv_op_and },
/* 443  */{ riscv_dsm_select, riscv_op_mul },
/* 444  */{ riscv_dsm_select, riscv_op_mulh },
/* 445  */{ riscv_dsm_select, riscv_op_mulhsu },
/* 446  */{ riscv_dsm_select, riscv_op_mulhu },
/* 447  */{ riscv_dsm_select, riscv_op_div },
/* 448  */{ riscv_dsm_select, riscv_op_divu },
/* 449  */{ riscv_dsm_select, riscv_op_rem },
/* 450  */{ riscv_dsm_select, riscv_op_remu },
/* 451  */{ riscv_dsm_break, 0 },
/* 452  */{ riscv_dsm_break, 0 },
/* 453  */{ riscv_dsm_break, 0 },
/* 454  */{ riscv_dsm_break, 0 },
/* 455  */{ riscv_dsm_break, 0 },
/* 456  */{ riscv_dsm_break, 0 },
/* 457  */{ riscv_dsm_break, 0 },
/* 458  */{ riscv_dsm_break, 0 },
/* 459  */{ riscv_dsm_break, 0 },
/* 460  */{ riscv_dsm_break, 0 },
/* 461  */{ riscv_dsm_break, 0 },
/* 462  */{ riscv_dsm_break, 0 },
/* 463  */{ riscv_dsm_break, 0 },
/* 464  */{ riscv_dsm_break, 0 },
/* 465  */{ riscv_dsm_break, 0 },
/* 466  */{ riscv_dsm_break, 0 },
/* 467  */{ riscv_dsm_break, 0 },
/* 468  */{ riscv_dsm_break, 0 },
/* 469  */{ riscv_dsm_break, 0 },
/* 470  */{ riscv_dsm_break, 0 },
/* 471  */{ riscv_dsm_break, 0 },
/* 472  */{ riscv_dsm_break, 0 },
/* 473  */{ riscv_dsm_break, 0 },
/* 474  */{ riscv_dsm_break, 0 },
/* 475  */{ riscv_dsm_break, 0 },
/* 476  */{ riscv_dsm_break, 0 },
/* 477  */{ riscv_dsm_break, 0 },
/* 478  */{ riscv_dsm_break, 0 },
/* 479  */{ riscv_dsm_break, 0 },
/* 480  */{ riscv_dsm_break, 0 },
/* 481  */{ riscv_dsm_break, 0 },
/* 482  */{ riscv_dsm_break, 0 },
/* 483  */{ riscv_dsm_break, 0 },
/* 484  */{ riscv_dsm_break, 0 },
/* 485  */{ riscv_dsm_break, 0 },
/* 486  */{ riscv_dsm_break, 0 },
/* 487  */{ riscv_dsm_break, 0 },
/* 488  */{ riscv_dsm_break, 0 },
/* 489  */{ riscv_dsm_break, 0 },
/* 490  */{ riscv_dsm_break, 0 },
/* 491  */{ riscv_dsm_break, 0 },
/* 492  */{ riscv_dsm_break, 0 },
/* 493  */{ riscv_dsm_break, 0 },
/* 494  */{ riscv_dsm_break, 0 },
/* 495  */{ riscv_dsm_break, 0 },
/* 496  */{ riscv_dsm_break, 0 },
/* 497  */{ riscv_dsm_break, 0 },
/* 498  */{ riscv_dsm_break, 0 },
/* 499  */{ riscv_dsm_break, 0 },
/* 500  */{ riscv_dsm_break, 0 },
/* 501  */{ riscv_dsm_break, 0 },
/* 502  */{ riscv_dsm_break, 0 },
/* 503  */{ riscv_dsm_break, 0 },
/* 504  */{ riscv_dsm_break, 0 },
/* 505  */{ riscv_dsm_break, 0 },
/* 506  */{ riscv_dsm_break, 0 },
/* 507  */{ riscv_dsm_break, 0 },
/* 508  */{ riscv_dsm_break, 0 },
/* 509  */{ riscv_dsm_break, 0 },
/* 510  */{ riscv_dsm_break, 0 },
/* 511  */{ riscv_dsm_break, 0 },
/* 512  */{ riscv_dsm_break, 0 },
/* 513  */{ riscv_dsm_break, 0 },
/* 514  */{ riscv_dsm_break, 0 },
/* 515  */{ riscv_dsm_break, 0 },
/* 516  */{ riscv_dsm_break, 0 },
/* 517  */{ riscv_dsm_break, 0 },
/* 518  */{ riscv_dsm_break, 0 },
/* 519  */{ riscv_dsm_break, 0 },
/* 520  */{ riscv_dsm_break, 0 },
/* 521  */{ riscv_dsm_break, 0 },
/* 522  */{ riscv_dsm_break, 0 },
/* 523  */{ riscv_dsm_break, 0 },
/* 524  */{ riscv_dsm_break, 0 },
/* 525  */{ riscv_dsm_break, 0 },
/* 526  */{ riscv_dsm_break, 0 },
/* 527  */{ riscv_dsm_break, 0 },
/* 528  */{ riscv_dsm_break, 0 },
/* 529  */{ riscv_dsm_break, 0 },
/* 530  */{ riscv_dsm_break, 0 },
/* 531  */{ riscv_dsm_break, 0 },
/* 532  */{ riscv_dsm_break, 0 },
/* 533  */{ riscv_dsm_break, 0 },
/* 534  */{ riscv_dsm_break, 0 },
/* 535  */{ riscv_dsm_break, 0 },
/* 536  */{ riscv_dsm_break, 0 },
/* 537  */{ riscv_dsm_break, 0 },
/* 538  */{ riscv_dsm_break, 0 },
/* 539  */{ riscv_dsm_break, 0 },
/* 540  */{ riscv_dsm_break, 0 },
/* 541  */{ riscv_dsm_break, 0 },
/* 542  */{ riscv_dsm_break, 0 },
/* 543  */{ riscv_dsm_break, 0 },
/* 544  */{ riscv_dsm_break, 0 },
/* 545  */{ riscv_dsm_break, 0 },
/* 546  */{ riscv_dsm_break, 0 },
/* 547  */{ riscv_dsm_break, 0 },
/* 548  */{ riscv_dsm_break, 0 },
/* 549  */{ riscv_dsm_break, 0 },
/* 550  */{ riscv_dsm_break, 0 },
/* 551  */{ riscv_dsm_break, 0 },
/* 552  */{ riscv_dsm_break, 0 },
/* 553  */{ riscv_dsm_break, 0 },
/* 554  */{ riscv_dsm_break, 0 },
/* 555  */{ riscv_dsm_break, 0 },
/* 556  */{ riscv_dsm_break, 0 },
/* 557  */{ riscv_dsm_break, 0 },
/* 558  */{ riscv_dsm_break, 0 },
/* 559  */{ riscv_dsm_break, 0 },
/* 560  */{ riscv_dsm_break, 0 },
/* 561  */{ riscv_dsm_break, 0 },
/* 562  */{ riscv_dsm_break, 0 },
/* 563  */{ riscv_dsm_break, 0 },
/* 564  */{ riscv_dsm_break, 0 },
/* 565  */{ riscv_dsm_break, 0 },
/* 566  */{ riscv_dsm_break, 0 },
/* 567  */{ riscv_dsm_break, 0 },
/* 568  */{ riscv_dsm_break, 0 },
/* 569  */{ riscv_dsm_break, 0 },
/* 570  */{ riscv_dsm_break, 0 },
/* 571  */{ riscv_dsm_break, 0 },
/* 572  */{ riscv_dsm_break, 0 },
/* 573  */{ riscv_dsm_break, 0 },
/* 574  */{ riscv_dsm_break, 0 },
/* 575  */{ riscv_dsm_break, 0 },
/* 576  */{ riscv_dsm_break, 0 },
/* 577  */{ riscv_dsm_break, 0 },
/* 578  */{ riscv_dsm_break, 0 },
/* 579  */{ riscv_dsm_break, 0 },
/* 580  */{ riscv_dsm_break, 0 },
/* 581  */{ riscv_dsm_break, 0 },
/* 582  */{ riscv_dsm_break, 0 },
/* 583  */{ riscv_dsm_break, 0 },
/* 584  */{ riscv_dsm_break, 0 },
/* 585  */{ riscv_dsm_break, 0 },
/* 586  */{ riscv_dsm_break, 0 },
/* 587  */{ riscv_dsm_break, 0 },
/* 588  */{ riscv_dsm_break, 0 },
/* 589  */{ riscv_dsm_break, 0 },
/* 590  */{ riscv_dsm_break, 0 },
/* 591  */{ riscv_dsm_break, 0 },
/* 592  */{ riscv_dsm_break, 0 },
/* 593  */{ riscv_dsm_break, 0 },
/* 594  */{ riscv_dsm_break, 0 },
/* 595  */{ riscv_dsm_break, 0 },
/* 596  */{ riscv_dsm_break, 0 },
/* 597  */{ riscv_dsm_break, 0 },
/* 598  */{ riscv_dsm_break, 0 },
/* 599  */{ riscv_dsm_break, 0 },
/* 600  */{ riscv_dsm_break, 0 },
/* 601  */{ riscv_dsm_break, 0 },
/* 602  */{ riscv_dsm_break, 0 },
/* 603  */{ riscv_dsm_break, 0 },
/* 604  */{ riscv_dsm_break, 0 },
/* 605  */{ riscv_dsm_break, 0 },
/* 606  */{ riscv_dsm_break, 0 },
/* 607  */{ riscv_dsm_break, 0 },
/* 608  */{ riscv_dsm_break, 0 },
/* 609  */{ riscv_dsm_break, 0 },
/* 610  */{ riscv_dsm_break, 0 },
/* 611  */{ riscv_dsm_break, 0 },
/* 612  */{ riscv_dsm_break, 0 },
/* 613  */{ riscv_dsm_break, 0 },
/* 614  */{ riscv_dsm_break, 0 },
/* 615  */{ riscv_dsm_break, 0 },
/* 616  */{ riscv_dsm_break, 0 },
/* 617  */{ riscv_dsm_break, 0 },
/* 618  */{ riscv_dsm_break, 0 },
/* 619  */{ riscv_dsm_break, 0 },
/* 620  */{ riscv_dsm_break, 0 },
/* 621  */{ riscv_dsm_break, 0 },
/* 622  */{ riscv_dsm_break, 0 },
/* 623  */{ riscv_dsm_break, 0 },
/* 624  */{ riscv_dsm_break, 0 },
/* 625  */{ riscv_dsm_break, 0 },
/* 626  */{ riscv_dsm_break, 0 },
/* 627  */{ riscv_dsm_break, 0 },
/* 628  */{ riscv_dsm_break, 0 },
/* 629  */{ riscv_dsm_break, 0 },
/* 630  */{ riscv_dsm_break, 0 },
/* 631  */{ riscv_dsm_break, 0 },
/* 632  */{ riscv_dsm_break, 0 },
/* 633  */{ riscv_dsm_break, 0 },
/* 634  */{ riscv_dsm_break, 0 },
/* 635  */{ riscv_dsm_break, 0 },
/* 636  */{ riscv_dsm_break, 0 },
/* 637  */{ riscv_dsm_break, 0 },
/* 638  */{ riscv_dsm_break, 0 },
/* 639  */{ riscv_dsm_break, 0 },
/* 640  */{ riscv_dsm_break, 0 },
/* 641  */{ riscv_dsm_break, 0 },
/* 642  */{ riscv_dsm_break, 0 },
/* 643  */{ riscv_dsm_break, 0 },
/* 644  */{ riscv_dsm_break, 0 },
/* 645  */{ riscv_dsm_break, 0 },
/* 646  */{ riscv_dsm_break, 0 },
/* 647  */{ riscv_dsm_break, 0 },
/* 648  */{ riscv_dsm_break, 0 },
/* 649  */{ riscv_dsm_break, 0 },
/* 650  */{ riscv_dsm_break, 0 },
/* 651  */{ riscv_dsm_break, 0 },
/* 652  */{ riscv_dsm_break, 0 },
/* 653  */{ riscv_dsm_break, 0 },
/* 654  */{ riscv_dsm_break, 0 },
/* 655  */{ riscv_dsm_break, 0 },
/* 656  */{ riscv_dsm_break, 0 },
/* 657  */{ riscv_dsm_break, 0 },
/* 658  */{ riscv_dsm_break, 0 },
/* 659  */{ riscv_dsm_break, 0 },
/* 660  */{ riscv_dsm_break, 0 },
/* 661  */{ riscv_dsm_break, 0 },
/* 662  */{ riscv_dsm_break, 0 },
/* 663  */{ riscv_dsm_break, 0 },
/* 664  */{ riscv_dsm_break, 0 },
/* 665  */{ riscv_dsm_break, 0 },
/* 666  */{ riscv_dsm_break, 0 },
/* 667  */{ riscv_dsm_break, 0 },
/* 668  */{ riscv_dsm_break, 0 },
/* 669  */{ riscv_dsm_break, 0 },
/* 670  */{ riscv_dsm_break, 0 },
/* 671  */{ riscv_dsm_break, 0 },
/* 672  */{ riscv_dsm_break, 0 },
/* 673  */{ riscv_dsm_break, 0 },
/* 674  */{ riscv_dsm_break, 0 },
/* 675  */{ riscv_dsm_break, 0 },
/* 676  */{ riscv_dsm_break, 0 },
/* 677  */{ riscv_dsm_break, 0 },
/* 678  */{ riscv_dsm_break, 0 },
/* 679  */{ riscv_dsm_break, 0 },
/* 680  */{ riscv_dsm_break, 0 },
/* 681  */{ riscv_dsm_break, 0 },
/* 682  */{ riscv_dsm_break, 0 },
/* 683  */{ riscv_dsm_break, 0 },
/* 684  */{ riscv_dsm_break, 0 },
/* 685  */{ riscv_dsm_break, 0 },
/* 686  */{ riscv_dsm_break, 0 },
/* 687  */{ riscv_dsm_break, 0 },
/* 688  */{ riscv_dsm_break, 0 },
/* 689  */{ riscv_dsm_break, 0 },
/* 690  */{ riscv_dsm_break, 0 },
/* 691  */{ riscv_dsm_select, riscv_op_sub },
/* 692  */{ riscv_dsm_break, 0 },
/* 693  */{ riscv_dsm_break, 0 },
/* 694  */{ riscv_dsm_break, 0 },
/* 695  */{ riscv_dsm_break, 0 },
/* 696  */{ riscv_dsm_select, riscv_op_sra },
/* 697  */{ riscv_dsm_mask_srl22, 1016 },
/* 698  */{ riscv_dsm_mask_srl12, 7 },
/* 699  */{ riscv_dsm_table_brk, 262 },
/* 700  */{ riscv_dsm_select, riscv_op_addw },
/* 701  */{ riscv_dsm_select, riscv_op_sllw },
/* 702  */{ riscv_dsm_break, 0 },
/* 703  */{ riscv_dsm_break, 0 },
/* 704  */{ riscv_dsm_break, 0 },
/* 705  */{ riscv_dsm_select, riscv_op_srlw },
/* 706  */{ riscv_dsm_break, 0 },
/* 707  */{ riscv_dsm_break, 0 },
/* 708  */{ riscv_dsm_select, riscv_op_mulw },
/* 709  */{ riscv_dsm_break, 0 },
/* 710  */{ riscv_dsm_break, 0 },
/* 711  */{ riscv_dsm_break, 0 },
/* 712  */{ riscv_dsm_select, riscv_op_divw },
/* 713  */{ riscv_dsm_select, riscv_op_divuw },
/* 714  */{ riscv_dsm_select, riscv_op_remw },
/* 715  */{ riscv_dsm_select, riscv_op_remuw },
/* 716  */{ riscv_dsm_break, 0 },
/* 717  */{ riscv_dsm_break, 0 },
/* 718  */{ riscv_dsm_break, 0 },
/* 719  */{ riscv_dsm_break, 0 },
/* 720  */{ riscv_dsm_break, 0 },
/* 721  */{ riscv_dsm_break, 0 },
/* 722  */{ riscv_dsm_break, 0 },
/* 723  */{ riscv_dsm_break, 0 },
/* 724  */{ riscv_dsm_break, 0 },
/* 725  */{ riscv_dsm_break, 0 },
/* 726  */{ riscv_dsm_break, 0 },
/* 727  */{ riscv_dsm_break, 0 },
/* 728  */{ riscv_dsm_break, 0 },
/* 729  */{ riscv_dsm_break, 0 },
/* 730  */{ riscv_dsm_break, 0 },
/* 731  */{ riscv_dsm_break, 0 },
/* 732  */{ riscv_dsm_break, 0 },
/* 733  */{ riscv_dsm_break, 0 },
/* 734  */{ riscv_dsm_break, 0 },
/* 735  */{ riscv_dsm_break, 0 },
/* 736  */{ riscv_dsm_break, 0 },
/* 737  */{ riscv_dsm_break, 0 },
/* 738  */{ riscv_dsm_break, 0 },
/* 739  */{ riscv_dsm_break, 0 },
/* 740  */{ riscv_dsm_break, 0 },
/* 741  */{ riscv_dsm_break, 0 },
/* 742  */{ riscv_dsm_break, 0 },
/* 743  */{ riscv_dsm_break, 0 },
/* 744  */{ riscv_dsm_break, 0 },
/* 745  */{ riscv_dsm_break, 0 },
/* 746  */{ riscv_dsm_break, 0 },
/* 747  */{ riscv_dsm_break, 0 },
/* 748  */{ riscv_dsm_break, 0 },
/* 749  */{ riscv_dsm_break, 0 },
/* 750  */{ riscv_dsm_break, 0 },
/* 751  */{ riscv_dsm_break, 0 },
/* 752  */{ riscv_dsm_break, 0 },
/* 753  */{ riscv_dsm_break, 0 },
/* 754  */{ riscv_dsm_break, 0 },
/* 755  */{ riscv_dsm_break, 0 },
/* 756  */{ riscv_dsm_break, 0 },
/* 757  */{ riscv_dsm_break, 0 },
/* 758  */{ riscv_dsm_break, 0 },
/* 759  */{ riscv_dsm_break, 0 },
/* 760  */{ riscv_dsm_break, 0 },
/* 761  */{ riscv_dsm_break, 0 },
/* 762  */{ riscv_dsm_break, 0 },
/* 763  */{ riscv_dsm_break, 0 },
/* 764  */{ riscv_dsm_break, 0 },
/* 765  */{ riscv_dsm_break, 0 },
/* 766  */{ riscv_dsm_break, 0 },
/* 767  */{ riscv_dsm_break, 0 },
/* 768  */{ riscv_dsm_break, 0 },
/* 769  */{ riscv_dsm_break, 0 },
/* 770  */{ riscv_dsm_break, 0 },
/* 771  */{ riscv_dsm_break, 0 },
/* 772  */{ riscv_dsm_break, 0 },
/* 773  */{ riscv_dsm_break, 0 },
/* 774  */{ riscv_dsm_break, 0 },
/* 775  */{ riscv_dsm_break, 0 },
/* 776  */{ riscv_dsm_break, 0 },
/* 777  */{ riscv_dsm_break, 0 },
/* 778  */{ riscv_dsm_break, 0 },
/* 779  */{ riscv_dsm_break, 0 },
/* 780  */{ riscv_dsm_break, 0 },
/* 781  */{ riscv_dsm_break, 0 },
/* 782  */{ riscv_dsm_break, 0 },
/* 783  */{ riscv_dsm_break, 0 },
/* 784  */{ riscv_dsm_break, 0 },
/* 785  */{ riscv_dsm_break, 0 },
/* 786  */{ riscv_dsm_break, 0 },
/* 787  */{ riscv_dsm_break, 0 },
/* 788  */{ riscv_dsm_break, 0 },
/* 789  */{ riscv_dsm_break, 0 },
/* 790  */{ riscv_dsm_break, 0 },
/* 791  */{ riscv_dsm_break, 0 },
/* 792  */{ riscv_dsm_break, 0 },
/* 793  */{ riscv_dsm_break, 0 },
/* 794  */{ riscv_dsm_break, 0 },
/* 795  */{ riscv_dsm_break, 0 },
/* 796  */{ riscv_dsm_break, 0 },
/* 797  */{ riscv_dsm_break, 0 },
/* 798  */{ riscv_dsm_break, 0 },
/* 799  */{ riscv_dsm_break, 0 },
/* 800  */{ riscv_dsm_break, 0 },
/* 801  */{ riscv_dsm_break, 0 },
/* 802  */{ riscv_dsm_break, 0 },
/* 803  */{ riscv_dsm_break, 0 },
/* 804  */{ riscv_dsm_break, 0 },
/* 805  */{ riscv_dsm_break, 0 },
/* 806  */{ riscv_dsm_break, 0 },
/* 807  */{ riscv_dsm_break, 0 },
/* 808  */{ riscv_dsm_break, 0 },
/* 809  */{ riscv_dsm_break, 0 },
/* 810  */{ riscv_dsm_break, 0 },
/* 811  */{ riscv_dsm_break, 0 },
/* 812  */{ riscv_dsm_break, 0 },
/* 813  */{ riscv_dsm_break, 0 },
/* 814  */{ riscv_dsm_break, 0 },
/* 815  */{ riscv_dsm_break, 0 },
/* 816  */{ riscv_dsm_break, 0 },
/* 817  */{ riscv_dsm_break, 0 },
/* 818  */{ riscv_dsm_break, 0 },
/* 819  */{ riscv_dsm_break, 0 },
/* 820  */{ riscv_dsm_break, 0 },
/* 821  */{ riscv_dsm_break, 0 },
/* 822  */{ riscv_dsm_break, 0 },
/* 823  */{ riscv_dsm_break, 0 },
/* 824  */{ riscv_dsm_break, 0 },
/* 825  */{ riscv_dsm_break, 0 },
/* 826  */{ riscv_dsm_break, 0 },
/* 827  */{ riscv_dsm_break, 0 },
/* 828  */{ riscv_dsm_break, 0 },
/* 829  */{ riscv_dsm_break, 0 },
/* 830  */{ riscv_dsm_break, 0 },
/* 831  */{ riscv_dsm_break, 0 },
/* 832  */{ riscv_dsm_break, 0 },
/* 833  */{ riscv_dsm_break, 0 },
/* 834  */{ riscv_dsm_break, 0 },
/* 835  */{ riscv_dsm_break, 0 },
/* 836  */{ riscv_dsm_break, 0 },
/* 837  */{ riscv_dsm_break, 0 },
/* 838  */{ riscv_dsm_break, 0 },
/* 839  */{ riscv_dsm_break, 0 },
/* 840  */{ riscv_dsm_break, 0 },
/* 841  */{ riscv_dsm_break, 0 },
/* 842  */{ riscv_dsm_break, 0 },
/* 843  */{ riscv_dsm_break, 0 },
/* 844  */{ riscv_dsm_break, 0 },
/* 845  */{ riscv_dsm_break, 0 },
/* 846  */{ riscv_dsm_break, 0 },
/* 847  */{ riscv_dsm_break, 0 },
/* 848  */{ riscv_dsm_break, 0 },
/* 849  */{ riscv_dsm_break, 0 },
/* 850  */{ riscv_dsm_break, 0 },
/* 851  */{ riscv_dsm_break, 0 },
/* 852  */{ riscv_dsm_break, 0 },
/* 853  */{ riscv_dsm_break, 0 },
/* 854  */{ riscv_dsm_break, 0 },
/* 855  */{ riscv_dsm_break, 0 },
/* 856  */{ riscv_dsm_break, 0 },
/* 857  */{ riscv_dsm_break, 0 },
/* 858  */{ riscv_dsm_break, 0 },
/* 859  */{ riscv_dsm_break, 0 },
/* 860  */{ riscv_dsm_break, 0 },
/* 861  */{ riscv_dsm_break, 0 },
/* 862  */{ riscv_dsm_break, 0 },
/* 863  */{ riscv_dsm_break, 0 },
/* 864  */{ riscv_dsm_break, 0 },
/* 865  */{ riscv_dsm_break, 0 },
/* 866  */{ riscv_dsm_break, 0 },
/* 867  */{ riscv_dsm_break, 0 },
/* 868  */{ riscv_dsm_break, 0 },
/* 869  */{ riscv_dsm_break, 0 },
/* 870  */{ riscv_dsm_break, 0 },
/* 871  */{ riscv_dsm_break, 0 },
/* 872  */{ riscv_dsm_break, 0 },
/* 873  */{ riscv_dsm_break, 0 },
/* 874  */{ riscv_dsm_break, 0 },
/* 875  */{ riscv_dsm_break, 0 },
/* 876  */{ riscv_dsm_break, 0 },
/* 877  */{ riscv_dsm_break, 0 },
/* 878  */{ riscv_dsm_break, 0 },
/* 879  */{ riscv_dsm_break, 0 },
/* 880  */{ riscv_dsm_break, 0 },
/* 881  */{ riscv_dsm_break, 0 },
/* 882  */{ riscv_dsm_break, 0 },
/* 883  */{ riscv_dsm_break, 0 },
/* 884  */{ riscv_dsm_break, 0 },
/* 885  */{ riscv_dsm_break, 0 },
/* 886  */{ riscv_dsm_break, 0 },
/* 887  */{ riscv_dsm_break, 0 },
/* 888  */{ riscv_dsm_break, 0 },
/* 889  */{ riscv_dsm_break, 0 },
/* 890  */{ riscv_dsm_break, 0 },
/* 891  */{ riscv_dsm_break, 0 },
/* 892  */{ riscv_dsm_break, 0 },
/* 893  */{ riscv_dsm_break, 0 },
/* 894  */{ riscv_dsm_break, 0 },
/* 895  */{ riscv_dsm_break, 0 },
/* 896  */{ riscv_dsm_break, 0 },
/* 897  */{ riscv_dsm_break, 0 },
/* 898  */{ riscv_dsm_break, 0 },
/* 899  */{ riscv_dsm_break, 0 },
/* 900  */{ riscv_dsm_break, 0 },
/* 901  */{ riscv_dsm_break, 0 },
/* 902  */{ riscv_dsm_break, 0 },
/* 903  */{ riscv_dsm_break, 0 },
/* 904  */{ riscv_dsm_break, 0 },
/* 905  */{ riscv_dsm_break, 0 },
/* 906  */{ riscv_dsm_break, 0 },
/* 907  */{ riscv_dsm_break, 0 },
/* 908  */{ riscv_dsm_break, 0 },
/* 909  */{ riscv_dsm_break, 0 },
/* 910  */{ riscv_dsm_break, 0 },
/* 911  */{ riscv_dsm_break, 0 },
/* 912  */{ riscv_dsm_break, 0 },
/* 913  */{ riscv_dsm_break, 0 },
/* 914  */{ riscv_dsm_break, 0 },
/* 915  */{ riscv_dsm_break, 0 },
/* 916  */{ riscv_dsm_break, 0 },
/* 917  */{ riscv_dsm_break, 0 },
/* 918  */{ riscv_dsm_break, 0 },
/* 919  */{ riscv_dsm_break, 0 },
/* 920  */{ riscv_dsm_break, 0 },
/* 921  */{ riscv_dsm_break, 0 },
/* 922  */{ riscv_dsm_break, 0 },
/* 923  */{ riscv_dsm_break, 0 },
/* 924  */{ riscv_dsm_break, 0 },
/* 925  */{ riscv_dsm_break, 0 },
/* 926  */{ riscv_dsm_break, 0 },
/* 927  */{ riscv_dsm_break, 0 },
/* 928  */{ riscv_dsm_break, 0 },
/* 929  */{ riscv_dsm_break, 0 },
/* 930  */{ riscv_dsm_break, 0 },
/* 931  */{ riscv_dsm_break, 0 },
/* 932  */{ riscv_dsm_break, 0 },
/* 933  */{ riscv_dsm_break, 0 },
/* 934  */{ riscv_dsm_break, 0 },
/* 935  */{ riscv_dsm_break, 0 },
/* 936  */{ riscv_dsm_break, 0 },
/* 937  */{ riscv_dsm_break, 0 },
/* 938  */{ riscv_dsm_break, 0 },
/* 939  */{ riscv_dsm_break, 0 },
/* 940  */{ riscv_dsm_break, 0 },
/* 941  */{ riscv_dsm_break, 0 },
/* 942  */{ riscv_dsm_break, 0 },
/* 943  */{ riscv_dsm_break, 0 },
/* 944  */{ riscv_dsm_break, 0 },
/* 945  */{ riscv_dsm_break, 0 },
/* 946  */{ riscv_dsm_break, 0 },
/* 947  */{ riscv_dsm_break, 0 },
/* 948  */{ riscv_dsm_break, 0 },
/* 949  */{ riscv_dsm_break, 0 },
/* 950  */{ riscv_dsm_break, 0 },
/* 951  */{ riscv_dsm_break, 0 },
/* 952  */{ riscv_dsm_break, 0 },
/* 953  */{ riscv_dsm_break, 0 },
/* 954  */{ riscv_dsm_break, 0 },
/* 955  */{ riscv_dsm_break, 0 },
/* 956  */{ riscv_dsm_select, riscv_op_subw },
/* 957  */{ riscv_dsm_break, 0 },
/* 958  */{ riscv_dsm_break, 0 },
/* 959  */{ riscv_dsm_break, 0 },
/* 960  */{ riscv_dsm_break, 0 },
/* 961  */{ riscv_dsm_select, riscv_op_sraw },
/* 962  */{ riscv_dsm_mask_srl25, 3 },
/* 963  */{ riscv_dsm_table_brk, 2 },
/* 964  */{ riscv_dsm_select, riscv_op_fmadd_s },
/* 965  */{ riscv_dsm_select, riscv_op_fmadd_d },
/* 966  */{ riscv_dsm_mask_srl25, 3 },
/* 967  */{ riscv_dsm_table_brk, 2 },
/* 968  */{ riscv_dsm_select, riscv_op_fmsub_s },
/* 969  */{ riscv_dsm_select, riscv_op_fmsub_d },
/* 970  */{ riscv_dsm_mask_srl25, 3 },
/* 971  */{ riscv_dsm_table_brk, 2 },
/* 972  */{ riscv_dsm_select, riscv_op_fnmsub_s },
/* 973  */{ riscv_dsm_select, riscv_op_fnmsub_d },
/* 974  */{ riscv_dsm_mask_srl25, 3 },
/* 975  */{ riscv_dsm_table_brk, 2 },
/* 976  */{ riscv_dsm_select, riscv_op_fnmadd_s },
/* 977  */{ riscv_dsm_select, riscv_op_fnmadd_d },
/* 978  */{ riscv_dsm_mask_srl25, 127 },
/* 979  */{ riscv_dsm_table_brk, 122 },
/* 980  */{ riscv_dsm_select, riscv_op_fadd_s },
/* 981  */{ riscv_dsm_select, riscv_op_fadd_d },
/* 982  */{ riscv_dsm_break, 0 },
/* 983  */{ riscv_dsm_break, 0 },
/* 984  */{ riscv_dsm_select, riscv_op_fsub_s },
/* 985  */{ riscv_dsm_select, riscv_op_fsub_d },
/* 986  */{ riscv_dsm_break, 0 },
/* 987  */{ riscv_dsm_break, 0 },
/* 988  */{ riscv_dsm_select, riscv_op_fmul_s },
/* 989  */{ riscv_dsm_select, riscv_op_fmul_d },
/* 990  */{ riscv_dsm_break, 0 },
/* 991  */{ riscv_dsm_break, 0 },
/* 992  */{ riscv_dsm_select, riscv_op_fdiv_s },
/* 993  */{ riscv_dsm_select, riscv_op_fdiv_d },
/* 994  */{ riscv_dsm_break, 0 },
/* 995  */{ riscv_dsm_break, 0 },
/* 996  */{ riscv_dsm_jump, 106 },
/* 997  */{ riscv_dsm_jump, 110 },
/* 998  */{ riscv_dsm_break, 0 },
/* 999  */{ riscv_dsm_break, 0 },
/* 1000 */{ riscv_dsm_jump, 112 },
/* 1001 */{ riscv_dsm_jump, 115 },
/* 1002 */{ riscv_dsm_break, 0 },
/* 1003 */{ riscv_dsm_break, 0 },
/* 1004 */{ riscv_dsm_break, 0 },
/* 1005 */{ riscv_dsm_break, 0 },
/* 1006 */{ riscv_dsm_break, 0 },
/* 1007 */{ riscv_dsm_break, 0 },
/* 1008 */{ riscv_dsm_break, 0 },
/* 1009 */{ riscv_dsm_break, 0 },
/* 1010 */{ riscv_dsm_break, 0 },
/* 1011 */{ riscv_dsm_break, 0 },
/* 1012 */{ riscv_dsm_jump, 108 },
/* 1013 */{ riscv_dsm_jump, 111 },
/* 1014 */{ riscv_dsm_break, 0 },
/* 1015 */{ riscv_dsm_break, 0 },
/* 1016 */{ riscv_dsm_break, 0 },
/* 1017 */{ riscv_dsm_break, 0 },
/* 1018 */{ riscv_dsm_break, 0 },
/* 1019 */{ riscv_dsm_break, 0 },
/* 1020 */{ riscv_dsm_break, 0 },
/* 1021 */{ riscv_dsm_break, 0 },
/* 1022 */{ riscv_dsm_break, 0 },
/* 1023 */{ riscv_dsm_break, 0 },
/* 1024 */{ riscv_dsm_jump, 103 },
/* 1025 */{ riscv_dsm_jump, 105 },
/* 1026 */{ riscv_dsm_break, 0 },
/* 1027 */{ riscv_dsm_break, 0 },
/* 1028 */{ riscv_dsm_break, 0 },
/* 1029 */{ riscv_dsm_break, 0 },
/* 1030 */{ riscv_dsm_break, 0 },
/* 1031 */{ riscv_dsm_break, 0 },
/* 1032 */{ riscv_dsm_break, 0 },
/* 1033 */{ riscv_dsm_break, 0 },
/* 1034 */{ riscv_dsm_break, 0 },
/* 1035 */{ riscv_dsm_break, 0 },
/* 1036 */{ riscv_dsm_break, 0 },
/* 1037 */{ riscv_dsm_break, 0 },
/* 1038 */{ riscv_dsm_break, 0 },
/* 1039 */{ riscv_dsm_break, 0 },
/* 1040 */{ riscv_dsm_break, 0 },
/* 1041 */{ riscv_dsm_break, 0 },
/* 1042 */{ riscv_dsm_break, 0 },
/* 1043 */{ riscv_dsm_break, 0 },
/* 1044 */{ riscv_dsm_break, 0 },
/* 1045 */{ riscv_dsm_break, 0 },
/* 1046 */{ riscv_dsm_break, 0 },
/* 1047 */{ riscv_dsm_break, 0 },
/* 1048 */{ riscv_dsm_break, 0 },
/* 1049 */{ riscv_dsm_break, 0 },
/* 1050 */{ riscv_dsm_break, 0 },
/* 1051 */{ riscv_dsm_break, 0 },
/* 1052 */{ riscv_dsm_break, 0 },
/* 1053 */{ riscv_dsm_break, 0 },
/* 1054 */{ riscv_dsm_break, 0 },
/* 1055 */{ riscv_dsm_break, 0 },
/* 1056 */{ riscv_dsm_break, 0 },
/* 1057 */{ riscv_dsm_break, 0 },
/* 1058 */{ riscv_dsm_break, 0 },
/* 1059 */{ riscv_dsm_break, 0 },
/* 1060 */{ riscv_dsm_jump, 73 },
/* 1061 */{ riscv_dsm_jump, 77 },
/* 1062 */{ riscv_dsm_break, 0 },
/* 1063 */{ riscv_dsm_break, 0 },
/* 1064 */{ riscv_dsm_break, 0 },
/* 1065 */{ riscv_dsm_break, 0 },
/* 1066 */{ riscv_dsm_break, 0 },
/* 1067 */{ riscv_dsm_break, 0 },
/* 1068 */{ riscv_dsm_break, 0 },
/* 1069 */{ riscv_dsm_break, 0 },
/* 1070 */{ riscv_dsm_break, 0 },
/* 1071 */{ riscv_dsm_break, 0 },
/* 1072 */{ riscv_dsm_break, 0 },
/* 1073 */{ riscv_dsm_break, 0 },
/* 1074 */{ riscv_dsm_break, 0 },
/* 1075 */{ riscv_dsm_break, 0 },
/* 1076 */{ riscv_dsm_jump, 67 },
/* 1077 */{ riscv_dsm_jump, 72 },
/* 1078 */{ riscv_dsm_break, 0 },
/* 1079 */{ riscv_dsm_break, 0 },
/* 1080 */{ riscv_dsm_break, 0 },
/* 1081 */{ riscv_dsm_break, 0 },
/* 1082 */{ riscv_dsm_break, 0 },
/* 1083 */{ riscv_dsm_break, 0 },
/* 1084 */{ riscv_dsm_jump, 71 },
/* 1085 */{ riscv_dsm_jump, 76 },
/* 1086 */{ riscv_dsm_break, 0 },
/* 1087 */{ riscv_dsm_break, 0 },
/* 1088 */{ riscv_dsm_break, 0 },
/* 1089 */{ riscv_dsm_break, 0 },
/* 1090 */{ riscv_dsm_break, 0 },
/* 1091 */{ riscv_dsm_break, 0 },
/* 1092 */{ riscv_dsm_jump, 75 },
/* 1093 */{ riscv_dsm_jump, 79 },
/* 1094 */{ riscv_dsm_break, 0 },
/* 1095 */{ riscv_dsm_break, 0 },
/* 1096 */{ riscv_dsm_break, 0 },
/* 1097 */{ riscv_dsm_break, 0 },
/* 1098 */{ riscv_dsm_break, 0 },
/* 1099 */{ riscv_dsm_break, 0 },
/* 1100 */{ riscv_dsm_jump, 77 },
/* 1101 */{ riscv_dsm_jump, 80 },
/* 1102 */{ riscv_dsm_mask_srl12, 7 },
/* 1103 */{ riscv_dsm_table_brk, 3 },
/* 1104 */{ riscv_dsm_select, riscv_op_fsgnj_s },
/* 1105 */{ riscv_dsm_select, riscv_op_fsgnjn_s },
/* 1106 */{ riscv_dsm_select, riscv_op_fsgnjx_s },
/* 1107 */{ riscv_dsm_mask_srl12, 7 },
/* 1108 */{ riscv_dsm_table_brk, 3 },
/* 1109 */{ riscv_dsm_select, riscv_op_fsgnj_d },
/* 1110 */{ riscv_dsm_select, riscv_op_fsgnjn_d },
/* 1111 */{ riscv_dsm_select, riscv_op_fsgnjx_d },
/* 1112 */{ riscv_dsm_mask_srl12, 7 },
/* 1113 */{ riscv_dsm_table_brk, 2 },
/* 1114 */{ riscv_dsm_select, riscv_op_fmin_s },
/* 1115 */{ riscv_dsm_select, riscv_op_fmax_s },
/* 1116 */{ riscv_dsm_mask_srl12, 7 },
/* 1117 */{ riscv_dsm_table_brk, 2 },
/* 1118 */{ riscv_dsm_select, riscv_op_fmin_d },
/* 1119 */{ riscv_dsm_select, riscv_op_fmax_d },
/* 1120 */{ riscv_dsm_mask_srl20, 31 },
/* 1121 */{ riscv_dsm_table_brk, 2 },
/* 1122 */{ riscv_dsm_break, 0 },
/* 1123 */{ riscv_dsm_select, riscv_op_fcvt_s_d },
/* 1124 */{ riscv_dsm_mask_srl20, 31 },
/* 1125 */{ riscv_dsm_table_brk, 1 },
/* 1126 */{ riscv_dsm_select, riscv_op_fcvt_d_s },
/* 1127 */{ riscv_dsm_mask_srl20, 31 },
/* 1128 */{ riscv_dsm_table_brk, 1 },
/* 1129 */{ riscv_dsm_select, riscv_op_fsqrt_s },
/* 1130 */{ riscv_dsm_mask_srl20, 31 },
/* 1131 */{ riscv_dsm_table_brk, 1 },
/* 1132 */{ riscv_dsm_select, riscv_op_fsqrt_d },
/* 1133 */{ riscv_dsm_mask_srl12, 7 },
/* 1134 */{ riscv_dsm_table_brk, 3 },
/* 1135 */{ riscv_dsm_select, riscv_op_fle_s },
/* 1136 */{ riscv_dsm_select, riscv_op_flt_s },
/* 1137 */{ riscv_dsm_select, riscv_op_feq_s },
/* 1138 */{ riscv_dsm_mask_srl12, 7 },
/* 1139 */{ riscv_dsm_table_brk, 3 },
/* 1140 */{ riscv_dsm_select, riscv_op_fle_d },
/* 1141 */{ riscv_dsm_select, riscv_op_flt_d },
/* 1142 */{ riscv_dsm_select, riscv_op_feq_d },
/* 1143 */{ riscv_dsm_mask_srl20, 31 },
/* 1144 */{ riscv_dsm_table_brk, 4 },
/* 1145 */{ riscv_dsm_select, riscv_op_fcvt_w_s },
/* 1146 */{ riscv_dsm_select, riscv_op_fcvt_wu_s },
/* 1147 */{ riscv_dsm_select, riscv_op_fcvt_l_s },
/* 1148 */{ riscv_dsm_select, riscv_op_fcvt_lu_s },
/* 1149 */{ riscv_dsm_mask_srl20, 31 },
/* 1150 */{ riscv_dsm_table_brk, 4 },
/* 1151 */{ riscv_dsm_select, riscv_op_fcvt_w_d },
/* 1152 */{ riscv_dsm_select, riscv_op_fcvt_wu_d },
/* 1153 */{ riscv_dsm_select, riscv_op_fcvt_l_d },
/* 1154 */{ riscv_dsm_select, riscv_op_fcvt_lu_d },
/* 1155 */{ riscv_dsm_mask_srl20, 31 },
/* 1156 */{ riscv_dsm_table_brk, 4 },
/* 1157 */{ riscv_dsm_select, riscv_op_fcvt_s_w },
/* 1158 */{ riscv_dsm_select, riscv_op_fcvt_s_wu },
/* 1159 */{ riscv_dsm_select, riscv_op_fcvt_s_l },
/* 1160 */{ riscv_dsm_select, riscv_op_fcvt_s_lu },
/* 1161 */{ riscv_dsm_mask_srl20, 31 },
/* 1162 */{ riscv_dsm_table_brk, 4 },
/* 1163 */{ riscv_dsm_select, riscv_op_fcvt_d_w },
/* 1164 */{ riscv_dsm_select, riscv_op_fcvt_d_wu },
/* 1165 */{ riscv_dsm_select, riscv_op_fcvt_d_l },
/* 1166 */{ riscv_dsm_select, riscv_op_fcvt_d_lu },
/* 1167 */{ riscv_dsm_mask_srl17, 248 },
/* 1168 */{ riscv_dsm_mask_srl12, 7 },
/* 1169 */{ riscv_dsm_table_brk, 2 },
/* 1170 */{ riscv_dsm_select, riscv_op_fmv_x_s },
/* 1171 */{ riscv_dsm_select, riscv_op_fclass_s },
/* 1172 */{ riscv_dsm_mask_srl17, 248 },
/* 1173 */{ riscv_dsm_mask_srl12, 7 },
/* 1174 */{ riscv_dsm_table_brk, 2 },
/* 1175 */{ riscv_dsm_select, riscv_op_fmv_x_d },
/* 1176 */{ riscv_dsm_select, riscv_op_fclass_d },
/* 1177 */{ riscv_dsm_mask_srl17, 248 },
/* 1178 */{ riscv_dsm_mask_srl12, 7 },
/* 1179 */{ riscv_dsm_table_brk, 1 },
/* 1180 */{ riscv_dsm_select, riscv_op_fmv_s_x },
/* 1181 */{ riscv_dsm_mask_srl17, 248 },
/* 1182 */{ riscv_dsm_mask_srl12, 7 },
/* 1183 */{ riscv_dsm_table_brk, 1 },
/* 1184 */{ riscv_dsm_select, riscv_op_fmv_d_x },
/* 1185 */{ riscv_dsm_mask_srl12, 7 },
/* 1186 */{ riscv_dsm_table_brk, 8 },
/* 1187 */{ riscv_dsm_select, riscv_op_beq },
/* 1188 */{ riscv_dsm_select, riscv_op_bne },
/* 1189 */{ riscv_dsm_break, 0 },
/* 1190 */{ riscv_dsm_break, 0 },
/* 1191 */{ riscv_dsm_select, riscv_op_blt },
/* 1192 */{ riscv_dsm_select, riscv_op_bge },
/* 1193 */{ riscv_dsm_select, riscv_op_bltu },
/* 1194 */{ riscv_dsm_select, riscv_op_bgeu },
/* 1195 */{ riscv_dsm_mask_srl12, 7 },
/* 1196 */{ riscv_dsm_table_brk, 1 },
/* 1197 */{ riscv_dsm_select, riscv_op_jalr },
/* 1198 */{ riscv_dsm_mask_srl12, 7 },
/* 1199 */{ riscv_dsm_table_brk, 8 },
/* 1200 */{ riscv_dsm_jump, 8 },
/* 1201 */{ riscv_dsm_select, riscv_op_csrrw },
/* 1202 */{ riscv_dsm_select, riscv_op_csrrs },
/* 1203 */{ riscv_dsm_select, riscv_op_csrrc },
/* 1204 */{ riscv_dsm_break, 0 },
/* 1205 */{ riscv_dsm_select, riscv_op_csrrwi },
/* 1206 */{ riscv_dsm_select, riscv_op_csrrsi },
/* 1207 */{ riscv_dsm_select, riscv_op_csrrci },
/* 1208 */{ riscv_dsm_mask_srl15, 131040 },
/* 1209 */{ riscv_dsm_mask_srl7, 31 },
/* 1210 */{ riscv_dsm_match, 0 },
/* 1211 */{ riscv_dsm_jump, 16 },
/* 1212 */{ riscv_dsm_match, 32 },
/* 1213 */{ riscv_dsm_jump, 17 },
/* 1214 */{ riscv_dsm_match, 8192 },
/* 1215 */{ riscv_dsm_jump, 18 },
/* 1216 */{ riscv_dsm_match, 8224 },
/* 1217 */{ riscv_dsm_select, riscv_op_sfence_vm },
/* 1218 */{ riscv_dsm_match, 8256 },
/* 1219 */{ riscv_dsm_jump, 17 },
/* 1220 */{ riscv_dsm_match, 16544 },
/* 1221 */{ riscv_dsm_jump, 18 },
/* 1222 */{ riscv_dsm_match, 24736 },
/* 1223 */{ riscv_dsm_jump, 19 },
/* 1224 */{ riscv_dsm_match, 24768 },
/* 1225 */{ riscv_dsm_jump, 20 },
/* 1226 */{ riscv_dsm_break, 0 },
/* 1227 */{ riscv_dsm_mask_srl15, 31 },
/* 1228 */{ riscv_dsm_table_brk, 1 },
/* 1229 */{ riscv_dsm_select, riscv_op_scall },
/* 1230 */{ riscv_dsm_mask_srl15, 31 },
/* 1231 */{ riscv_dsm_table_brk, 1 },
/* 1232 */{ riscv_dsm_select, riscv_op_sbreak },
/* 1233 */{ riscv_dsm_mask_srl15, 31 },
/* 1234 */{ riscv_dsm_table_brk, 1 },
/* 1235 */{ riscv_dsm_select, riscv_op_sret },
/* 1236 */{ riscv_dsm_mask_srl15, 31 },
/* 1237 */{ riscv_dsm_table_brk, 1 },
/* 1238 */{ riscv_dsm_select, riscv_op_wfi },
/* 1239 */{ riscv_dsm_mask_srl15, 31 },
/* 1240 */{ riscv_dsm_table_brk, 1 },
/* 1241 */{ riscv_dsm_select, riscv_op_hrts },
/* 1242 */{ riscv_dsm_mask_srl15, 31 },
/* 1243 */{ riscv_dsm_table_brk, 1 },
/* 1244 */{ riscv_dsm_select, riscv_op_mrts },
/* 1245 */{ riscv_dsm_mask_srl15, 31 },
/* 1246 */{ riscv_dsm_table_brk, 1 },
/* 1247 */{ riscv_dsm_select, riscv_op_mrth },
};

const riscv_csr_metadata riscv_csr_table[] = {
	{ 0x001, riscv_csr_perm_urw, "fflags", "Floating-Point Accrued Exceptions" },
	{ 0x002, riscv_csr_perm_urw, "frm", "Floating-Point Dynamic Rounding Mode" },
	{ 0x003, riscv_csr_perm_urw, "fcsr", "Floating-Point Control and Status Register (frm + fflags)" },
	{ 0xC00, riscv_csr_perm_uro, "cycle", "Cycle counter for RDCYCLE instruction" },
	{ 0xC01, riscv_csr_perm_uro, "time", "Timer for RDTIME instruction" },
	{ 0xC02, riscv_csr_perm_uro, "instret", "Instructions-retired counter for RDINSTRET instruction" },
	{ 0xC80, riscv_csr_perm_uro, "cycleh", "Upper 32 bits of cycle, RV32I only" },
	{ 0xC81, riscv_csr_perm_uro, "timeh", "Upper 32 bits of time, RV32I only" },
	{ 0xC82, riscv_csr_perm_uro, "instreth", "Upper 32 bits of instret, RV32I only" },
	{ 0x100, riscv_csr_perm_srw, "sstatus", "Supervisor status register" },
	{ 0x101, riscv_csr_perm_srw, "stvec", "Supervisor trap handler base address" },
	{ 0x104, riscv_csr_perm_srw, "sie", "Supervisor interrupt-enable register" },
	{ 0x121, riscv_csr_perm_srw, "stimecmp", "Wall-clock timer compare value" },
	{ 0xD01, riscv_csr_perm_sro, "stime", "Supervisor wall-clock time register" },
	{ 0xD81, riscv_csr_perm_sro, "stimeh", "Upper 32 bits of stime, RV32I only" },
	{ 0x140, riscv_csr_perm_srw, "sscratch", "Scratch register for supervisor trap handlers" },
	{ 0x141, riscv_csr_perm_srw, "sepc", "Supervisor exception program counter" },
	{ 0xD42, riscv_csr_perm_sro, "scause", "Supervisor trap cause" },
	{ 0xD43, riscv_csr_perm_sro, "sbadaddr", "Supervisor bad address" },
	{ 0x144, riscv_csr_perm_srw, "sip", "Supervisor interrupt pending" },
	{ 0x180, riscv_csr_perm_srw, "sptbr", "Page-table base register" },
	{ 0x181, riscv_csr_perm_srw, "sasid", "Address-space ID" },
	{ 0x900, riscv_csr_perm_srw, "cyclew", "Cycle counter for RDCYCLE instruction" },
	{ 0x901, riscv_csr_perm_srw, "timew", "Timer for RDTIME instruction" },
	{ 0x902, riscv_csr_perm_srw, "instretw", "Instructions-retired counter for RDINSTRET instruction" },
	{ 0x980, riscv_csr_perm_srw, "cyclehw", "Upper 32 bits of cycle, RV32I only" },
	{ 0x981, riscv_csr_perm_srw, "timehw", "Upper 32 bits of time, RV32I only" },
	{ 0x982, riscv_csr_perm_srw, "instrethw", "Upper 32 bits of instret, RV32I only" },
	{ 0x200, riscv_csr_perm_hrw, "hstatus", "Hypervisor status register" },
	{ 0x201, riscv_csr_perm_hrw, "htvec", "Hypervisor trap handler base address" },
	{ 0x202, riscv_csr_perm_hrw, "htdeleg", "Hypervisor trap delegation register" },
	{ 0x221, riscv_csr_perm_hrw, "htimecmp", "Hypervisor wall-clock timer compare value" },
	{ 0xE01, riscv_csr_perm_hro, "htime", "Hypervisor wall-clock time register" },
	{ 0xE81, riscv_csr_perm_hro, "htimeh", "Upper 32 bits of htime, RV32I only" },
	{ 0x240, riscv_csr_perm_hrw, "hscratch", "Scratch register for hypervisor trap handlers" },
	{ 0x241, riscv_csr_perm_hrw, "hepc", "Hypervisor exception program counter" },
	{ 0x242, riscv_csr_perm_hrw, "hcause", "Hypervisor trap cause" },
	{ 0x243, riscv_csr_perm_hrw, "hbadaddr", "Hypervisor bad address" },
	{ 0xA01, riscv_csr_perm_hrw, "stimew", "Supervisor wall-clock timer" },
	{ 0xA81, riscv_csr_perm_hrw, "stimehw", "Upper 32 bits of supervisor wall-clock timer, RV32I only" },
	{ 0xF00, riscv_csr_perm_mro, "mcpuid", "CPU description" },
	{ 0xF01, riscv_csr_perm_mro, "mimpid", "Vendor ID and version number" },
	{ 0xF10, riscv_csr_perm_mro, "mhartid", "Hardware thread ID" },
	{ 0x300, riscv_csr_perm_mrw, "mstatus", "Machine status register" },
	{ 0x301, riscv_csr_perm_mrw, "mtvec", "Machine trap-handler base address" },
	{ 0x302, riscv_csr_perm_mrw, "mtdeleg", "Machine trap delegation register" },
	{ 0x304, riscv_csr_perm_mrw, "mie", "Machine interrupt-enable register" },
	{ 0x321, riscv_csr_perm_mrw, "mtimecmp", "Machine wall-clock timer compare value" },
	{ 0x300, riscv_csr_perm_mrw, "mstatus", "Machine status register" },
	{ 0x301, riscv_csr_perm_mrw, "mtvec", "Machine trap-handler base address" },
	{ 0x302, riscv_csr_perm_mrw, "mtdeleg", "Machine trap delegation register" },
	{ 0x304, riscv_csr_perm_mrw, "mie", "Machine interrupt-enable register" },
	{ 0x321, riscv_csr_perm_mrw, "mtimecmp", "Machine wall-clock timer compare value" },
	{ 0x340, riscv_csr_perm_mrw, "mscratch", "Scratch register for machine trap handlers" },
	{ 0x341, riscv_csr_perm_mrw, "mepc", "Machine exception program counter" },
	{ 0x342, riscv_csr_perm_mrw, "mcause", "Machine trap cause" },
	{ 0x343, riscv_csr_perm_mrw, "mbadaddr", "Machine bad address" },
	{ 0x344, riscv_csr_perm_mrw, "mip", "Machine interrupt pending" },
	{ 0x380, riscv_csr_perm_mrw, "mbase", "Base register" },
	{ 0x381, riscv_csr_perm_mrw, "mbound", "Bound register" },
	{ 0x382, riscv_csr_perm_mrw, "mibase", "Instruction base register" },
	{ 0x383, riscv_csr_perm_mrw, "mibound", "Instruction bound register" },
	{ 0x384, riscv_csr_perm_mrw, "mdbase", "Data base register" },
	{ 0x385, riscv_csr_perm_mrw, "mdbound", "Data bound register" },
	{ 0xB01, riscv_csr_perm_mrw, "htimew", "Hypervisor wall-clock timer" },
	{ 0xB81, riscv_csr_perm_mrw, "htimehw", "Upper 32 bits of hypervisor wall-clock timer, RV32I only" },
	{ 0x780, riscv_csr_perm_mrw, "mtohost", "Output register to host" },
	{ 0x781, riscv_csr_perm_mrw, "mfromhost", "Input register from host" },
	{ 0x000, riscv_csr_perm_none, nullptr, nullptr }
};

const rvf rvf_none[] =               { rvf_z };
const rvf rvf_imm_pc[] =             { rvf_ipc, rvf_z };
const rvf rvf_rs1_rs2[] =            { rvf_rs1, rvf_c, rvf_rs2, rvf_z };
const rvf rvf_rs2_imm[] =            { rvf_rs2, rvf_c, rvf_i, rvf_z };
const rvf rvf_rd_imm[] =             { rvf_rd, rvf_c, rvf_i, rvf_z };
const rvf rvf_rd_imm_pc[] =          { rvf_rd, rvf_c, rvf_ipc, rvf_z };
const rvf rvf_rd_rs1_rs2[] =         { rvf_rd, rvf_c, rvf_rs1, rvf_c, rvf_rs2, rvf_z };
const rvf rvf_frd_frs1_frs2[] =      { rvf_frd, rvf_c, rvf_frs1, rvf_c, rvf_frs2, rvf_z };
const rvf rvf_rd_frs1_frs2[] =       { rvf_frd, rvf_c, rvf_rs1, rvf_c, rvf_frs2, rvf_z };
const rvf rvf_frd_frs1_frs2_frs3[] = { rvf_frd, rvf_c, rvf_frs1, rvf_c, rvf_frs2, rvf_c, rvf_frs3, rvf_z };
const rvf rvf_frd_rs1[] =            { rvf_frd, rvf_c, rvf_rs1, rvf_z };
const rvf rvf_frd_frs1[] =           { rvf_frd, rvf_c, rvf_frs1, rvf_z };
const rvf rvf_rd_frs1[] =            { rvf_rd, rvf_c, rvf_frs1, rvf_z };
const rvf rvf_rd_rs1_imm[] =         { rvf_rd, rvf_c, rvf_rs1, rvf_c, rvf_i, rvf_z };
const rvf rvf_rd_bimm_rs1[] =        { rvf_rd, rvf_c, rvf_i, rvf_b, rvf_rs1, rvf_d, rvf_z };
const rvf rvf_frd_bimm_rs1[] =       { rvf_frd, rvf_c, rvf_i, rvf_b, rvf_rs1, rvf_d, rvf_z };
const rvf rvf_rd_csr_rs1[] =         { rvf_rd, rvf_c, rvf_icsr, rvf_c, rvf_rs1, rvf_z };
const rvf rvf_rd_csr_srs1[] =        { rvf_rd, rvf_c, rvf_icsr, rvf_c, rvf_srs1, rvf_z };
const rvf rvf_rs1_rs2_imm[] =        { rvf_rs1, rvf_c, rvf_rs2, rvf_c, rvf_i, rvf_z };
const rvf rvf_rs2_bimm_rs1[] =       { rvf_rs2, rvf_c, rvf_i, rvf_b, rvf_rs1, rvf_d, rvf_z };
const rvf rvf_frs2_bimm_rs1[] =      { rvf_frs2, rvf_c, rvf_i, rvf_b, rvf_rs1, rvf_d, rvf_z };
const rvf rvf_rs1_rs2_imm_pc[] =     { rvf_rs1, rvf_c, rvf_rs2, rvf_c, rvf_ipc, rvf_z };

const riscv_inst_type_metadata riscv_inst_type_table[] = {
	{ riscv_inst_type_unknown,      rvf_none },
	{ riscv_inst_type_cr,           rvf_rs1_rs2 },
	{ riscv_inst_type_ci,           rvf_rd_imm },
	{ riscv_inst_type_ci_lui,       rvf_rd_imm },
	{ riscv_inst_type_ci_lwsp,      rvf_rd_imm },
	{ riscv_inst_type_ci_ldsp,      rvf_rd_imm },
	{ riscv_inst_type_ci_addi16sp,  rvf_rd_imm },
	{ riscv_inst_type_css_swsp,     rvf_rs2_imm },
	{ riscv_inst_type_css_sdsp,     rvf_rs2_imm },
	{ riscv_inst_type_ciw_addi4spn, rvf_rd_imm },
	{ riscv_inst_type_cl_lw,        rvf_rd_imm },
	{ riscv_inst_type_cl_ld,        rvf_rd_imm },
	{ riscv_inst_type_cs_x,         rvf_rs1_rs2 },
	{ riscv_inst_type_cs_sw,        rvf_rs1_rs2_imm },
	{ riscv_inst_type_cs_sd,        rvf_rs1_rs2_imm },
	{ riscv_inst_type_cb,           rvf_imm_pc },
	{ riscv_inst_type_cj,           rvf_imm_pc },
	{ riscv_inst_type_r,            rvf_rd_rs1_rs2 },
	{ riscv_inst_type_r_ff,         rvf_frd_frs1},
	{ riscv_inst_type_r_rf,         rvf_rd_frs1},
	{ riscv_inst_type_r_fr,         rvf_frd_rs1 },
	{ riscv_inst_type_r_fff,        rvf_frd_frs1_frs2},
	{ riscv_inst_type_r_rff,        rvf_rd_frs1_frs2},
	{ riscv_inst_type_r_ffff,       rvf_frd_frs1_frs2_frs3},
	{ riscv_inst_type_i,            rvf_rd_rs1_imm },
	{ riscv_inst_type_i_s,          rvf_none },
	{ riscv_inst_type_i_l,          rvf_rd_bimm_rs1 },
	{ riscv_inst_type_i_lf,         rvf_frd_bimm_rs1 },
	{ riscv_inst_type_i_csr,        rvf_rd_csr_rs1 },
	{ riscv_inst_type_i_csri,       rvf_rd_csr_srs1 },
	{ riscv_inst_type_s,            rvf_rs2_bimm_rs1 },
	{ riscv_inst_type_sf,           rvf_frs2_bimm_rs1 },
	{ riscv_inst_type_sb,           rvf_rs1_rs2_imm_pc },
	{ riscv_inst_type_u,            rvf_rd_imm },
	{ riscv_inst_type_uj,           rvf_rd_imm_pc },
	{ riscv_inst_type_unknown,      nullptr }
};

riscv_wu test_code_1[] = {
	0x0026c197,
	0xd7018193,
	0x800000e7,
	0x04051063,
	0x0026c517,
	0xcd050513,
	0x00000593,
	0x002a3617,
	0x14460613,
	0x40a60633,
	0x00127317,
	0x07c300e7,
	0x00250117,
	0xfd010113,
	0x00259217,
	0xc0020213,
	0x000032b7,
	0x1002b073,
	0x5180006f,
	0x00800593,
	0x02b57663,
	0x0026e597,
	0xfac58593,
	0x00351513,
	0x00b50533,
	0x00053103,
	0xfe010ee3,
	0xffffe237,
	0x00220233,
	0x00023203,
	0x7980106f,
	0x10200073,
	0xffdff06f
};

riscv_hu test_code_2[] = {
	0x6197, 0x001d,
	0x8193, 0xd701,
	0x00e7, 0x8000,
	0xe915,
	0x6517, 0x001d,
	0x0513, 0xcd25,
	0x4581,
	0xd617, 0x0020,
	0x0613, 0x1486,
	0x8e09,
	0xc0ef, 0x527c,
	0xa117, 0x001b,
	0x0113, 0xfda1,
	0x3217, 0x001c,
	0x0213, 0xc0a2,
	0x628d,
	0xb073, 0x1002,
	0x006f, 0x3680,
	0x45a1,
	0x7263, 0x02b5,
	0x8597, 0x001d,
	0x8593, 0xfba5,
	0x050e,
	0x952e,
	0x3103, 0x0005,
	0x0ee3, 0xfe01,
	0x7279,
	0x920a,
	0x3203, 0x0002,
	0x106f, 0x1300,
	0x0073, 0x1020,
	0xbff5
};

static const int INITIAL_BUFFER_SIZE = 256;

static const char* FATAL_PREFIX = "FATAL";
static const char* ERROR_PREFIX = "ERROR";
static const char* DEBUG_PREFIX = "DEBUG";
static const char* INFO_PREFIX = "INFO";

std::string format_string(const char* fmt, ...)
{
    std::vector<char> buf(INITIAL_BUFFER_SIZE);
    va_list ap;
    
    va_start(ap, fmt);
    int len = vsnprintf(buf.data(), buf.capacity(), fmt, ap);
    va_end(ap);
    
    std::string str;
    if (len >= (int)buf.capacity()) {
        buf.resize(len + 1);
        va_start(ap, fmt);
        vsnprintf(buf.data(), buf.capacity(), fmt, ap);
        va_end(ap);
    }
    str = buf.data();
    
    return str;
}

void log_prefix(const char* prefix, const char* fmt, va_list arg)
{
	std::vector<char> buf(INITIAL_BUFFER_SIZE);

	int len = vsnprintf(buf.data(), buf.capacity(), fmt, arg);

	if (len >= (int)buf.capacity()) {
		buf.resize(len + 1);
		vsnprintf(buf.data(), buf.capacity(), fmt, arg);
	}

	fprintf(stderr, "%s: %s\n", prefix, buf.data());
}

void log_fatal_exit(const char* fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	log_prefix(FATAL_PREFIX, fmt, ap);
	va_end(ap);
	exit(9);
}

void log_error(const char* fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	log_prefix(ERROR_PREFIX, fmt, ap);
	va_end(ap);
}

void log_info(const char* fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	log_prefix(INFO_PREFIX, fmt, ap);
	va_end(ap);
}

void log_debug(const char* fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	log_prefix(DEBUG_PREFIX, fmt, ap);
	va_end(ap);
}

static std::vector<char> read_file(std::string filename)
{
	std::vector<char> buf;
	struct stat stat_buf;

	FILE *file = fopen(filename.c_str(), "r");
	if (!file) {
		log_fatal_exit("error fopen: %s: %s", filename.c_str(), strerror(errno));
	}

	if (fstat(fileno(file), &stat_buf) < 0) {
		log_fatal_exit("error fstat: %s: %s", filename.c_str(), strerror(errno));
	}

	buf.resize(stat_buf.st_size);
	size_t bytes_read = fread(buf.data(), 1, stat_buf.st_size, file);
	if (bytes_read != (size_t)stat_buf.st_size) {
		log_fatal_exit("error fread: %s", filename.c_str());
	}
	fclose(file);

	return buf;
}

void decode_rv64(riscv_ptr start, riscv_ptr end, riscv_ptr pc_offset)
{
	riscv_decode dec;
	riscv_proc_state proc = { 0 };
	proc.p_type = riscv_proc_type_rv64i;

	proc.pc = start;
	while (proc.pc < end) {
		riscv_ptr pc = proc.pc;
		riscv_decode_instruction(dec, &proc);
		//riscv_decode_instruction_dsm(dec, &proc);
		std::string s = riscv_format_instruction(dec, &proc, pc, pc_offset);
		printf("%s\n", s.c_str());
	}
}

#define DECODE_RV64(arr) decode_rv64((riscv_ptr)arr, (riscv_ptr)arr + sizeof(arr), (riscv_ptr)arr - 0xffffffff80000000ULL);

int main(int argc, char *argv[])
{
	printf("sizeof(riscv_decode)=%lu\n", sizeof(riscv_decode));
#if 1
	//DECODE_RV64(test_code_1);
	DECODE_RV64(test_code_2);
#else
	std::vector<char> bin = read_file("bin/add_1.bin");
	decode_rv64((riscv_ptr)bin.data(), (riscv_ptr)bin.data() + bin.size(), (riscv_ptr)bin.data());
#endif

	return 0;
}
