//
//  riscv-meta.h
//
//  DANGER - This is machine generated code
//

#ifndef riscv_meta_h
#define riscv_meta_h

enum rvc_constraint
{
	rvc_end,
	rvc_imm_10,
	rvc_imm_12,
	rvc_imm_18,
	rvc_imm_6,
	rvc_imm_7,
	rvc_imm_8,
	rvc_imm_9,
	rvc_imm_not_zero,
	rvc_imm_scale_2,
	rvc_imm_scale_4,
	rvc_imm_scale_8,
	rvc_rd_comp,
	rvc_rd_eq_ra,
	rvc_rd_eq_rs1,
	rvc_rd_eq_sp,
	rvc_rd_eq_zero,
	rvc_rd_not_sp,
	rvc_rd_not_zero,
	rvc_rs1_comp,
	rvc_rs1_eq_sp,
	rvc_rs1_eq_zero,
	rvc_rs2_comp,
	rvc_rs2_eq_zero,
	rvc_rs2_not_zero,
};

enum riscv_csr
{
	riscv_csr_fflags = 0x001,
	riscv_csr_frm = 0x002,
	riscv_csr_fcsr = 0x003,
	riscv_csr_cycle = 0xC00,
	riscv_csr_time = 0xC01,
	riscv_csr_instret = 0xC02,
	riscv_csr_cycleh = 0xC80,
	riscv_csr_timeh = 0xC81,
	riscv_csr_instreth = 0xC82,
	riscv_csr_sstatus = 0x100,
	riscv_csr_stvec = 0x101,
	riscv_csr_sie = 0x104,
	riscv_csr_stimecmp = 0x121,
	riscv_csr_stime = 0xD01,
	riscv_csr_stimeh = 0xD81,
	riscv_csr_sscratch = 0x140,
	riscv_csr_sepc = 0x141,
	riscv_csr_scause = 0xD42,
	riscv_csr_sbadaddr = 0xD43,
	riscv_csr_sip = 0x144,
	riscv_csr_sptbr = 0x180,
	riscv_csr_sasid = 0x181,
	riscv_csr_cyclew = 0x900,
	riscv_csr_timew = 0x901,
	riscv_csr_instretw = 0x902,
	riscv_csr_cyclehw = 0x980,
	riscv_csr_timehw = 0x981,
	riscv_csr_instrethw = 0x982,
	riscv_csr_hstatus = 0x200,
	riscv_csr_htvec = 0x201,
	riscv_csr_htdeleg = 0x202,
	riscv_csr_htimecmp = 0x221,
	riscv_csr_htime = 0xE01,
	riscv_csr_htimeh = 0xE81,
	riscv_csr_hscratch = 0x240,
	riscv_csr_hepc = 0x241,
	riscv_csr_hcause = 0x242,
	riscv_csr_hbadaddr = 0x243,
	riscv_csr_stimew = 0xA01,
	riscv_csr_stimehw = 0xA81,
	riscv_csr_mcpuid = 0xF00,
	riscv_csr_mimpid = 0xF01,
	riscv_csr_mhartid = 0xF10,
	riscv_csr_mstatus = 0x300,
	riscv_csr_mtvec = 0x301,
	riscv_csr_mtdeleg = 0x302,
	riscv_csr_mie = 0x304,
	riscv_csr_mtimecmp = 0x321,
	riscv_csr_mscratch = 0x340,
	riscv_csr_mepc = 0x341,
	riscv_csr_mcause = 0x342,
	riscv_csr_mbadaddr = 0x343,
	riscv_csr_mip = 0x344,
	riscv_csr_mbase = 0x380,
	riscv_csr_mbound = 0x381,
	riscv_csr_mibase = 0x382,
	riscv_csr_mibound = 0x383,
	riscv_csr_mdbase = 0x384,
	riscv_csr_mdbound = 0x385,
	riscv_csr_htimew = 0xB01,
	riscv_csr_htimehw = 0xB81,
	riscv_csr_mtohost = 0x780,
	riscv_csr_mfromhost = 0x781,
};

enum riscv_ireg_name
{
	riscv_ireg_x0,
	riscv_ireg_x1,
	riscv_ireg_x2,
	riscv_ireg_x3,
	riscv_ireg_x4,
	riscv_ireg_x5,
	riscv_ireg_x6,
	riscv_ireg_x7,
	riscv_ireg_x8,
	riscv_ireg_x9,
	riscv_ireg_x10,
	riscv_ireg_x11,
	riscv_ireg_x12,
	riscv_ireg_x13,
	riscv_ireg_x14,
	riscv_ireg_x15,
	riscv_ireg_x16,
	riscv_ireg_x17,
	riscv_ireg_x18,
	riscv_ireg_x19,
	riscv_ireg_x20,
	riscv_ireg_x21,
	riscv_ireg_x22,
	riscv_ireg_x23,
	riscv_ireg_x24,
	riscv_ireg_x25,
	riscv_ireg_x26,
	riscv_ireg_x27,
	riscv_ireg_x28,
	riscv_ireg_x29,
	riscv_ireg_x30,
	riscv_ireg_x31,
};

enum riscv_ireg_alias
{
	riscv_ireg_zero,
	riscv_ireg_ra,
	riscv_ireg_sp,
	riscv_ireg_gp,
	riscv_ireg_tp,
	riscv_ireg_t0,
	riscv_ireg_t1,
	riscv_ireg_t2,
	riscv_ireg_s0,
	riscv_ireg_s1,
	riscv_ireg_a0,
	riscv_ireg_a1,
	riscv_ireg_a2,
	riscv_ireg_a3,
	riscv_ireg_a4,
	riscv_ireg_a5,
	riscv_ireg_a6,
	riscv_ireg_a7,
	riscv_ireg_s2,
	riscv_ireg_s3,
	riscv_ireg_s4,
	riscv_ireg_s5,
	riscv_ireg_s6,
	riscv_ireg_s7,
	riscv_ireg_s8,
	riscv_ireg_s9,
	riscv_ireg_s10,
	riscv_ireg_s11,
	riscv_ireg_t3,
	riscv_ireg_t4,
	riscv_ireg_t5,
	riscv_ireg_t6,
};

enum riscv_freg_name
{
	riscv_freg_f0,
	riscv_freg_f1,
	riscv_freg_f2,
	riscv_freg_f3,
	riscv_freg_f4,
	riscv_freg_f5,
	riscv_freg_f6,
	riscv_freg_f7,
	riscv_freg_f8,
	riscv_freg_f9,
	riscv_freg_f10,
	riscv_freg_f11,
	riscv_freg_f12,
	riscv_freg_f13,
	riscv_freg_f14,
	riscv_freg_f15,
	riscv_freg_f16,
	riscv_freg_f17,
	riscv_freg_f18,
	riscv_freg_f19,
	riscv_freg_f20,
	riscv_freg_f21,
	riscv_freg_f22,
	riscv_freg_f23,
	riscv_freg_f24,
	riscv_freg_f25,
	riscv_freg_f26,
	riscv_freg_f27,
	riscv_freg_f28,
	riscv_freg_f29,
	riscv_freg_f30,
	riscv_freg_f31,
};

enum riscv_freg_alias
{
	riscv_freg_ft0,
	riscv_freg_ft1,
	riscv_freg_ft2,
	riscv_freg_ft3,
	riscv_freg_ft4,
	riscv_freg_ft5,
	riscv_freg_ft6,
	riscv_freg_ft7,
	riscv_freg_fs0,
	riscv_freg_fs1,
	riscv_freg_fa0,
	riscv_freg_fa1,
	riscv_freg_fa2,
	riscv_freg_fa3,
	riscv_freg_fa4,
	riscv_freg_fa5,
	riscv_freg_fa6,
	riscv_freg_fa7,
	riscv_freg_fs2,
	riscv_freg_fs3,
	riscv_freg_fs4,
	riscv_freg_fs5,
	riscv_freg_fs6,
	riscv_freg_fs7,
	riscv_freg_fs8,
	riscv_freg_fs9,
	riscv_freg_fs10,
	riscv_freg_fs11,
	riscv_freg_ft8,
	riscv_freg_ft9,
	riscv_freg_ft10,
	riscv_freg_ft11,
};

enum riscv_inst_type
{
	riscv_inst_type_unknown,
	riscv_inst_type_none,
	riscv_inst_type_c_nop,
	riscv_inst_type_cb,
	riscv_inst_type_cb_sh5,
	riscv_inst_type_ci,
	riscv_inst_type_ci_sh5,
	riscv_inst_type_ci_16sp,
	riscv_inst_type_ci_lwsp,
	riscv_inst_type_ci_ldsp,
	riscv_inst_type_ci_li,
	riscv_inst_type_ci_lui,
	riscv_inst_type_ciw_4spn,
	riscv_inst_type_cj,
	riscv_inst_type_cl_lw,
	riscv_inst_type_cl_ld,
	riscv_inst_type_cr,
	riscv_inst_type_cr_mv,
	riscv_inst_type_cr_jalr,
	riscv_inst_type_cr_jr,
	riscv_inst_type_cs,
	riscv_inst_type_cs_sw,
	riscv_inst_type_cs_sd,
	riscv_inst_type_css_swsp,
	riscv_inst_type_css_sdsp,
	riscv_inst_type_i,
	riscv_inst_type_i_sh5,
	riscv_inst_type_i_sh6,
	riscv_inst_type_r,
	riscv_inst_type_r_4f,
	riscv_inst_type_s,
	riscv_inst_type_sb,
	riscv_inst_type_u,
	riscv_inst_type_uj,
};

enum riscv_op
{
	riscv_op_unknown,
	riscv_op_lui = 1,
	riscv_op_auipc = 2,
	riscv_op_jal = 3,
	riscv_op_jalr = 4,
	riscv_op_beq = 5,
	riscv_op_bne = 6,
	riscv_op_blt = 7,
	riscv_op_bge = 8,
	riscv_op_bltu = 9,
	riscv_op_bgeu = 10,
	riscv_op_lb = 11,
	riscv_op_lh = 12,
	riscv_op_lw = 13,
	riscv_op_lbu = 14,
	riscv_op_lhu = 15,
	riscv_op_sb = 16,
	riscv_op_sh = 17,
	riscv_op_sw = 18,
	riscv_op_addi = 19,
	riscv_op_slti = 20,
	riscv_op_sltiu = 21,
	riscv_op_xori = 22,
	riscv_op_ori = 23,
	riscv_op_andi = 24,
	riscv_op_slli_rv32i = 25,
	riscv_op_srli_rv32i = 26,
	riscv_op_srai_rv32i = 27,
	riscv_op_add = 28,
	riscv_op_sub = 29,
	riscv_op_sll = 30,
	riscv_op_slt = 31,
	riscv_op_sltu = 32,
	riscv_op_xor = 33,
	riscv_op_srl = 34,
	riscv_op_sra = 35,
	riscv_op_or = 36,
	riscv_op_and = 37,
	riscv_op_fence = 38,
	riscv_op_fence_i = 39,
	riscv_op_lwu = 40,
	riscv_op_ld = 41,
	riscv_op_sd = 42,
	riscv_op_slli_rv64i = 43,
	riscv_op_srli_rv64i = 44,
	riscv_op_srai_rv64i = 45,
	riscv_op_addiw = 46,
	riscv_op_slliw = 47,
	riscv_op_srliw = 48,
	riscv_op_sraiw = 49,
	riscv_op_addw = 50,
	riscv_op_subw = 51,
	riscv_op_sllw = 52,
	riscv_op_srlw = 53,
	riscv_op_sraw = 54,
	riscv_op_mul = 55,
	riscv_op_mulh = 56,
	riscv_op_mulhsu = 57,
	riscv_op_mulhu = 58,
	riscv_op_div = 59,
	riscv_op_divu = 60,
	riscv_op_rem = 61,
	riscv_op_remu = 62,
	riscv_op_mulw = 63,
	riscv_op_divw = 64,
	riscv_op_divuw = 65,
	riscv_op_remw = 66,
	riscv_op_remuw = 67,
	riscv_op_lr_w = 68,
	riscv_op_sc_w = 69,
	riscv_op_amoswap_w = 70,
	riscv_op_amoadd_w = 71,
	riscv_op_amoxor_w = 72,
	riscv_op_amoor_w = 73,
	riscv_op_amoand_w = 74,
	riscv_op_amomin_w = 75,
	riscv_op_amomax_w = 76,
	riscv_op_amominu_w = 77,
	riscv_op_amomaxu_w = 78,
	riscv_op_lr_d = 79,
	riscv_op_sc_d = 80,
	riscv_op_amoswap_d = 81,
	riscv_op_amoadd_d = 82,
	riscv_op_amoxor_d = 83,
	riscv_op_amoor_d = 84,
	riscv_op_amoand_d = 85,
	riscv_op_amomin_d = 86,
	riscv_op_amomax_d = 87,
	riscv_op_amominu_d = 88,
	riscv_op_amomaxu_d = 89,
	riscv_op_scall = 90,
	riscv_op_sbreak = 91,
	riscv_op_sret = 92,
	riscv_op_sfence_vm = 93,
	riscv_op_wfi = 94,
	riscv_op_mrth = 95,
	riscv_op_mrts = 96,
	riscv_op_hrts = 97,
	riscv_op_rdcycle = 98,
	riscv_op_rdtime = 99,
	riscv_op_rdinstret = 100,
	riscv_op_rdcycleh = 101,
	riscv_op_rdtimeh = 102,
	riscv_op_rdinstreth = 103,
	riscv_op_csrrw = 104,
	riscv_op_csrrs = 105,
	riscv_op_csrrc = 106,
	riscv_op_csrrwi = 107,
	riscv_op_csrrsi = 108,
	riscv_op_csrrci = 109,
	riscv_op_flw = 110,
	riscv_op_fsw = 111,
	riscv_op_fmadd_s = 112,
	riscv_op_fmsub_s = 113,
	riscv_op_fnmsub_s = 114,
	riscv_op_fnmadd_s = 115,
	riscv_op_fadd_s = 116,
	riscv_op_fsub_s = 117,
	riscv_op_fmul_s = 118,
	riscv_op_fdiv_s = 119,
	riscv_op_fsgnj_s = 120,
	riscv_op_fsgnjn_s = 121,
	riscv_op_fsgnjx_s = 122,
	riscv_op_fmin_s = 123,
	riscv_op_fmax_s = 124,
	riscv_op_fsqrt_s = 125,
	riscv_op_fle_s = 126,
	riscv_op_flt_s = 127,
	riscv_op_feq_s = 128,
	riscv_op_fcvt_w_s = 129,
	riscv_op_fcvt_wu_s = 130,
	riscv_op_fcvt_s_w = 131,
	riscv_op_fcvt_s_wu = 132,
	riscv_op_fmv_x_s = 133,
	riscv_op_fclass_s = 134,
	riscv_op_fmv_s_x = 135,
	riscv_op_fcvt_l_s = 136,
	riscv_op_fcvt_lu_s = 137,
	riscv_op_fcvt_s_l = 138,
	riscv_op_fcvt_s_lu = 139,
	riscv_op_fld = 140,
	riscv_op_fsd = 141,
	riscv_op_fmadd_d = 142,
	riscv_op_fmsub_d = 143,
	riscv_op_fnmsub_d = 144,
	riscv_op_fnmadd_d = 145,
	riscv_op_fadd_d = 146,
	riscv_op_fsub_d = 147,
	riscv_op_fmul_d = 148,
	riscv_op_fdiv_d = 149,
	riscv_op_fsgnj_d = 150,
	riscv_op_fsgnjn_d = 151,
	riscv_op_fsgnjx_d = 152,
	riscv_op_fmin_d = 153,
	riscv_op_fmax_d = 154,
	riscv_op_fcvt_s_d = 155,
	riscv_op_fcvt_d_s = 156,
	riscv_op_fsqrt_d = 157,
	riscv_op_fle_d = 158,
	riscv_op_flt_d = 159,
	riscv_op_feq_d = 160,
	riscv_op_fcvt_w_d = 161,
	riscv_op_fcvt_wu_d = 162,
	riscv_op_fcvt_d_w = 163,
	riscv_op_fcvt_d_wu = 164,
	riscv_op_fclass_d = 165,
	riscv_op_fcvt_l_d = 166,
	riscv_op_fcvt_lu_d = 167,
	riscv_op_fmv_x_d = 168,
	riscv_op_fcvt_d_l = 169,
	riscv_op_fcvt_d_lu = 170,
	riscv_op_fmv_d_x = 171,
	riscv_op_frcsr = 172,
	riscv_op_frrm = 173,
	riscv_op_frflags = 174,
	riscv_op_fscsr = 175,
	riscv_op_fsrm = 176,
	riscv_op_fsflags = 177,
	riscv_op_fsrmi = 178,
	riscv_op_fsflagsi = 179,
	riscv_op_c_addi4spn = 180,
	riscv_op_c_fld = 181,
	riscv_op_c_lw = 182,
	riscv_op_c_flw = 183,
	riscv_op_c_fsd = 184,
	riscv_op_c_sw = 185,
	riscv_op_c_fsw = 186,
	riscv_op_c_nop = 187,
	riscv_op_c_addi = 188,
	riscv_op_c_jal = 189,
	riscv_op_c_li = 190,
	riscv_op_c_lui = 191,
	riscv_op_c_addi16sp = 192,
	riscv_op_c_srli = 193,
	riscv_op_c_srai = 194,
	riscv_op_c_andi = 195,
	riscv_op_c_sub = 196,
	riscv_op_c_xor = 197,
	riscv_op_c_or = 198,
	riscv_op_c_and = 199,
	riscv_op_c_subw = 200,
	riscv_op_c_addw = 201,
	riscv_op_c_j = 202,
	riscv_op_c_beqz = 203,
	riscv_op_c_bnez = 204,
	riscv_op_c_slli = 205,
	riscv_op_c_fldsp = 206,
	riscv_op_c_lwsp = 207,
	riscv_op_c_flwsp = 208,
	riscv_op_c_jr = 209,
	riscv_op_c_mv = 210,
	riscv_op_c_ebreak = 211,
	riscv_op_c_jalr = 212,
	riscv_op_c_add = 213,
	riscv_op_c_fsdsp = 214,
	riscv_op_c_swsp = 215,
	riscv_op_c_fswsp = 216,
	riscv_op_c_ld = 217,
	riscv_op_c_sd = 218,
	riscv_op_c_addiw = 219,
	riscv_op_c_ldsp = 220,
	riscv_op_c_sdsp = 221,
};

struct riscv_comp_data
{
	const int op;
	const rvc_constraint* constraints;
};

extern "C" {
	extern const char* riscv_i_registers[];
	extern const char* riscv_f_registers[];
	extern const char* riscv_instruction_name[];
	extern const riscv_inst_type riscv_instruction_type[];
	extern const riscv_wu riscv_instruction_match[];
	extern const riscv_wu riscv_instruction_mask[];
	extern const rvf* riscv_instruction_format[];
	extern const riscv_comp_data* riscv_instruction_comp[];
	extern const int riscv_instruction_decomp[];
}

#endif
